'use client';
import {useEffect,useMemo,useState} from 'react';
import WorkspaceShell,{fieldStyle,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtDate,fmtMoney,requireToken} from '../../lib/api';

type Journal={journalNo:string;journalDate:string;period:string;currency:string;description?:string;reference?:string;status:string;totalDebit:number;totalCredit:number;lines:any[]};
export default function GeneralLedgerPage(){
 const [token,setToken]=useState('');const [journals,setJournals]=useState<Journal[]>([]);const [periods,setPeriods]=useState<any[]>([]);const [tb,setTb]=useState<any[]>([]);const [tax,setTax]=useState<any[]>([]);const [dash,setDash]=useState<any>({});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({journalDate:new Date().toISOString().slice(0,10),currency:'USD',description:'Manual journal',reference:'',debitAccount:'1100-AR',creditAccount:'4000-REVENUE',amount:'',taxCode:'',taxRate:''});
 useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
 async function load(t=token){try{const [j,p,b,tb0,tax0]=await Promise.all([api('/general-ledger/journals',t),api('/general-ledger/periods',t),api('/general-ledger/dashboard',t),api('/general-ledger/trial-balance',t),api('/general-ledger/tax-summary',t)]);setJournals(j||[]);setPeriods(p||[]);setDash(b||{});setTb(tb0||[]);setTax(tax0||[]);}catch(e:any){setMessage(e.message||'Unable to load ledger');}}
 async function action(path:string,body?:any,msg='Updated'){setBusy(true);setMessage('');try{await api(path,token,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)});setMessage(msg);await load();}catch(e:any){setMessage(e.message||'Action failed');}finally{setBusy(false);}}
 async function create(){const amount=Number(form.amount);if(!Number.isFinite(amount)||amount<=0){setMessage('Enter a valid amount.');return;}await action('/general-ledger/journals',{journalDate:form.journalDate,currency:form.currency,description:form.description,reference:form.reference,lines:[{account:form.debitAccount,debit:amount,credit:0,taxCode:form.taxCode||null,taxRate:form.taxRate?Number(form.taxRate):null},{account:form.creditAccount,debit:0,credit:amount,taxCode:form.taxCode||null,taxRate:form.taxRate?Number(form.taxRate):null}]},'Balanced journal created.');}
 const currentPeriod=useMemo(()=>form.journalDate.slice(0,7),[form.journalDate]);const period=periods.find(p=>p.period===currentPeriod)||{period:currentPeriod,status:'OPEN'};
 return <WorkspaceShell title="General Ledger / Tax / Period Close" subtitle="Journal control, trial balance, VAT/tax reporting and accounting period governance" active="/general-ledger" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
 {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
 <div className="grid" style={{marginBottom:12}}><div className="card"><div className="sub">JOURNALS</div><div className="kpi">{dash.journalCount||0}</div></div><div className="card"><div className="sub">DRAFT</div><div className="kpi">{dash.draftCount||0}</div></div><div className="card"><div className="sub">POSTED</div><div className="kpi">{dash.postedCount||0}</div></div><div className="card"><div className="sub">CLOSED PERIODS</div><div className="kpi">{dash.closedPeriods||0}</div></div></div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Create Balanced Journal</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}>
 <label><span style={labelStyle}>Date</span><input type="date" style={fieldStyle} value={form.journalDate} onChange={e=>setForm({...form,journalDate:e.target.value})}/></label><label><span style={labelStyle}>Currency</span><select style={fieldStyle} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{['USD','EUR','GBP','AED'].map(x=><option key={x}>{x}</option>)}</select></label><label><span style={labelStyle}>Debit Account</span><input style={fieldStyle} value={form.debitAccount} onChange={e=>setForm({...form,debitAccount:e.target.value})}/></label><label><span style={labelStyle}>Credit Account</span><input style={fieldStyle} value={form.creditAccount} onChange={e=>setForm({...form,creditAccount:e.target.value})}/></label><label><span style={labelStyle}>Amount</span><input type="number" step="0.01" style={fieldStyle} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label><span style={labelStyle}>VAT / Tax Code</span><input style={fieldStyle} value={form.taxCode} onChange={e=>setForm({...form,taxCode:e.target.value})} placeholder="VAT21 / ZERO / EXEMPT"/></label><label><span style={labelStyle}>Tax %</span><input type="number" step="0.01" style={fieldStyle} value={form.taxRate} onChange={e=>setForm({...form,taxRate:e.target.value})}/></label><label><span style={labelStyle}>Reference</span><input style={fieldStyle} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label></div><div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><button className="btn" disabled={busy||period.status==='CLOSED'} onClick={create}>Create Journal</button><span className="status">Period {currentPeriod}: {period.status}</span><button className="btn" disabled={busy} onClick={()=>action(`/general-ledger/periods/${currentPeriod}/close`,undefined,`Period ${currentPeriod} closed.`)}>Close Period</button><button className="btn" disabled={busy} onClick={()=>action(`/general-ledger/periods/${currentPeriod}/reopen`,undefined,`Period ${currentPeriod} reopened.`)}>Reopen</button></div></div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Journal Register</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Journal</th><th>Date</th><th>Period</th><th>Currency</th><th>Description</th><th>Debit</th><th>Credit</th><th>Status</th><th>Action</th></tr></thead><tbody>{journals.map(j=><tr key={j.journalNo}><td><b>{j.journalNo}</b><div className="sub">{j.reference||'-'}</div></td><td>{fmtDate(j.journalDate)}</td><td>{j.period}</td><td>{j.currency}</td><td>{j.description||'-'}</td><td>{fmtMoney(j.totalDebit,j.currency)}</td><td>{fmtMoney(j.totalCredit,j.currency)}</td><td><span className="status">{j.status}</span></td><td>{j.status==='DRAFT'&&<button className="btn" disabled={busy} onClick={()=>action(`/general-ledger/journals/${j.journalNo}/post`,undefined,`${j.journalNo} posted.`)}>Post</button>}</td></tr>)}{journals.length===0&&<tr><td colSpan={9}>No journals yet.</td></tr>}</tbody></table></div></div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Trial Balance</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Currency</th><th>Account</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{tb.map((r:any)=><tr key={`${r.currency}-${r.account}`}><td>{r.currency}</td><td><b>{r.account}</b></td><td>{fmtMoney(r.debit,r.currency)}</td><td>{fmtMoney(r.credit,r.currency)}</td><td>{fmtMoney(r.balance,r.currency)}</td></tr>)}{tb.length===0&&<tr><td colSpan={5}>Post journals to populate the trial balance.</td></tr>}</tbody></table></div></div>
 <div className="card"><h3 style={sectionTitle}>VAT / Tax Summary</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Period</th><th>Currency</th><th>Tax Code</th><th>Rate</th><th>Taxable Base</th><th>Tax Amount</th></tr></thead><tbody>{tax.map((r:any,i:number)=><tr key={i}><td>{r.period}</td><td>{r.currency}</td><td><b>{r.taxCode}</b></td><td>{r.taxRate}%</td><td>{fmtMoney(r.taxableBase,r.currency)}</td><td>{fmtMoney(r.taxAmount,r.currency)}</td></tr>)}{tax.length===0&&<tr><td colSpan={6}>No posted tax-coded journals yet.</td></tr>}</tbody></table></div></div>
 </WorkspaceShell>;
}
