import { BadRequestException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';

const SOURCE='ANCLINE_QUALITY';
const now=()=>new Date();
const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;

@Injectable()
export class QualityService {
  constructor(private prisma:PrismaService,private scope:ScopeService){}
  private events(source=SOURCE){return this.prisma.integrationEvent.findMany({where:{sourceSystem:source},orderBy:{createdAt:'asc'}});}
  private p(e:any){return (e?.payload||{}) as any;}
  private latest(rows:any[],type:string,eventTypes?:string[]){const m=new Map<string,any>();for(const e of rows)if(e.objectType===type&&(!eventTypes||eventTypes.includes(e.eventType)))m.set(e.objectId,e);return [...m.values()].map(e=>this.p(e));}
  private write(eventType:string,objectType:string,objectId:string,payload:any){return this.prisma.integrationEvent.create({data:{sourceSystem:SOURCE,eventType,objectType,objectId,status:'COMPLETED',payload,completedAt:now()}});}

  async dashboard(user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events(),ncrs=this.latest(rows,'NCR',['NCR_SET','NCR_UPDATED']),capas=this.latest(rows,'CAPA',['CAPA_SET','CAPA_UPDATED']),audits=this.latest(rows,'QualityAudit',['AUDIT_SET','AUDIT_UPDATED']),sops=this.latest(rows,'SOP',['SOP_SET']),att=this.latest(rows,'SOPAttestation',['SOP_ATTESTED']);const external=(await Promise.all(['ANCLINE_CUSTOMER_SERVICE','ANCLINE_VENDOR_CONTROL','ANCLINE_ENTERPRISE_RISK'].map(s=>this.events(s)))).flat();const patterns=new Map<string,{key:string;count:number;sources:Set<string>}>();for(const e of external){const p=this.p(e),key=String(p.category||p.type||p.severity||e.eventType||'OTHER').toUpperCase();const x=patterns.get(key)||{key,count:0,sources:new Set<string>()};x.count++;x.sources.add(e.sourceSystem);patterns.set(key,x);}const recurring=[...patterns.values()].filter(x=>x.count>=3).map(x=>({key:x.key,count:x.count,sources:[...x.sources]})).sort((a,b)=>b.count-a.count);const overdueCapa=capas.filter((x:any)=>!['VERIFIED','CLOSED'].includes(String(x.status||'').toUpperCase())&&x.dueAt&&new Date(x.dueAt).getTime()<Date.now());return {summary:{openNcr:ncrs.filter((x:any)=>!['CLOSED','CANCELLED'].includes(String(x.status||'').toUpperCase())).length,openCapa:capas.filter((x:any)=>!['VERIFIED','CLOSED','CANCELLED'].includes(String(x.status||'').toUpperCase())).length,overdueCapa:overdueCapa.length,openAudits:audits.filter((x:any)=>!['CLOSED','COMPLETE'].includes(String(x.status||'').toUpperCase())).length,activeSops:sops.filter((x:any)=>x.active!==false).length,attestations:att.length,recurringPatterns:recurring.length},ncrs,capas,audits,sops,attestations:att,recurring,overdueCapa};}

  async ncr(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.title)throw new BadRequestException('NCR title is required');const ncrId=String(body.ncrId||id('NCR'));const payload={ncrId,title:String(body.title),source:String(body.source||'OPERATIONS').toUpperCase(),severity:String(body.severity||'MEDIUM').toUpperCase(),category:String(body.category||'PROCESS').toUpperCase(),bookingId:body.bookingId||null,organizationId:body.organizationId||null,branchId:body.branchId||null,description:body.description||null,containment:body.containment||null,rootCauseMethod:body.rootCauseMethod||null,rootCause:body.rootCause||null,status:String(body.status||'OPEN').toUpperCase(),owner:body.owner||user.sub,targetCloseAt:body.targetCloseAt||null,createdBy:user.sub,updatedBy:user.sub,updatedAt:now().toISOString()};await this.write('NCR_SET','NCR',ncrId,payload);return payload;}
  async updateNcr(ncrId:string,body:any,user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events(),cur=this.latest(rows,'NCR',['NCR_SET','NCR_UPDATED']).find((x:any)=>x.ncrId===ncrId);if(!cur)throw new BadRequestException('NCR not found');const payload={...cur,...body,ncrId,status:String(body.status||cur.status).toUpperCase(),updatedBy:user.sub,updatedAt:now().toISOString()};await this.write('NCR_UPDATED','NCR',ncrId,payload);return payload;}

  async capa(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.ncrId||!body?.action)throw new BadRequestException('NCR and corrective action are required');const capaId=String(body.capaId||id('CAPA'));const payload={capaId,ncrId:String(body.ncrId),action:String(body.action),actionType:String(body.actionType||'CORRECTIVE').toUpperCase(),owner:body.owner||user.sub,dueAt:body.dueAt||null,status:String(body.status||'OPEN').toUpperCase(),verificationMethod:body.verificationMethod||null,effectivenessResult:body.effectivenessResult||null,createdBy:user.sub,updatedBy:user.sub,updatedAt:now().toISOString()};await this.write('CAPA_SET','CAPA',capaId,payload);return payload;}
  async updateCapa(capaId:string,body:any,user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events(),cur=this.latest(rows,'CAPA',['CAPA_SET','CAPA_UPDATED']).find((x:any)=>x.capaId===capaId);if(!cur)throw new BadRequestException('CAPA not found');const status=String(body.status||cur.status).toUpperCase();if(status==='VERIFIED'&&!String(body.effectivenessResult||cur.effectivenessResult||'').trim())throw new BadRequestException('Effectiveness result is required before verification');const payload={...cur,...body,capaId,status,updatedBy:user.sub,updatedAt:now().toISOString()};await this.write('CAPA_UPDATED','CAPA',capaId,payload);return payload;}

  async audit(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.title)throw new BadRequestException('Audit title is required');const auditId=String(body.auditId||id('AUD'));const payload={auditId,title:String(body.title),auditType:String(body.auditType||'INTERNAL').toUpperCase(),scope:body.scope||null,auditor:body.auditor||user.sub,plannedAt:body.plannedAt||null,status:String(body.status||'PLANNED').toUpperCase(),score:body.score!=null?Number(body.score):null,findings:Number(body.findings||0),majorFindings:Number(body.majorFindings||0),notes:body.notes||null,updatedBy:user.sub};await this.write('AUDIT_SET','QualityAudit',auditId,payload);return payload;}
  async updateAudit(auditId:string,body:any,user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events(),cur=this.latest(rows,'QualityAudit',['AUDIT_SET','AUDIT_UPDATED']).find((x:any)=>x.auditId===auditId);if(!cur)throw new BadRequestException('Audit not found');const payload={...cur,...body,auditId,status:String(body.status||cur.status).toUpperCase(),score:body.score!=null?Number(body.score):cur.score,findings:body.findings!=null?Number(body.findings):cur.findings,majorFindings:body.majorFindings!=null?Number(body.majorFindings):cur.majorFindings,updatedBy:user.sub};await this.write('AUDIT_UPDATED','QualityAudit',auditId,payload);return payload;}

  async sop(body:any,user:ScopeUser){this.scope.assertFinanceAccess(user);if(!body?.code||!body?.title)throw new BadRequestException('SOP code and title are required');const sopId=String(body.sopId||id('SOP'));const payload={sopId,code:String(body.code),title:String(body.title),version:String(body.version||'1.0'),owner:body.owner||user.sub,effectiveAt:body.effectiveAt||now().toISOString(),reviewAt:body.reviewAt||null,active:body.active!==false,requiresAttestation:body.requiresAttestation!==false,notes:body.notes||null,updatedBy:user.sub};await this.write('SOP_SET','SOP',sopId,payload);return payload;}
  async attest(sopId:string,body:any,user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events(),sop=this.latest(rows,'SOP',['SOP_SET']).find((x:any)=>x.sopId===sopId&&x.active!==false);if(!sop)throw new BadRequestException('Active SOP not found');const attestationId=`${sopId}:${user.sub}`;const payload={attestationId,sopId,sopCode:sop.code,sopVersion:sop.version,userId:user.sub,attestedAt:now().toISOString(),comment:body?.comment||null};await this.write('SOP_ATTESTED','SOPAttestation',attestationId,payload);return payload;}
}
