'use client';
import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

export default function CommercialGuardrailsPage(){
 const [token,setToken]=useState(''),[data,setData]=useState<any>({summary:{},policies:[],commitments:[],approvals:[],contracts:[],bookingChecks:[]}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [policy,setPolicy]=useState<any>({scopeType:'GLOBAL',scopeKey:'GLOBAL',minMarginPct:'10',minGp:'0',expiryWarningDays:'7',requireQuote:true,requireCreditApprovalForHighRisk:true,active:true,notes:''});
 const [commitment,setCommitment]=useState<any>({customerId:'',name:'Annual volume commitment',lane:'',targetQuantity:'100',quantityUnit:'TEU',rebatePct:'2',currency:'USD',validFrom:new Date().toISOString().slice(0,10),validTo:new Date(Date.now()+365*86400000).toISOString().slice(0,10),notes:''});
 useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
 async function load(t=token){try{setData(await api('/commercial-guardrails/dashboard',t));}catch(e:any){setMessage(e.message||'Unable to load commercial guardrails');}}
 async function savePolicy(){setBusy(true);setMessage('');try{await api('/commercial-guardrails/policies',token,{method:'POST',body:JSON.stringify({...policy,minMarginPct:Number(policy.minMarginPct),minGp:Number(policy.minGp),expiryWarningDays:Number(policy.expiryWarningDays)})});setMessage('Commercial policy saved.');await load();}catch(e:any){setMessage(e.message||'Policy could not be saved');}finally{setBusy(false);}}
 async function saveCommitment(){setBusy(true);setMessage('');try{await api('/commercial-guardrails/commitments',token,{method:'POST',body:JSON.stringify({...commitment,targetQuantity:Number(commitment.targetQuantity),rebatePct:Number(commitment.rebatePct)})});setMessage('Volume / rebate commitment created.');await load();}catch(e:any){setMessage(e.message||'Commitment could not be created');}finally{setBusy(false);}}
 async function decide(id:string,d:string){setBusy(true);try{await api(`/commercial-guardrails/approvals/${id}/${d}`,token,{method:'POST',body:JSON.stringify({})});await load();}catch(e:any){setMessage(e.message||'Decision failed');}finally{setBusy(false);}}
 const s=data?.summary||{};
 return <WorkspaceShell title="Commercial Guardrails" subtitle="Margin protection, rate validity, credit-linked approvals, contract utilization and rebate commitments" active="/commercial-guardrails" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
  {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:12}}>{[['Active Policies',s.activePolicies],['Pending Approvals',s.pendingApprovals],['Blocked Bookings',s.blockedBookings],['Expiring Rates',s.expiringRates],['Under Commitment',s.underCommitmentContracts],['Rebate Eligible',s.rebateEligible]].map(([a,b])=><div className="card" key={String(a)}><div className="sub">{a}</div><div style={{fontSize:24,fontWeight:800}}>{b??0}</div></div>)}</div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Commercial Policy</h3><div style={formGrid}>
   <label><span style={labelStyle}>Scope</span><select style={fieldStyle} value={policy.scopeType} onChange={e=>setPolicy({...policy,scopeType:e.target.value,scopeKey:e.target.value==='GLOBAL'?'GLOBAL':''})}>{['GLOBAL','CUSTOMER','LANE'].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span style={labelStyle}>Scope Key</span><input style={fieldStyle} value={policy.scopeKey} onChange={e=>setPolicy({...policy,scopeKey:e.target.value})} placeholder="Customer ID or ORIGIN->DESTINATION"/></label>
   <label><span style={labelStyle}>Minimum Margin %</span><input type="number" style={fieldStyle} value={policy.minMarginPct} onChange={e=>setPolicy({...policy,minMarginPct:e.target.value})}/></label>
   <label><span style={labelStyle}>Minimum GP</span><input type="number" style={fieldStyle} value={policy.minGp} onChange={e=>setPolicy({...policy,minGp:e.target.value})}/></label>
   <label><span style={labelStyle}>Rate Expiry Warning Days</span><input type="number" style={fieldStyle} value={policy.expiryWarningDays} onChange={e=>setPolicy({...policy,expiryWarningDays:e.target.value})}/></label>
  </div><div style={{display:'flex',gap:14,marginTop:10,flexWrap:'wrap'}}><label><input type="checkbox" checked={policy.requireQuote} onChange={e=>setPolicy({...policy,requireQuote:e.target.checked})}/> Require quote</label><label><input type="checkbox" checked={policy.requireCreditApprovalForHighRisk} onChange={e=>setPolicy({...policy,requireCreditApprovalForHighRisk:e.target.checked})}/> High-risk credit approval</label><button className="btn" disabled={busy} onClick={()=>void savePolicy()}>Save Policy</button></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Confirmation Guardrail Queue</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Booking</th><th>Lane</th><th>Quote</th><th>Margin</th><th>GP</th><th>Credit</th><th>Control</th></tr></thead><tbody>{(data.bookingChecks||[]).map((x:any)=><tr key={x.bookingId}><td>{x.bookingNo}</td><td>{x.lane}</td><td>{x.quoteNo||'—'}</td><td>{x.marginPct}%</td><td>{x.gp}</td><td>{x.creditRisk}{x.creditHold?' / HOLD':''}</td><td>{x.clear?'CLEAR':x.blockers?.join('; ')}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Commercial Exception Approvals</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Booking</th><th>Reasons</th><th>Margin</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data.approvals||[]).map((x:any)=><tr key={x.approvalId}><td>{x.bookingNo||x.bookingId}</td><td>{(x.reasons||[]).join('; ')}</td><td>{x.marginPct}%</td><td>{x.status}</td><td>{x.status==='PENDING'&&<><button className="btn" disabled={busy} onClick={()=>void decide(x.approvalId,'APPROVE')}>Approve</button> <button className="btn" disabled={busy} onClick={()=>void decide(x.approvalId,'REJECT')}>Reject</button></>}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Contract Utilization</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Contract</th><th>Trade</th><th>Minimum</th><th>Used</th><th>Attainment</th><th>Status</th></tr></thead><tbody>{(data.contracts||[]).map((x:any)=><tr key={x.contractId}><td>{x.contractNo}</td><td>{x.trade||'All'}</td><td>{x.minimumQuantity||'—'} {x.quantityUnit||''}</td><td>{x.utilizedQuantity}</td><td>{x.attainmentPct==null?'—':`${x.attainmentPct}%`}</td><td>{x.status}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Volume / Rebate Commitment</h3><div style={formGrid}>{['customerId','name','lane','targetQuantity','quantityUnit','rebatePct','currency','validFrom','validTo'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type={k==='validFrom'||k==='validTo'?'date':k==='targetQuantity'||k==='rebatePct'?'number':'text'} style={fieldStyle} value={commitment[k]} onChange={e=>setCommitment({...commitment,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void saveCommitment()}>Create Commitment</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Name</th><th>Customer</th><th>Target</th><th>Used</th><th>Attainment</th><th>Rebate</th><th>Eligibility</th></tr></thead><tbody>{(data.commitments||[]).map((x:any)=><tr key={x.commitmentId}><td>{x.name}</td><td>{x.customerId}</td><td>{x.targetQuantity} {x.quantityUnit}</td><td>{x.utilizedQuantity}</td><td>{x.attainmentPct}%</td><td>{x.rebatePct}%</td><td>{x.projectedRebateEligible?'ELIGIBLE':'TRACKING'}</td></tr>)}</tbody></table></div></div>
 </WorkspaceShell>;
}
