'use client';
import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,labelStyle,formGrid,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtDate,requireToken} from '../../lib/api';

export default function WorkflowAutomationPage(){
 const [token,setToken]=useState(''),[d,setD]=useState<any>({summary:{},workflows:[],runs:[],timers:[],notifications:[]}),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 const [process,setProcess]=useState('BOOKING'),[trigger,setTrigger]=useState('BOOKING_CONFIRMED'),[bookingId,setBookingId]=useState(''),[objectType,setObjectType]=useState('Booking'),[objectId,setObjectId]=useState(''),[idempotencyKey,setKey]=useState(''),[context,setContext]=useState('{}'),[preview,setPreview]=useState<any>(null);
 useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
 async function load(t=token){try{setD(await api('/workflow-automation/dashboard',t));}catch(e:any){setMsg(e.message||'Unable to load workflow automation');}}
 function body(){let c:any={};try{c=JSON.parse(context||'{}');}catch{throw new Error('Context must be valid JSON');}return {process,trigger,bookingId:bookingId||null,objectType:objectType||null,objectId:objectId||null,idempotencyKey:idempotencyKey||null,context:c};}
 async function act(kind:'preview'|'trigger'){setBusy(kind);setMsg('');try{const r=await api(`/workflow-automation/${kind}`,token,{method:'POST',body:JSON.stringify(body())});if(kind==='preview')setPreview(r);else{setMsg(`Automation run ${r.status}: ${r.resultCount||0} actions, ${r.errorCount||0} errors.`);setKey('');await load();}}catch(e:any){setMsg(e.message||'Automation action failed');}finally{setBusy('');}}
 async function runDue(){setBusy('due');setMsg('');try{const r=await api('/workflow-automation/run-due',token,{method:'POST'});setMsg(`Due escalations: ${r.executed||0} executed, ${r.failed||0} failed.`);await load();}catch(e:any){setMsg(e.message||'Unable to run escalations');}finally{setBusy('');}}
 const s=d.summary||{};
 return <WorkspaceShell title="Workflow Automation / Orchestration" subtitle="Governance rules · cross-module actions · approvals · tasks · notifications · escalations" active="/workflow-automation" actions={<><button className="btn" onClick={runDue} disabled={!!busy}>{busy==='due'?'Running...':`Run Due Escalations (${s.dueTimers||0})`}</button><button className="btn" onClick={()=>load()}>Refresh</button></>}>
 {msg&&<div className="card" style={{marginBottom:12}}>{msg}</div>}
 <div className="grid" style={{marginBottom:12}}>{[['ACTIVE RULES',s.activeRules],['EXECUTIONS',s.executions],['WITH ERRORS',s.executionsWithErrors],['PENDING TIMERS',s.pendingTimers],['DUE TIMERS',s.dueTimers],['OPEN TASKS',s.openTasks],['PENDING APPROVALS',s.pendingApprovals],['NOTIFICATIONS',s.automationNotifications]].map(([a,b]:any)=><div className="card" key={a}><div className="sub">{a}</div><div className="kpi">{b||0}</div></div>)}</div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Trigger / Simulation Console</h3><div style={formGrid}><label><span style={labelStyle}>Process</span><input style={fieldStyle} value={process} onChange={e=>setProcess(e.target.value)}/></label><label><span style={labelStyle}>Trigger</span><input style={fieldStyle} value={trigger} onChange={e=>setTrigger(e.target.value)}/></label><label><span style={labelStyle}>Booking ID</span><input style={fieldStyle} value={bookingId} onChange={e=>setBookingId(e.target.value)}/></label><label><span style={labelStyle}>Object Type</span><input style={fieldStyle} value={objectType} onChange={e=>setObjectType(e.target.value)}/></label><label><span style={labelStyle}>Object ID</span><input style={fieldStyle} value={objectId} onChange={e=>setObjectId(e.target.value)}/></label><label><span style={labelStyle}>Idempotency Key</span><input style={fieldStyle} value={idempotencyKey} onChange={e=>setKey(e.target.value)}/></label></div><label style={{display:'block',marginTop:10}}><span style={labelStyle}>Context JSON</span><textarea style={{...fieldStyle,minHeight:120,fontFamily:'monospace'}} value={context} onChange={e=>setContext(e.target.value)}/></label><div style={{display:'flex',gap:8,justifyContent:'flex-end',marginTop:10}}><button className="btn" disabled={!!busy} onClick={()=>act('preview')}>Preview Rules</button><button className="btn" disabled={!!busy} onClick={()=>act('trigger')}>{busy==='trigger'?'Executing...':'Execute Trigger'}</button></div>{preview&&<pre style={{whiteSpace:'pre-wrap',background:'#f6f8fa',padding:10,marginTop:10,maxHeight:300,overflow:'auto'}}>{JSON.stringify(preview,null,2)}</pre>}</div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Active Governance Workflow Rules</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Process</th><th>Trigger</th><th>Condition</th><th>Action</th><th>Owner</th><th>Escalate</th></tr></thead><tbody>{(d.workflows||[]).map((r:any)=><tr key={r.workflowId}><td>{r.process}</td><td>{r.trigger}</td><td>{r.conditionField?`${r.conditionField} ${r.operator} ${r.conditionValue??''}`:'Always'}</td><td>{r.action}</td><td>{r.ownerRole||'-'}</td><td>{r.escalateAfterMinutes!=null?`${r.escalateAfterMinutes} min`:'-'}</td></tr>)}</tbody></table></div></div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Execution History</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Executed</th><th>Process</th><th>Trigger</th><th>Rules</th><th>Results</th><th>Errors</th><th>Status</th></tr></thead><tbody>{(d.runs||[]).map((r:any)=><tr key={r.runId}><td>{fmtDate(r.executedAt||r.updatedAt)}</td><td>{r.process||'-'}</td><td>{r.trigger}</td><td>{r.matchedRuleCount||0}</td><td>{r.resultCount||0}</td><td>{r.errorCount||0}</td><td>{r.status}</td></tr>)}</tbody></table></div></div>
 <div className="card"><h3 style={sectionTitle}>Escalation Timers</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Due</th><th>Process</th><th>Trigger</th><th>Owner</th><th>Status</th><th>Task</th></tr></thead><tbody>{(d.timers||[]).map((r:any)=><tr key={r.timerId}><td>{fmtDate(r.dueAt)}</td><td>{r.process}</td><td>{r.trigger}</td><td>{r.ownerRole||'-'}</td><td>{r.status}</td><td>{r.taskId||'-'}</td></tr>)}</tbody></table></div></div>
 </WorkspaceShell>;
}
