'use client';

import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

export default function EnterpriseReportingPage(){
  const [token,setToken]=useState('');const [data,setData]=useState<any>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const [report,setReport]=useState({name:'Executive Weekly Pack',reportType:'EXECUTIVE_KPI',frequency:'WEEKLY',recipients:'',notes:''});
  const [view,setView]=useState({name:'My Branch View',dimension:'BRANCH',shared:false});
  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
  async function load(t=token){try{setData(await api('/enterprise-reporting/dashboard',t));}catch(e:any){setMessage(e.message||'Unable to load reporting data');}}
  async function saveReport(){setBusy(true);setMessage('');try{await api('/enterprise-reporting/report-definitions',token,{method:'POST',body:JSON.stringify({...report,recipients:report.recipients.split(',').map(x=>x.trim()).filter(Boolean)})});setMessage('Report definition saved.');await load();}catch(e:any){setMessage(e.message||'Could not save report definition');}finally{setBusy(false);}}
  async function saveView(){setBusy(true);setMessage('');try{await api('/enterprise-reporting/saved-views',token,{method:'POST',body:JSON.stringify(view)});setMessage('Saved view created.');await load();}catch(e:any){setMessage(e.message||'Could not save view');}finally{setBusy(false);}}
  async function run(id:string){setBusy(true);setMessage('');try{await api(`/enterprise-reporting/reports/${id}/run`,token,{method:'POST'});setMessage('Report snapshot generated.');await load();}catch(e:any){setMessage(e.message||'Could not run report');}finally{setBusy(false);}}
  const s=data?.summary||{};const cards=[['TOTAL BOOKINGS',s.totalBookings],['ACTIVE',s.activeBookings],['NEGATIVE GP',s.negativeGpJobs],['OVERDUE ETA',s.overdueEta],['UNBILLED REVENUE',s.unbilledRevenueJobs],['PENDING APPROVALS',s.pendingApprovals]];
  const money=(v:any)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
  const agg=(title:string,rows:any[])=><div className="card" style={{marginBottom:12,overflowX:'auto'}}><h3 style={sectionTitle}>{title}</h3><table className="table"><thead><tr><th>Dimension</th><th>Bookings</th><th>Currency</th><th>Revenue</th><th>Cost</th><th>GP</th><th>Margin %</th><th>Unbilled</th></tr></thead><tbody>{(rows||[]).flatMap((r:any)=>(r.financials||[]).map((f:any,i:number)=><tr key={`${r.key}-${f.currency}`}><td>{i===0?<b>{r.label}</b>:''}</td><td>{i===0?r.bookingCount:''}</td><td>{f.currency}</td><td>{money(f.revenue)}</td><td>{money(f.cost)}</td><td>{money(f.gp)}</td><td>{money(f.marginPct)}%</td><td>{money(f.unbilledRevenue)}</td></tr>))}{!rows?.length&&<tr><td colSpan={8}>No data.</td></tr>}</tbody></table></div>;
  return <WorkspaceShell title="Enterprise Reporting & BI" subtitle="Executive KPIs, branch / customer / lane profitability, management exceptions and scheduled report definitions" active="/enterprise-reporting" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="grid" style={{marginBottom:12}}>{cards.map(([k,v])=><div className="card" key={String(k)}><div className="sub">{k}</div><div className="kpi">{v??0}</div></div>)}</div>
    <div className="card" style={{marginBottom:12,overflowX:'auto'}}><h3 style={sectionTitle}>Executive Financial Snapshot</h3><table className="table"><thead><tr><th>Currency</th><th>Revenue</th><th>Cost</th><th>GP</th><th>Margin %</th><th>Unbilled Revenue</th></tr></thead><tbody>{(data?.currencyTotals||[]).map((x:any)=><tr key={x.currency}><td><b>{x.currency}</b></td><td>{money(x.revenue)}</td><td>{money(x.cost)}</td><td>{money(x.gp)}</td><td>{money(x.marginPct)}%</td><td>{money(x.unbilledRevenue)}</td></tr>)}{!data?.currencyTotals?.length&&<tr><td colSpan={6}>No financial data.</td></tr>}</tbody></table><div className="sub" style={{marginTop:8}}>Currencies are reported separately; ANCLINE does not invent FX consolidation rates.</div></div>
    {agg('Branch Performance',data?.branch||[])}{agg('Customer Performance',data?.customer||[])}{agg('Lane / Trade Performance',data?.lane||[])}{agg('Monthly Trend',data?.month||[])}
    <div className="card" style={{marginBottom:12,overflowX:'auto'}}><h3 style={sectionTitle}>Management Exceptions</h3><table className="table"><thead><tr><th>Type</th><th>Booking</th><th>Customer</th><th>Detail</th></tr></thead><tbody>{(data?.exceptions?.negativeGp||[]).map((x:any)=><tr key={`gp-${x.bookingId}-${x.currency}`}><td>NEGATIVE GP</td><td>{x.bookingNo}</td><td>{x.customerName}</td><td>{x.currency} GP {money(x.gp)}</td></tr>)}{(data?.exceptions?.overdueEta||[]).map((x:any)=><tr key={`eta-${x.bookingId}`}><td>OVERDUE ETA</td><td>{x.bookingNo}</td><td>{x.customerName}</td><td>{x.origin} → {x.destination} · {x.eta?new Date(x.eta).toLocaleDateString():'-'}</td></tr>)}{(data?.exceptions?.unbilledRevenue||[]).map((x:any)=><tr key={`ub-${x.bookingId}-${x.currency}`}><td>UNBILLED REVENUE</td><td>{x.bookingNo}</td><td>{x.customerName}</td><td>{x.currency} {money(x.unbilledRevenue)}</td></tr>)}{!(data?.exceptions?.negativeGp?.length||data?.exceptions?.overdueEta?.length||data?.exceptions?.unbilledRevenue?.length)&&<tr><td colSpan={4}>No management exceptions detected.</td></tr>}</tbody></table></div>
    <div className="grid" style={{marginBottom:12}}><div className="card"><h3 style={sectionTitle}>Scheduled Report Definition</h3><div style={formGrid}><label><span style={labelStyle}>Name</span><input style={fieldStyle} value={report.name} onChange={e=>setReport({...report,name:e.target.value})}/></label><label><span style={labelStyle}>Report Type</span><select style={fieldStyle} value={report.reportType} onChange={e=>setReport({...report,reportType:e.target.value})}><option>EXECUTIVE_KPI</option><option>BRANCH_PERFORMANCE</option><option>CUSTOMER_PROFITABILITY</option><option>LANE_PROFITABILITY</option><option>MANAGEMENT_EXCEPTIONS</option></select></label><label><span style={labelStyle}>Frequency</span><select style={fieldStyle} value={report.frequency} onChange={e=>setReport({...report,frequency:e.target.value})}><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option></select></label><label><span style={labelStyle}>Recipients</span><input style={fieldStyle} placeholder="email1, email2" value={report.recipients} onChange={e=>setReport({...report,recipients:e.target.value})}/></label></div><div style={{textAlign:'right',marginTop:10}}><button className="btn" disabled={busy} onClick={saveReport}>Save Definition</button></div></div>
    <div className="card"><h3 style={sectionTitle}>Saved Report View</h3><div style={formGrid}><label><span style={labelStyle}>View Name</span><input style={fieldStyle} value={view.name} onChange={e=>setView({...view,name:e.target.value})}/></label><label><span style={labelStyle}>Dimension</span><select style={fieldStyle} value={view.dimension} onChange={e=>setView({...view,dimension:e.target.value})}><option>BRANCH</option><option>CUSTOMER</option><option>LANE</option><option>MONTH</option></select></label><label><span style={labelStyle}>Shared</span><select style={fieldStyle} value={view.shared?'YES':'NO'} onChange={e=>setView({...view,shared:e.target.value==='YES'})}><option>NO</option><option>YES</option></select></label></div><div style={{textAlign:'right',marginTop:10}}><button className="btn" disabled={busy} onClick={saveView}>Save View</button></div></div></div>
    <div className="card" style={{overflowX:'auto'}}><h3 style={sectionTitle}>Report Definitions & Manual Runs</h3><table className="table"><thead><tr><th>Name</th><th>Type</th><th>Frequency</th><th>Recipients</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data?.reportDefinitions||[]).map((r:any)=><tr key={r.reportId}><td><b>{r.name}</b></td><td>{r.reportType}</td><td>{r.frequency}</td><td>{(r.recipients||[]).join(', ')||'-'}</td><td>{r.active===false?'Inactive':'Active'}</td><td><button className="btn" disabled={busy||r.active===false} onClick={()=>run(r.reportId)}>Generate Snapshot</button></td></tr>)}{!data?.reportDefinitions?.length&&<tr><td colSpan={6}>No report definitions configured.</td></tr>}</tbody></table></div>
  </WorkspaceShell>;
}
