'use client';
import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,labelStyle,formGrid,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtDate,requireToken} from '../../lib/api';

export default function DataQualityPage(){
 const [token,setToken]=useState(''),[d,setD]=useState<any>({summary:{},rules:[],issues:[],bookings:[],remediations:[]}),[msg,setMsg]=useState(''),[busy,setBusy]=useState('');
 const [name,setName]=useState('Booking customer reference required'),[field,setField]=useState('customerReference'),[operator,setOperator]=useState('REQUIRED'),[value,setValue]=useState(''),[severity,setSeverity]=useState('ERROR'),[action,setAction]=useState('WARN'),[gate,setGate]=useState('ANY'),[branchId,setBranchId]=useState(''),[customerId,setCustomerId]=useState('');
 useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
 async function load(t=token){try{setD(await api('/data-quality/dashboard',t));}catch(e:any){setMsg(e.message||'Unable to load data quality');}}
 async function saveRule(){setBusy('rule');setMsg('');try{await api('/data-quality/rules',token,{method:'POST',body:JSON.stringify({name,objectType:'BOOKING',field,operator,value:value||null,severity,action,gate,branchId:branchId||null,customerId:customerId||null,active:true})});setMsg('Validation rule saved.');await load();}catch(e:any){setMsg(e.message||'Unable to save rule');}finally{setBusy('');}}
 async function scan(){setBusy('scan');setMsg('');try{const r=await api('/data-quality/scan',token,{method:'POST'});setMsg(`Scanned ${r.length||0} bookings.`);await load();}catch(e:any){setMsg(e.message||'Scan failed');}finally{setBusy('');}}
 async function remediate(i:any){setBusy(i.bookingId+i.code);setMsg('');try{await api('/data-quality/remediations',token,{method:'POST',body:JSON.stringify({bookingId:i.bookingId,bookingNo:i.bookingNo,issueCode:i.code,message:i.message,severity:i.severity})});setMsg('Remediation item created.');await load();}catch(e:any){setMsg(e.message||'Unable to create remediation');}finally{setBusy('');}}
 async function resolve(r:any){setBusy(r.remediationId);try{await api(`/data-quality/remediations/${r.remediationId}/RESOLVED`,token,{method:'POST',body:JSON.stringify({resolution:'Resolved from Data Quality workspace'})});await load();}catch(e:any){setMsg(e.message||'Unable to resolve item');}finally{setBusy('');}}
 const s=d.summary||{};
 return <WorkspaceShell title="Data Quality & Operational Validation" subtitle="Completeness · consistency · duplicates · configurable validation gates · remediation control" active="/data-quality" actions={<><button className="btn" disabled={!!busy} onClick={scan}>{busy==='scan'?'Scanning...':'Run Quality Scan'}</button><button className="btn" onClick={()=>load()}>Refresh</button></>}>
 {msg&&<div className="card" style={{marginBottom:12}}>{msg}</div>}
 <div className="grid" style={{marginBottom:12}}>{[['ACTIVE RULES',s.activeRules],['BOOKINGS SCANNED',s.bookingsScanned],['ISSUES',s.issues],['ERRORS',s.errors],['WARNINGS',s.warnings],['DUPLICATES',s.duplicates],['OPEN REMEDIATIONS',s.openRemediations]].map(([a,b]:any)=><div className="card" key={a}><div className="sub">{a}</div><div className="kpi">{b||0}</div></div>)}</div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Validation Rule Administration</h3><div style={formGrid}><label><span style={labelStyle}>Rule Name</span><input style={fieldStyle} value={name} onChange={e=>setName(e.target.value)}/></label><label><span style={labelStyle}>Booking Field</span><input style={fieldStyle} value={field} onChange={e=>setField(e.target.value)}/></label><label><span style={labelStyle}>Operator</span><select style={fieldStyle} value={operator} onChange={e=>setOperator(e.target.value)}><option>REQUIRED</option><option>EQUALS</option><option>NOT_EQUALS</option><option>GT</option><option>GTE</option><option>LT</option><option>LTE</option><option>CONTAINS</option><option>IN</option><option>REGEX</option></select></label><label><span style={labelStyle}>Value</span><input style={fieldStyle} value={value} onChange={e=>setValue(e.target.value)}/></label><label><span style={labelStyle}>Severity</span><select style={fieldStyle} value={severity} onChange={e=>setSeverity(e.target.value)}><option>ERROR</option><option>WARN</option><option>INFO</option></select></label><label><span style={labelStyle}>Action</span><select style={fieldStyle} value={action} onChange={e=>setAction(e.target.value)}><option>WARN</option><option>BLOCK</option></select></label><label><span style={labelStyle}>Gate</span><select style={fieldStyle} value={gate} onChange={e=>setGate(e.target.value)}><option>ANY</option><option>CONFIRMATION</option><option>OPERATIONAL</option><option>COMPLETION</option><option>FINANCIAL_CLOSE</option></select></label><label><span style={labelStyle}>Branch ID (optional)</span><input style={fieldStyle} value={branchId} onChange={e=>setBranchId(e.target.value)}/></label><label><span style={labelStyle}>Customer ID (optional)</span><input style={fieldStyle} value={customerId} onChange={e=>setCustomerId(e.target.value)}/></label></div><div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><button className="btn" disabled={!!busy} onClick={saveRule}>{busy==='rule'?'Saving...':'Save Validation Rule'}</button></div></div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Current Data Quality Issues</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Booking</th><th>Severity</th><th>Code</th><th>Field</th><th>Issue</th><th>Source</th><th></th></tr></thead><tbody>{(d.issues||[]).map((i:any,idx:number)=><tr key={`${i.bookingId}-${i.code}-${idx}`}><td>{i.bookingNo}</td><td>{i.severity}</td><td>{i.code}</td><td>{i.field||'-'}</td><td>{i.message}</td><td>{i.source}</td><td><button className="btn" disabled={!!busy} onClick={()=>remediate(i)}>Remediate</button></td></tr>)}</tbody></table></div></div>
 <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Configured Validation Rules</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Name</th><th>Field</th><th>Condition</th><th>Severity</th><th>Action</th><th>Gate</th><th>Scope</th></tr></thead><tbody>{(d.rules||[]).map((r:any)=><tr key={r.ruleId}><td>{r.name}</td><td>{r.field}</td><td>{r.operator} {r.value??''}</td><td>{r.severity}</td><td>{r.action}</td><td>{r.gate}</td><td>{r.branchId?`Branch ${r.branchId}`:r.customerId?`Customer ${r.customerId}`:'Global'}</td></tr>)}</tbody></table></div></div>
 <div className="card"><h3 style={sectionTitle}>Remediation Queue</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Created</th><th>Booking</th><th>Issue</th><th>Severity</th><th>Owner</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{(d.remediations||[]).map((r:any)=><tr key={r.remediationId}><td>{fmtDate(r.createdAt||r.updatedAt)}</td><td>{r.bookingNo||r.bookingId}</td><td>{r.issueCode}</td><td>{r.severity}</td><td>{r.ownerId||'-'}</td><td>{fmtDate(r.dueAt)}</td><td>{r.status}</td><td>{!['RESOLVED','CLOSED'].includes(r.status)&&<button className="btn" disabled={!!busy} onClick={()=>resolve(r)}>Resolve</button>}</td></tr>)}</tbody></table></div></div>
 </WorkspaceShell>;
}
