import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
@Injectable()
export class AutomationService {
  constructor(private p:PrismaService, private audit:AuditService){}
  private assertInternal(u:any){ if(!['GLOBAL_ADMIN','CONTROL_TOWER','BRANCH_OPS','FINANCE'].includes(u?.role)) throw new ForbiddenException('Internal access required'); }
  private userId(u:any){ return u?.sub||u?.userId||'unknown'; }
  async search(q:string,u:any){ this.assertInternal(u); const term=q.trim(); if(!term) return {query:'',bookings:[],organizations:[],rates:[],documents:[]}; const contains={contains:term,mode:'insensitive' as const}; const [bookings,organizations,rates,documents]=await Promise.all([
    this.p.booking.findMany({where:{OR:[{bookingNo:contains},{origin:contains},{destination:contains},{carrier:contains}]},take:20,include:{customer:true}}),
    this.p.organization.findMany({where:{OR:[{code:contains},{name:contains},{countryCode:contains}]},take:20}),
    this.p.rateQuote.findMany({where:{OR:[{quoteNo:contains},{trade:contains},{equipment:contains}]},take:20}),
    this.p.document.findMany({where:{OR:[{documentNo:contains},{type:contains},{status:contains}]},take:20})
  ]); return {query:term,bookings,organizations,rates,documents,total:bookings.length+organizations.length+rates.length+documents.length}; }
  async notifications(u:any){ return this.p.notification.findMany({where:{userId:this.userId(u),status:{not:'ARCHIVED'}},orderBy:{createdAt:'desc'},take:100}); }
  async markRead(id:string,u:any){ const n=await this.p.notification.findUnique({where:{id}}); if(!n) throw new NotFoundException('Notification not found'); if(n.userId!==this.userId(u) && u?.role!=='GLOBAL_ADMIN') throw new ForbiddenException(); return this.p.notification.update({where:{id},data:{status:'READ',readAt:new Date()}}); }
  async integrations(u:any){ this.assertInternal(u); return this.p.integrationEvent.findMany({orderBy:{createdAt:'desc'},take:200}); }
  async createIntegrationEvent(b:any,u:any){ this.assertInternal(u); const r=await this.p.integrationEvent.create({data:{sourceSystem:b.sourceSystem||'MANUAL',eventType:b.eventType||'GENERIC',externalId:b.externalId,objectType:b.objectType,objectId:b.objectId,payload:b.payload||{},status:'RECEIVED'}}); await this.audit.record({actorId:this.userId(u),action:'INTEGRATION_EVENT_CREATED',objectType:'IntegrationEvent',objectId:r.id,meta:{sourceSystem:r.sourceSystem,eventType:r.eventType}}); return r; }
  async retryIntegrationEvent(id:string,u:any){ this.assertInternal(u); const e=await this.p.integrationEvent.findUnique({where:{id}}); if(!e) throw new NotFoundException('Integration event not found'); const r=await this.p.integrationEvent.update({where:{id},data:{status:'RETRY_PENDING',attemptCount:{increment:1},lastAttemptAt:new Date(),errorMessage:null}}); await this.audit.record({actorId:this.userId(u),action:'INTEGRATION_EVENT_RETRY',objectType:'IntegrationEvent',objectId:id}); return r; }
  private defaults(){ return [
    ['OPS_COMPLETE','Operations completed'],['DOCUMENTS_COMPLETE','Documents and BL released'],['COSTS_CAPTURED','All costs captured/accrued'],['REVENUE_POSTED','Revenue posted'],['EXCEPTIONS_CLOSED','Operational exceptions closed'],['TASKS_CLOSED','Outstanding tasks closed'],['AGENT_SETTLED','Agent settlement completed'],['DND_RESOLVED','D&D exposure resolved']
  ] as const; }
  async closeout(bookingId:string,u:any){ this.assertInternal(u); const booking=await this.p.booking.findUnique({where:{id:bookingId}}); if(!booking) throw new NotFoundException('Booking not found'); const existing=await this.p.jobCloseoutChecklist.findMany({where:{bookingId}}); const known=new Set(existing.map(x=>x.itemCode)); const missing=this.defaults().filter(([code])=>!known.has(code)); if(missing.length) await this.p.jobCloseoutChecklist.createMany({data:missing.map(([itemCode,itemLabel])=>({bookingId,itemCode,itemLabel,mandatory:true}))}); const items=await this.p.jobCloseoutChecklist.findMany({where:{bookingId},orderBy:{createdAt:'asc'}}); const [openTasks,openExceptions,pendingApprovals,financeOpen]=await Promise.all([this.p.task.count({where:{bookingId,status:{not:'COMPLETED'}}}),this.p.operationalException.count({where:{bookingId,status:{not:'RESOLVED'}}}),this.p.approval.count({where:{bookingId,status:'PENDING'}}),this.p.financeLine.count({where:{bookingId,status:{notIn:['FINAL','CLEARED','CANCELLED']}}})]); const mandatory=items.filter(x=>x.mandatory); return {booking,items,checks:{openTasks,openExceptions,pendingApprovals,financeOpen},ready:mandatory.length>0&&mandatory.every(x=>x.completed)&&openTasks===0&&openExceptions===0&&pendingApprovals===0&&financeOpen===0}; }
  async setCloseoutItem(bookingId:string,itemCode:string,b:any,u:any){ this.assertInternal(u); const r=await this.p.jobCloseoutChecklist.upsert({where:{bookingId_itemCode:{bookingId,itemCode}},update:{completed:!!b.completed,completedBy:b.completed?this.userId(u):null,completedAt:b.completed?new Date():null,note:b.note},create:{bookingId,itemCode,itemLabel:b.itemLabel||itemCode,mandatory:b.mandatory!==false,completed:!!b.completed,completedBy:b.completed?this.userId(u):null,completedAt:b.completed?new Date():null,note:b.note}}); await this.audit.record({actorId:this.userId(u),action:'JOB_CLOSEOUT_ITEM_UPDATED',objectType:'JobCloseoutChecklist',objectId:r.id,meta:{bookingId,itemCode,completed:r.completed}}); return r; }
}
