import { BadRequestException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';
@Injectable()
export class CommercialService {
  constructor(private p:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private internal(u:ScopeUser){this.scope.assertInternal(u)}
  async dashboard(u:ScopeUser){this.internal(u); const [contracts,settlements,dnd,collections,ai]=await Promise.all([this.p.serviceContract.count(),this.p.agentSettlement.count(),this.p.demurrageDetentionCase.count({where:{status:{not:'SETTLED'}}}),this.p.collectionCase.count({where:{status:{not:'CLOSED'}}}),this.p.aIReview.count({where:{status:'DRAFT'}})]); const overdue=await this.p.collectionCase.aggregate({_sum:{outstandingAmount:true},where:{status:{not:'CLOSED'},dueAt:{lt:new Date()}}}); return {contracts,settlements,openDnD:dnd,openCollections:collections,aiReviewsPending:ai,overdueReceivables:Number(overdue._sum.outstandingAmount||0)} }
  async contracts(u:ScopeUser){this.internal(u); return this.p.serviceContract.findMany({include:{rates:true},orderBy:{validTo:'asc'}})}
  async createContract(b:any,u:ScopeUser){this.internal(u); const row=await this.p.serviceContract.create({data:{...b,validFrom:new Date(b.validFrom),validTo:new Date(b.validTo)}}); await this.audit.log({actorId:u.sub,action:'CONTRACT_CREATE',objectType:'ServiceContract',objectId:row.id,detail:{contractNo:row.contractNo}}); return row}
  async addContractRate(id:string,b:any,u:ScopeUser){this.internal(u); const row=await this.p.contractRateLane.create({data:{...b,contractId:id}}); await this.audit.log({actorId:u.sub,action:'CONTRACT_RATE_ADD',objectType:'ContractRateLane',objectId:row.id,detail:{contractId:id}}); return row}
  async settlements(u:ScopeUser){this.scope.assertFinanceAccess(u); return this.p.agentSettlement.findMany({include:{lines:true},orderBy:{createdAt:'desc'}})}
  async createSettlement(b:any,u:ScopeUser){this.scope.assertFinanceAccess(u); const lines=Array.isArray(b.lines)?b.lines:[]; const dueTo=lines.filter((x:any)=>x.type==='DUE_TO').reduce((s:number,x:any)=>s+Number(x.amount||0),0); const dueFrom=lines.filter((x:any)=>x.type==='DUE_FROM').reduce((s:number,x:any)=>s+Number(x.amount||0),0); const profitShare=lines.filter((x:any)=>x.type==='PROFIT_SHARE').reduce((s:number,x:any)=>s+Number(x.amount||0),0); const deposit=lines.filter((x:any)=>x.type==='DEPOSIT').reduce((s:number,x:any)=>s+Number(x.amount||0),0); return this.p.agentSettlement.create({data:{settlementNo:b.settlementNo,agentId:b.agentId,periodFrom:new Date(b.periodFrom),periodTo:new Date(b.periodTo),currency:b.currency||'USD',dueToAmount:dueTo,dueFromAmount:dueFrom,profitShare,depositMovement:deposit,netAmount:dueFrom-dueTo+profitShare+deposit,status:'APPROVAL_PENDING',requesterId:u.sub,lines:{create:lines.map((x:any)=>({bookingId:x.bookingId,reference:x.reference,type:x.type,amount:x.amount,currency:x.currency||b.currency||'USD',note:x.note}))}},include:{lines:true}})}
  async approveSettlement(id:string,u:ScopeUser){this.scope.assertFinanceAccess(u); const s=await this.p.agentSettlement.findUnique({where:{id}}); if(!s) throw new BadRequestException('Settlement not found'); if(s.requesterId===u.sub) throw new BadRequestException('Requester cannot self-approve settlement'); return this.p.agentSettlement.update({where:{id},data:{status:'APPROVED',approverId:u.sub,approvedAt:new Date()}})}
  async dnd(u:ScopeUser){this.internal(u); return this.p.demurrageDetentionCase.findMany({orderBy:{updatedAt:'desc'}})}
  async createDnd(b:any,u:ScopeUser){this.internal(u); await this.scope.assertBookingAccess(u,b.bookingId); return this.p.demurrageDetentionCase.create({data:{...b,freeTimeEndsAt:b.freeTimeEndsAt?new Date(b.freeTimeEndsAt):undefined,chargeFrom:b.chargeFrom?new Date(b.chargeFrom):undefined,chargeTo:b.chargeTo?new Date(b.chargeTo):undefined}})}
  async waiver(id:string,b:any,u:ScopeUser){this.internal(u); return this.p.demurrageDetentionCase.update({where:{id},data:{waiverAmount:b.waiverAmount,waiverReason:b.waiverReason,status:'WAIVER_REQUESTED'}})}
  async collections(u:ScopeUser){this.scope.assertFinanceAccess(u); return this.p.collectionCase.findMany({orderBy:[{creditHold:'desc'},{dueAt:'asc'}]})}
  async createCollection(b:any,u:ScopeUser){this.scope.assertFinanceAccess(u); return this.p.collectionCase.create({data:{...b,dueAt:b.dueAt?new Date(b.dueAt):undefined,lastActionAt:new Date()}})}
  async aiReviews(u:ScopeUser){this.internal(u); return this.p.aIReview.findMany({orderBy:{createdAt:'desc'}})}
  async createAiReview(b:any,u:ScopeUser){this.internal(u); return this.p.aIReview.create({data:{objectType:b.objectType,objectId:b.objectId,reviewType:b.reviewType,confidence:b.confidence,findings:b.findings||{},recommendedActions:b.recommendedActions||{},status:'DRAFT'}})}
}
