import { BadRequestException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';
@Injectable()
export class LandsideService{
 constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
 async dashboard(user:ScopeUser){this.scope.assertInternal(user);const [transport,customs,warehouse,milestones]=await Promise.all([
  this.prisma.transportOrder.findMany({include:{booking:true},orderBy:{createdAt:'desc'},take:100}),
  this.prisma.customsDeclaration.findMany({include:{booking:true},orderBy:{createdAt:'desc'},take:100}),
  this.prisma.warehouseJob.findMany({include:{booking:true},orderBy:{createdAt:'desc'},take:100}),
  this.prisma.trackingMilestone.findMany({include:{booking:true},orderBy:{createdAt:'desc'},take:150})
 ]);return {transport,customs,warehouse,milestones}}
 async booking(bookingId:string,user:ScopeUser){await this.scope.assertBookingAccess(user,bookingId);return this.prisma.booking.findUnique({where:{id:bookingId},include:{transportOrders:{include:{milestones:true}},customsDeclarations:true,warehouseJobs:true,trackingMilestones:true}})}
 async createTransport(bookingId:string,b:any,user:ScopeUser){await this.scope.assertBookingAccess(user,bookingId);this.scope.assertInternal(user);const row=await this.prisma.transportOrder.create({data:{...b,bookingId,pickupAt:b.pickupAt?new Date(b.pickupAt):null,deliveryAt:b.deliveryAt?new Date(b.deliveryAt):null}});await this.audit.log({actorId:user.sub,action:'TRANSPORT_ORDER_CREATE',objectType:'TransportOrder',objectId:row.id,bookingId,detail:{orderNo:row.orderNo}});return row}
 async transportStatus(id:string,b:any,user:ScopeUser){this.scope.assertInternal(user);const row=await this.prisma.transportOrder.findUnique({where:{id}});if(!row)throw new BadRequestException('Transport order not found');await this.scope.assertBookingAccess(user,row.bookingId);const out=await this.prisma.transportOrder.update({where:{id},data:{status:b.status,podReference:b.podReference??undefined,exceptionNote:b.exceptionNote??undefined}});await this.audit.log({actorId:user.sub,action:'TRANSPORT_STATUS',objectType:'TransportOrder',objectId:id,bookingId:row.bookingId,detail:{status:b.status}});return out}
 async createCustoms(bookingId:string,b:any,user:ScopeUser){await this.scope.assertBookingAccess(user,bookingId);this.scope.assertInternal(user);const row=await this.prisma.customsDeclaration.create({data:{...b,bookingId,submittedAt:b.submittedAt?new Date(b.submittedAt):null,clearedAt:b.clearedAt?new Date(b.clearedAt):null}});await this.audit.log({actorId:user.sub,action:'CUSTOMS_CREATE',objectType:'CustomsDeclaration',objectId:row.id,bookingId,detail:{declarationNo:row.declarationNo}});return row}
 async customsStatus(id:string,b:any,user:ScopeUser){this.scope.assertInternal(user);const row=await this.prisma.customsDeclaration.findUnique({where:{id}});if(!row)throw new BadRequestException('Customs declaration not found');await this.scope.assertBookingAccess(user,row.bookingId);const out=await this.prisma.customsDeclaration.update({where:{id},data:{status:b.status,mrn:b.mrn??undefined,holdReason:b.holdReason??undefined,submittedAt:b.submittedAt?new Date(b.submittedAt):undefined,clearedAt:b.clearedAt?new Date(b.clearedAt):undefined}});await this.audit.log({actorId:user.sub,action:'CUSTOMS_STATUS',objectType:'CustomsDeclaration',objectId:id,bookingId:row.bookingId,detail:{status:b.status}});return out}
 async createWarehouse(bookingId:string,b:any,user:ScopeUser){await this.scope.assertBookingAccess(user,bookingId);this.scope.assertInternal(user);const row=await this.prisma.warehouseJob.create({data:{...b,bookingId,plannedAt:b.plannedAt?new Date(b.plannedAt):null,completedAt:b.completedAt?new Date(b.completedAt):null}});await this.audit.log({actorId:user.sub,action:'WAREHOUSE_JOB_CREATE',objectType:'WarehouseJob',objectId:row.id,bookingId,detail:{jobNo:row.jobNo}});return row}
 async warehouseStatus(id:string,b:any,user:ScopeUser){this.scope.assertInternal(user);const row=await this.prisma.warehouseJob.findUnique({where:{id}});if(!row)throw new BadRequestException('Warehouse job not found');await this.scope.assertBookingAccess(user,row.bookingId);const out=await this.prisma.warehouseJob.update({where:{id},data:{status:b.status,releaseReference:b.releaseReference??undefined,completedAt:b.completedAt?new Date(b.completedAt):undefined}});await this.audit.log({actorId:user.sub,action:'WAREHOUSE_STATUS',objectType:'WarehouseJob',objectId:id,bookingId:row.bookingId,detail:{status:b.status}});return out}
 async milestone(bookingId:string,b:any,user:ScopeUser){await this.scope.assertBookingAccess(user,bookingId);this.scope.assertInternal(user);const row=await this.prisma.trackingMilestone.create({data:{...b,bookingId,plannedAt:b.plannedAt?new Date(b.plannedAt):null,actualAt:b.actualAt?new Date(b.actualAt):null}});await this.audit.log({actorId:user.sub,action:'TRACKING_MILESTONE_CREATE',objectType:'TrackingMilestone',objectId:row.id,bookingId,detail:{code:row.code}});return row}
}
