import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SOURCE='ANCLINE_SALES_CRM';
@Injectable()
export class SalesCrmService{
 constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
 private get db():any{return this.prisma as any;}
 private internal(u:ScopeUser){this.scope.assertInternal(u);}
 private p(e:any){return (e?.payload||{}) as any;}
 private async events(type:string):Promise<any[]>{return this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:type},orderBy:{createdAt:'asc'}});}
 private latest(rows:any[],createType:string,patchType:string){const g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const c=ev.find((x:any)=>x.eventType===createType);if(!c)continue;let row={id,...this.p(c),createdAt:c.createdAt};for(const x of ev.filter((x:any)=>x.eventType===patchType))row={...row,...this.p(x),updatedAt:x.createdAt};out.push(row);}return out;}
 async customers(u:ScopeUser){this.internal(u);return this.db.organization.findMany({where:{roles:{has:'CUSTOMER'},active:true},select:{id:true,code:true,name:true,countryCode:true},orderBy:{name:'asc'}});}
 async opportunities(u:ScopeUser){this.internal(u);return this.latest(await this.events('Opportunity'),'OPPORTUNITY_CREATED','OPPORTUNITY_UPDATED').sort((a:any,b:any)=>new Date(b.updatedAt||b.createdAt).getTime()-new Date(a.updatedAt||a.createdAt).getTime());}
 async createOpportunity(b:any,u:ScopeUser){this.internal(u);if(!b?.customerId||!b?.name)throw new BadRequestException('Customer and opportunity name are required');const value=Number(b?.value||0),probability=Math.max(0,Math.min(100,Number(b?.probability??20)));if(!Number.isFinite(value))throw new BadRequestException('Invalid opportunity value');const id=`OPP-${Date.now()}`;const payload={opportunityId:id,name:String(b.name),customerId:String(b.customerId),owner:String(b.owner||u.email||u.sub),stage:String(b.stage||'QUALIFY').toUpperCase(),probability,value,currency:String(b.currency||'USD').toUpperCase(),origin:b.origin?String(b.origin).toUpperCase():null,destination:b.destination?String(b.destination).toUpperCase():null,equipment:b.equipment?String(b.equipment).toUpperCase():null,expectedClose:b.expectedClose?new Date(b.expectedClose).toISOString():null,source:b.source?String(b.source):'DIRECT',notes:b.notes?String(b.notes):null,status:'OPEN',createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'OPPORTUNITY_CREATED',externalId:id,objectType:'Opportunity',objectId:id,status:'OPEN',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'CRM_OPPORTUNITY_CREATE',objectType:'Opportunity',objectId:id,detail:{customerId:payload.customerId,value,currency:payload.currency}});return payload;}
 async updateOpportunity(id:string,b:any,u:ScopeUser){this.internal(u);const row=(await this.opportunities(u)).find((x:any)=>x.opportunityId===id||x.id===id);if(!row)throw new NotFoundException('Opportunity not found');const allowed=['name','owner','stage','probability','value','currency','origin','destination','equipment','expectedClose','source','notes','status','lossReason','competitor','wonQuoteId'];const payload:any={opportunityId:id,updatedBy:u.sub};for(const k of allowed)if(Object.prototype.hasOwnProperty.call(b,k))payload[k]=b[k];if(payload.probability!=null)payload.probability=Math.max(0,Math.min(100,Number(payload.probability)));if(payload.value!=null)payload.value=Number(payload.value);if(payload.stage)payload.stage=String(payload.stage).toUpperCase();if(payload.status)payload.status=String(payload.status).toUpperCase();await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'OPPORTUNITY_UPDATED',externalId:id,objectType:'Opportunity',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {...row,...payload};}
 async tenders(u:ScopeUser){this.internal(u);return this.latest(await this.events('Tender'),'TENDER_CREATED','TENDER_UPDATED').sort((a:any,b:any)=>new Date(b.updatedAt||b.createdAt).getTime()-new Date(a.updatedAt||a.createdAt).getTime());}
 async createTender(b:any,u:ScopeUser){this.internal(u);if(!b?.customerId||!b?.name)throw new BadRequestException('Customer and tender name are required');const id=`RFQ-${Date.now()}`,deadline=b.deadline?new Date(b.deadline):null;if(deadline&&Number.isNaN(deadline.getTime()))throw new BadRequestException('Invalid deadline');const payload={tenderId:id,name:String(b.name),customerId:String(b.customerId),opportunityId:b.opportunityId?String(b.opportunityId):null,trade:b.trade?String(b.trade).toUpperCase():null,equipment:b.equipment?String(b.equipment).toUpperCase():null,estimatedVolume:Number(b.estimatedVolume||0),volumeUnit:String(b.volumeUnit||'TEU'),deadline:deadline?.toISOString()||null,status:String(b.status||'OPEN').toUpperCase(),owner:String(b.owner||u.email||u.sub),notes:b.notes?String(b.notes):null,createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'TENDER_CREATED',externalId:id,objectType:'Tender',objectId:id,status:'OPEN',payload,completedAt:new Date()}});return payload;}
 async updateTender(id:string,b:any,u:ScopeUser){this.internal(u);const row=(await this.tenders(u)).find((x:any)=>x.tenderId===id||x.id===id);if(!row)throw new NotFoundException('Tender not found');const payload={tenderId:id,...b,updatedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'TENDER_UPDATED',externalId:id,objectType:'Tender',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {...row,...payload};}
 private quoteRows(events:any[]){const g=new Map<string,any[]>();for(const e of events){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const c=ev.find((x:any)=>x.eventType==='QUOTE_VERSION_CREATED');if(!c)continue;const a=ev.find((x:any)=>x.eventType==='QUOTE_VERSION_APPROVED'),m=ev.find((x:any)=>x.eventType==='QUOTE_MATERIALIZED');out.push({quoteVersionId:id,...this.p(c),status:a?'APPROVED':'DRAFT',rateQuoteId:m?this.p(m).rateQuoteId||null:null,createdAt:c.createdAt});}return out.sort((a:any,b:any)=>b.version-a.version);}
 async quoteVersions(opportunityId:string,u:ScopeUser){this.internal(u);return this.quoteRows(await this.events('QuoteVersion')).filter((x:any)=>String(x.opportunityId)===opportunityId);}
 async createQuoteVersion(opportunityId:string,b:any,u:ScopeUser){this.internal(u);const opp=(await this.opportunities(u)).find((x:any)=>x.opportunityId===opportunityId||x.id===opportunityId);if(!opp)throw new NotFoundException('Opportunity not found');const existing=await this.quoteVersions(opportunityId,u),version=(existing[0]?.version||0)+1,buy=Number(b?.buyRate||0),sell=Number(b?.sellRate||0);if(!Number.isFinite(buy)||!Number.isFinite(sell)||buy<0||sell<0)throw new BadRequestException('Invalid buy/sell rate');const validTo=new Date(b?.validTo);if(Number.isNaN(validTo.getTime()))throw new BadRequestException('Valid-to date is required');const id=`QV-${Date.now()}`,payload={quoteVersionId:id,opportunityId,version,customerId:opp.customerId,trade:String(b?.trade||`${opp.origin||''}->${opp.destination||''}`).toUpperCase(),equipment:String(b?.equipment||opp.equipment||'40HC').toUpperCase(),buyRate:buy,sellRate:sell,currency:String(b?.currency||opp.currency||'USD').toUpperCase(),validFrom:new Date(b?.validFrom||new Date()).toISOString(),validTo:validTo.toISOString(),grossProfit:sell-buy,marginPct:sell?((sell-buy)/sell)*100:0,notes:b?.notes?String(b.notes):null,createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'QUOTE_VERSION_CREATED',externalId:id,objectType:'QuoteVersion',objectId:id,status:'DRAFT',payload,completedAt:new Date()}});return payload;}
 async approveQuoteVersion(id:string,u:ScopeUser){this.internal(u);const row=this.quoteRows(await this.events('QuoteVersion')).find((x:any)=>x.quoteVersionId===id);if(!row)throw new NotFoundException('Quote version not found');if(row.status==='APPROVED')return row;await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'QUOTE_VERSION_APPROVED',externalId:id,objectType:'QuoteVersion',objectId:id,status:'COMPLETED',payload:{quoteVersionId:id,approvedBy:u.sub},completedAt:new Date()}});return {...row,status:'APPROVED'};}
 async materializeQuote(id:string,u:ScopeUser){this.internal(u);const row=this.quoteRows(await this.events('QuoteVersion')).find((x:any)=>x.quoteVersionId===id);if(!row)throw new NotFoundException('Quote version not found');if(row.rateQuoteId)return {rateQuoteId:row.rateQuoteId,reused:true};if(row.status!=='APPROVED')throw new BadRequestException('Approve quote version before publishing');const quote=await this.db.rateQuote.create({data:{quoteNo:`Q-${Date.now().toString().slice(-8)}`,customerId:row.customerId,trade:row.trade,equipment:row.equipment,buyRate:row.buyRate,sellRate:row.sellRate,currency:row.currency,validFrom:new Date(row.validFrom),validTo:new Date(row.validTo),status:'Rate Approved',source:'SALES_CRM'}});await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'QUOTE_MATERIALIZED',externalId:id,objectType:'QuoteVersion',objectId:id,status:'COMPLETED',payload:{quoteVersionId:id,rateQuoteId:quote.id,quoteNo:quote.quoteNo,publishedBy:u.sub},completedAt:new Date()}});await this.updateOpportunity(row.opportunityId,{wonQuoteId:quote.id},u);return {rateQuoteId:quote.id,quoteNo:quote.quoteNo};}
 async closeOpportunity(id:string,result:string,b:any,u:ScopeUser){this.internal(u);const r=String(result).toUpperCase();if(!['WON','LOST'].includes(r))throw new BadRequestException('Result must be WON or LOST');return this.updateOpportunity(id,{status:r,stage:r,probability:r==='WON'?100:0,lossReason:r==='LOST'?String(b?.lossReason||'Unspecified'):null,competitor:r==='LOST'&&b?.competitor?String(b.competitor):null},u);}
 async dashboard(u:ScopeUser){this.internal(u);const [opps,tenders]=await Promise.all([this.opportunities(u),this.tenders(u)]),open=opps.filter((x:any)=>!['WON','LOST'].includes(String(x.status))),won=opps.filter((x:any)=>x.status==='WON'),lost=opps.filter((x:any)=>x.status==='LOST');const byCurrency=[...new Set<string>(open.map((x:any)=>String(x.currency||'USD'))) ].map(currency=>{const rows=open.filter((x:any)=>String(x.currency||'USD')===currency);return {currency,grossPipeline:rows.reduce((s:number,x:any)=>s+Number(x.value||0),0),weightedPipeline:rows.reduce((s:number,x:any)=>s+Number(x.value||0)*Number(x.probability||0)/100,0)};});const winRate=won.length+lost.length?won.length/(won.length+lost.length)*100:0;const lossReasons=Object.entries(lost.reduce((m:any,x:any)=>{const k=x.lossReason||'Unspecified';m[k]=(m[k]||0)+1;return m;},{})).map(([reason,count])=>({reason,count}));return {opportunities:opps,tenders,summary:{openOpportunities:open.length,won:won.length,lost:lost.length,winRate,openTenders:tenders.filter((x:any)=>x.status==='OPEN').length},pipelineByCurrency:byCurrency,lossReasons};}
}
