'use client';

import {useEffect,useMemo,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtDate,requireToken} from '../../lib/api';

type Branch={id:string;code:string;name:string;countryCode:string;active:boolean};
type User={id:string;email:string;displayName:string;role:string;branchId?:string|null;agentId?:string|null;customerId?:string|null;active:boolean};
type Integration={id:string;sourceSystem:string;eventType:string;externalId?:string;objectType:string;objectId:string;status:string;attemptCount:number;createdAt:string};

export default function AdministrationPage(){
  const [token,setToken]=useState('');const [branches,setBranches]=useState<Branch[]>([]);const [users,setUsers]=useState<User[]>([]);const [events,setEvents]=useState<Integration[]>([]);const [message,setMessage]=useState('');const [tab,setTab]=useState<'BRANCHES'|'USERS'|'INTEGRATIONS'>('BRANCHES');
  const [branch,setBranch]=useState({code:'',name:'',countryCode:''});const [user,setUser]=useState({email:'',displayName:'',role:'BRANCH_OPS',branchId:'',agentId:'',customerId:''});
  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
  async function load(t=token){try{const [b,u,i]=await Promise.all([api('/operations/branches',t),api('/operations/users',t).catch(()=>[]),api('/operations/integrations',t)]);setBranches(Array.isArray(b)?b:[]);setUsers(Array.isArray(u)?u:[]);setEvents(Array.isArray(i)?i:[]);}catch(e:any){setMessage(e.message||'Unable to load administration data');}}
  async function createBranch(){try{await api('/operations/branches',token,{method:'POST',body:JSON.stringify(branch)});setBranch({code:'',name:'',countryCode:''});setMessage('Branch created.');await load();}catch(e:any){setMessage(e.message||'Could not create branch');}}
  async function createUser(){try{await api('/operations/users',token,{method:'POST',body:JSON.stringify({...user,branchId:user.branchId||null,agentId:user.agentId||null,customerId:user.customerId||null})});setUser({email:'',displayName:'',role:'BRANCH_OPS',branchId:'',agentId:'',customerId:''});setMessage('User account created.');await load();}catch(e:any){setMessage(e.message||'Could not create user');}}
  async function toggleUser(id:string){try{await api(`/operations/users/${id}/toggle`,token,{method:'POST'});await load();}catch(e:any){setMessage(e.message||'Could not update user');}}
  const activeUsers=useMemo(()=>users.filter(x=>x.active).length,[users]);
  const btn=(key:typeof tab,label:string)=><button className="btn" style={{opacity:tab===key?1:.68}} onClick={()=>setTab(key)}>{label}</button>;
  return <WorkspaceShell title="Administration" subtitle="Branches, user accounts and integration event control" active="/administration" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="grid" style={{marginBottom:12}}><div className="card"><div className="sub">BRANCHES</div><div className="kpi">{branches.length}</div></div><div className="card"><div className="sub">USERS</div><div className="kpi">{users.length}</div></div><div className="card"><div className="sub">ACTIVE USERS</div><div className="kpi">{activeUsers}</div></div><div className="card"><div className="sub">INTEGRATION EVENTS</div><div className="kpi">{events.length}</div></div></div>
    <div style={{display:'flex',gap:7,flexWrap:'wrap',marginBottom:12}}>{btn('BRANCHES','Branches')}{btn('USERS','Users & Roles')}{btn('INTEGRATIONS','Integration Events')}</div>
    {tab==='BRANCHES'&&<><div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>New Branch</h3><div style={formGrid}><label><span style={labelStyle}>Branch Code *</span><input style={fieldStyle} value={branch.code} onChange={e=>setBranch({...branch,code:e.target.value})}/></label><label><span style={labelStyle}>Branch Name *</span><input style={fieldStyle} value={branch.name} onChange={e=>setBranch({...branch,name:e.target.value})}/></label><label><span style={labelStyle}>Country Code *</span><input maxLength={2} style={fieldStyle} value={branch.countryCode} onChange={e=>setBranch({...branch,countryCode:e.target.value})}/></label></div><div style={{textAlign:'right',marginTop:12}}><button className="btn" onClick={createBranch}>Create Branch</button></div></div><div className="card"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Country</th><th>Status</th></tr></thead><tbody>{branches.map(b=><tr key={b.id}><td><b>{b.code}</b></td><td>{b.name}</td><td>{b.countryCode}</td><td><span className="status">{b.active?'Active':'Inactive'}</span></td></tr>)}{!branches.length&&<tr><td colSpan={4}>No branches configured.</td></tr>}</tbody></table></div></>}
    {tab==='USERS'&&<><div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>New User Account</h3><div style={formGrid}><label><span style={labelStyle}>Email *</span><input style={fieldStyle} value={user.email} onChange={e=>setUser({...user,email:e.target.value})}/></label><label><span style={labelStyle}>Display Name *</span><input style={fieldStyle} value={user.displayName} onChange={e=>setUser({...user,displayName:e.target.value})}/></label><label><span style={labelStyle}>Role *</span><select style={fieldStyle} value={user.role} onChange={e=>setUser({...user,role:e.target.value})}>{['GLOBAL_ADMIN','CONTROL_TOWER','BRANCH_OPS','FINANCE','AGENT','CUSTOMER'].map(x=><option key={x}>{x}</option>)}</select></label><label><span style={labelStyle}>Branch</span><select style={fieldStyle} value={user.branchId} onChange={e=>setUser({...user,branchId:e.target.value})}><option value="">Not scoped</option>{branches.map(b=><option key={b.id} value={b.id}>{b.code} - {b.name}</option>)}</select></label><label><span style={labelStyle}>Agent Organization ID</span><input style={fieldStyle} value={user.agentId} onChange={e=>setUser({...user,agentId:e.target.value})}/></label><label><span style={labelStyle}>Customer Organization ID</span><input style={fieldStyle} value={user.customerId} onChange={e=>setUser({...user,customerId:e.target.value})}/></label></div><div style={{textAlign:'right',marginTop:12}}><button className="btn" onClick={createUser}>Create User</button></div></div><div className="card" style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Scope</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.displayName}</b></td><td>{u.email}</td><td>{u.role}</td><td>{u.branchId||u.agentId||u.customerId||'Global / none'}</td><td><span className="status">{u.active?'Active':'Inactive'}</span></td><td><button className="btn" onClick={()=>toggleUser(u.id)}>{u.active?'Deactivate':'Activate'}</button></td></tr>)}{!users.length&&<tr><td colSpan={6}>No user accounts configured or admin permission is required.</td></tr>}</tbody></table></div></>}
    {tab==='INTEGRATIONS'&&<div className="card" style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Created</th><th>Source</th><th>Event</th><th>Object</th><th>External ID</th><th>Attempts</th><th>Status</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{fmtDate(e.createdAt)}</td><td>{e.sourceSystem}</td><td><b>{e.eventType}</b></td><td>{e.objectType} · {e.objectId}</td><td>{e.externalId||'-'}</td><td>{e.attemptCount}</td><td><span className="status">{e.status}</span></td></tr>)}{!events.length&&<tr><td colSpan={7}>No integration events recorded.</td></tr>}</tbody></table></div>}
  </WorkspaceShell>;
}
