import { BadRequestException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SOURCE='ANCLINE_WORKFORCE';
@Injectable()
export class WorkforceService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private async events(){return this.prisma.integrationEvent.findMany({where:{sourceSystem:SOURCE},orderBy:{createdAt:'asc'}});}
  private latest(rows:any[],objectType:string){const m=new Map<string,any>();for(const e of rows.filter((x:any)=>x.objectType===objectType))m.set(e.objectId,{...(e.payload as any),eventType:e.eventType,updatedAt:e.createdAt});return [...m.values()];}
  private id(prefix:string){return `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;}
  private async put(objectType:string,eventType:string,objectId:string,payload:any,user:ScopeUser){this.scope.assertInternal(user);const row=await this.prisma.integrationEvent.create({data:{sourceSystem:SOURCE,objectType,objectId,eventType,status:'COMPLETED',completedAt:new Date(),payload:{...payload,updatedBy:user.sub}}});await this.audit.log({actorId:user.sub,action:eventType,objectType,objectId,detail:payload});return row.payload;}
  async dashboard(user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events();const employees=this.latest(rows,'Employee'),certifications=this.latest(rows,'Certification'),leave=this.latest(rows,'Leave'),shifts=this.latest(rows,'Shift'),training=this.latest(rows,'Training'),assignments=this.latest(rows,'Assignment');const now=Date.now(),soon=now+30*86400000;const active=employees.filter((x:any)=>x.active!==false);const expiredCerts=certifications.filter((x:any)=>x.expiryDate&&new Date(x.expiryDate).getTime()<now);const expiringCerts=certifications.filter((x:any)=>x.expiryDate&&new Date(x.expiryDate).getTime()>=now&&new Date(x.expiryDate).getTime()<=soon);const activeLeave=leave.filter((x:any)=>x.status!=='CANCELLED'&&new Date(x.startDate).getTime()<=now&&new Date(x.endDate).getTime()>=now);const overdueTraining=training.filter((x:any)=>x.status!=='COMPLETED'&&x.dueDate&&new Date(x.dueDate).getTime()<now);const openShifts=shifts.filter((x:any)=>x.status!=='CANCELLED'&&(!x.employeeId||x.status==='OPEN'));const utilization=active.map((e:any)=>{const hrs=shifts.filter((s:any)=>s.employeeId===e.employeeId&&s.status!=='CANCELLED').reduce((a:number,s:any)=>a+Number(s.hours||0),0);const cap=Number(e.capacityHoursPerWeek||40);return {employeeId:e.employeeId,name:e.name,hours:hrs,capacity:cap,utilizationPct:cap?hrs/cap*100:0,status:hrs>cap?'OVERLOADED':hrs>cap*.85?'HIGH':'OK'};});return {summary:{activeEmployees:active.length,expiredCerts:expiredCerts.length,expiringCerts:expiringCerts.length,activeLeave:activeLeave.length,overdueTraining:overdueTraining.length,openShifts:openShifts.length,overloaded:utilization.filter((x:any)=>x.status==='OVERLOADED').length},employees,certifications,leave,shifts,training,assignments,utilization,expiredCerts,expiringCerts,overdueTraining};}
  async setEmployee(body:any,user:ScopeUser){const employeeId=String(body.employeeId||this.id('EMP'));if(!body.name)throw new BadRequestException('Employee name is required');return this.put('Employee','EMPLOYEE_SET',employeeId,{employeeId,name:String(body.name),email:body.email||null,role:body.role||'OPERATIONS',branchId:body.branchId||null,department:body.department||null,capacityHoursPerWeek:Number(body.capacityHoursPerWeek||40),skills:Array.isArray(body.skills)?body.skills:[],active:body.active!==false,notes:body.notes||null},user);}
  async setCertification(body:any,user:ScopeUser){if(!body.employeeId||!body.name)throw new BadRequestException('Employee and certification name are required');const certificationId=String(body.certificationId||this.id('CERT'));return this.put('Certification','CERTIFICATION_SET',certificationId,{certificationId,employeeId:String(body.employeeId),name:String(body.name),certificateNo:body.certificateNo||null,issuedDate:body.issuedDate||null,expiryDate:body.expiryDate||null,status:body.status||'VALID'},user);}
  async setLeave(body:any,user:ScopeUser){if(!body.employeeId||!body.startDate||!body.endDate)throw new BadRequestException('Employee, start date and end date are required');const leaveId=String(body.leaveId||this.id('LEAVE'));return this.put('Leave','LEAVE_SET',leaveId,{leaveId,employeeId:String(body.employeeId),leaveType:body.leaveType||'LEAVE',startDate:body.startDate,endDate:body.endDate,status:body.status||'APPROVED',notes:body.notes||null},user);}
  async setShift(body:any,user:ScopeUser){if(!body.startAt||!body.endAt)throw new BadRequestException('Shift start and end are required');const shiftId=String(body.shiftId||this.id('SHIFT')),hours=Math.max(0,(new Date(body.endAt).getTime()-new Date(body.startAt).getTime())/3600000);return this.put('Shift','SHIFT_SET',shiftId,{shiftId,employeeId:body.employeeId||null,branchId:body.branchId||null,startAt:body.startAt,endAt:body.endAt,hours,status:body.status||'PLANNED',roleRequired:body.roleRequired||null,notes:body.notes||null},user);}
  async setTraining(body:any,user:ScopeUser){if(!body.employeeId||!body.course)throw new BadRequestException('Employee and course are required');const trainingId=String(body.trainingId||this.id('TRN'));return this.put('Training','TRAINING_SET',trainingId,{trainingId,employeeId:String(body.employeeId),course:String(body.course),required:body.required!==false,dueDate:body.dueDate||null,completedAt:body.completedAt||null,status:body.completedAt?'COMPLETED':(body.status||'PENDING')},user);}
  async suitability(bookingId:string,user:ScopeUser){await this.scope.assertBookingAccess(user,bookingId);const booking:any=await this.prisma.booking.findUnique({where:{id:bookingId}}),rows=await this.events(),employees=this.latest(rows,'Employee').filter((x:any)=>x.active!==false),certs=this.latest(rows,'Certification'),leave=this.latest(rows,'Leave');const now=Date.now(),requiredSkills=(booking?.specialCargo==='DG'||booking?.dgUnNo)?['DG']:[];return employees.map((e:any)=>{const blockers:string[]=[];if(e.branchId&&booking?.owningBranchId&&e.branchId!==booking.owningBranchId)blockers.push('different branch');for(const s of requiredSkills)if(!(e.skills||[]).map((x:any)=>String(x).toUpperCase()).includes(s))blockers.push(`missing skill ${s}`);const onLeave=leave.some((l:any)=>l.employeeId===e.employeeId&&l.status!=='CANCELLED'&&new Date(l.startDate).getTime()<=now&&new Date(l.endDate).getTime()>=now);if(onLeave)blockers.push('currently on leave');const expired=certs.filter((c:any)=>c.employeeId===e.employeeId&&c.expiryDate&&new Date(c.expiryDate).getTime()<now);if(expired.length)blockers.push(`expired certification: ${expired.map((c:any)=>c.name).join(', ')}`);return {employeeId:e.employeeId,name:e.name,role:e.role,branchId:e.branchId,skills:e.skills||[],suitable:blockers.length===0,blockers};});}
  async assign(body:any,user:ScopeUser){if(!body.bookingId||!body.employeeId)throw new BadRequestException('Booking and employee are required');await this.scope.assertBookingAccess(user,String(body.bookingId));const candidates=await this.suitability(String(body.bookingId),user),candidate=candidates.find((x:any)=>x.employeeId===String(body.employeeId));if(!candidate)throw new BadRequestException('Employee not found');if(!candidate.suitable)throw new BadRequestException(`Assignment blocked: ${candidate.blockers.join('; ')}`);const assignmentId=String(body.assignmentId||this.id('ASN'));return this.put('Assignment','ASSIGNMENT_SET',assignmentId,{assignmentId,bookingId:String(body.bookingId),employeeId:String(body.employeeId),assignmentRole:body.assignmentRole||'OPERATOR',startAt:body.startAt||new Date().toISOString(),endAt:body.endAt||null,status:body.status||'ASSIGNED',notes:body.notes||null},user);}
}
