import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser, bookingScope } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SRC='ANCLINE_VENDOR_CONTROL', PROC='ANCLINE_PROCUREMENT';
@Injectable()
export class VendorControlService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private get db():any{return this.prisma as any;}
  private p(e:any){return (e?.payload||{}) as any;}
  private r(v:any){return Math.round((Number(v||0)+Number.EPSILON)*100)/100;}
  private internal(u:ScopeUser){this.scope.assertInternal(u);}
  private finance(u:ScopeUser){this.scope.assertFinanceAccess(u);}
  private req(v:any,n:string){const s=String(v??'').trim();if(!s)throw new BadRequestException(`${n} is required`);return s;}
  private periodOf(v:any){const d=new Date(v);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}

  private async vendor(vendorId:string){const v=await this.db.organization.findUnique({where:{id:vendorId}});if(!v||!v.active||!Array.isArray(v.roles)||!v.roles.includes('VENDOR'))throw new NotFoundException('Active vendor not found');return v;}
  private async profiles(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'VendorProfile',eventType:'VENDOR_PROFILE_SET'},orderBy:{createdAt:'asc'}}),m=new Map<string,any>();for(const e of rows)m.set(e.objectId,{vendorId:e.objectId,...this.p(e),updatedAt:e.createdAt});return m;}
  private async incidents(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'VendorIncident',eventType:'VENDOR_INCIDENT_RECORDED'},orderBy:{createdAt:'desc'}});return rows.map((e:any)=>({incidentId:e.objectId,...this.p(e),createdAt:e.createdAt}));}
  private async poRows(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:PROC,objectType:'PurchaseOrder'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [poNo,ev] of g){const c=ev.find((x:any)=>x.eventType==='PO_CREATED');if(!c)continue;const changes=ev.filter((x:any)=>['PO_CREATED','PO_UPDATED'].includes(x.eventType)),base={...this.p(changes[changes.length-1])};const approved=ev.find((x:any)=>x.eventType==='PO_APPROVED'),cancelled=ev.find((x:any)=>x.eventType==='PO_CANCELLED');if(cancelled)continue;const receipts=ev.filter((x:any)=>x.eventType==='PO_RECEIPT_RECORDED').map((x:any)=>({...this.p(x),createdAt:x.createdAt}));out.push({poNo,...base,approved:Boolean(approved),receipts});}return out;}

  private async governance(vendorId:string){const [profiles,incidents]=await Promise.all([this.profiles(),this.incidents()]);const p=profiles.get(vendorId)||{vendorId,approvalStatus:'UNREVIEWED',riskRating:'MEDIUM',preferred:false,maxSinglePO:null,complianceExpiry:null,insuranceExpiry:null,reviewDate:null};const now=Date.now(),expiredCompliance=p.complianceExpiry?new Date(p.complianceExpiry).getTime()<now:false,expiredInsurance=p.insuranceExpiry?new Date(p.insuranceExpiry).getTime()<now:false,critical=incidents.filter((x:any)=>x.vendorId===vendorId&&x.severity==='CRITICAL'&&x.status!=='CLOSED').length;const blocking=String(p.approvalStatus).toUpperCase()==='BLOCKED'||expiredCompliance||expiredInsurance||critical>0;return {...p,expiredCompliance,expiredInsurance,criticalOpenIncidents:critical,blocking};}
  async setVendorProfile(vendorId:string,b:any,u:ScopeUser){this.finance(u);const v=await this.vendor(vendorId),approvalStatus=String(b?.approvalStatus||'APPROVED').toUpperCase(),riskRating=String(b?.riskRating||'MEDIUM').toUpperCase();if(!['APPROVED','CONDITIONAL','BLOCKED'].includes(approvalStatus))throw new BadRequestException('Approval status must be APPROVED, CONDITIONAL or BLOCKED');if(!['LOW','MEDIUM','HIGH','RESTRICTED'].includes(riskRating))throw new BadRequestException('Risk rating must be LOW, MEDIUM, HIGH or RESTRICTED');const max=b?.maxSinglePO==null||b.maxSinglePO===''?null:Number(b.maxSinglePO);if(max!=null&&(!Number.isFinite(max)||max<0))throw new BadRequestException('Maximum single PO is invalid');const payload={vendorId,vendorName:v.name,approvalStatus,riskRating,preferred:Boolean(b?.preferred),maxSinglePO:max==null?null:this.r(max),complianceExpiry:b?.complianceExpiry?new Date(b.complianceExpiry).toISOString():null,insuranceExpiry:b?.insuranceExpiry?new Date(b.insuranceExpiry).toISOString():null,reviewDate:b?.reviewDate?new Date(b.reviewDate).toISOString():null,owner:b?.owner?String(b.owner):null,notes:b?.notes?String(b.notes):null,updatedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'VENDOR_PROFILE_SET',externalId:vendorId,objectType:'VendorProfile',objectId:vendorId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'VENDOR_PROFILE_SET',objectType:'Organization',objectId:vendorId,detail:{approvalStatus,riskRating,maxSinglePO:payload.maxSinglePO}});return this.governance(vendorId);}
  async recordIncident(vendorId:string,b:any,u:ScopeUser){this.internal(u);const v=await this.vendor(vendorId),severity=String(b?.severity||'MEDIUM').toUpperCase();if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(severity))throw new BadRequestException('Invalid severity');const incidentId=`VI-${Date.now().toString().slice(-10)}`,payload={vendorId,vendorName:v.name,severity,category:String(b?.category||'SERVICE').toUpperCase(),description:this.req(b?.description,'Description'),status:String(b?.status||'OPEN').toUpperCase(),poNo:b?.poNo?String(b.poNo):null,bookingId:b?.bookingId?String(b.bookingId):null,recordedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'VENDOR_INCIDENT_RECORDED',externalId:incidentId,objectType:'VendorIncident',objectId:incidentId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'VENDOR_INCIDENT_RECORDED',objectType:'Organization',objectId:vendorId,detail:{incidentId,severity,category:payload.category}});return {incidentId,...payload};}

  async marginLeakage(periodInput:string|undefined,u:ScopeUser){this.internal(u);const period=periodInput&&/^\d{4}-\d{2}$/.test(periodInput)?periodInput:null,bookings:any[]=await this.db.booking.findMany({where:{...bookingScope(u),status:{not:'CANCELLED'}},select:{id:true,bookingNo:true,shipmentNo:true,status:true,createdAt:true}}),ids=bookings.map((b:any)=>b.id);const lines:any[]=ids.length?await this.db.financeLine.findMany({where:{bookingId:{in:ids},status:{not:'CANCELLED'}},orderBy:{createdAt:'asc'}}):[];const out:any[]=[];for(const b of bookings){if(period&&this.periodOf(b.createdAt)!==period)continue;const bl=lines.filter((x:any)=>x.bookingId===b.id),currencies=Array.from(new Set(bl.map((x:any)=>String(x.currency))));for(const currency of currencies){const rows=bl.filter((x:any)=>String(x.currency)===currency),rev=rows.filter((x:any)=>x.type==='REVENUE'),cost=rows.filter((x:any)=>x.type==='COST');const estRevenue=this.r(rev.filter((x:any)=>x.source==='RATE_QUOTE').reduce((s:number,x:any)=>s+Number(x.finalAmount??x.amount),0)),estCostRows=cost.filter((x:any)=>x.source==='RATE_QUOTE'),poRows=cost.filter((x:any)=>x.source==='PROCUREMENT'),other=cost.filter((x:any)=>!['RATE_QUOTE','PROCUREMENT'].includes(String(x.source||'')));const estBy=new Map<string,number>(),poBy=new Map<string,number>(),otherBy=new Map<string,number>();for(const x of estCostRows)estBy.set(x.chargeCode,this.r((estBy.get(x.chargeCode)||0)+Number(x.amount||0)));for(const x of poRows)poBy.set(x.chargeCode,this.r((poBy.get(x.chargeCode)||0)+Number(x.finalAmount??x.amount)));for(const x of other)otherBy.set(x.chargeCode,this.r((otherBy.get(x.chargeCode)||0)+Number(x.finalAmount??x.amount)));const charges=Array.from(new Set([...estBy.keys(),...poBy.keys(),...otherBy.keys()]));let forecastCost=0;for(const c of charges)forecastCost+=poBy.has(c)?Number(poBy.get(c)||0)+Number(otherBy.get(c)||0):Number(estBy.get(c)||0)+Number(otherBy.get(c)||0);forecastCost=this.r(forecastCost);const estimatedCost=this.r(Array.from(estBy.values()).reduce((s:number,n:number)=>s+n,0)),committed=this.r(Array.from(poBy.values()).reduce((s:number,n:number)=>s+n,0)),actualRevenue=this.r(rev.reduce((s:number,x:any)=>s+Number(x.finalAmount??x.amount),0)),quoteGp=this.r(estRevenue-estimatedCost),forecastGp=this.r(actualRevenue-forecastCost),leakage=this.r(forecastCost-estimatedCost);out.push({bookingId:b.id,bookingNo:b.bookingNo,shipmentNo:b.shipmentNo,status:b.status,currency,estimatedRevenue:estRevenue,actualRevenue,estimatedCost,poCommitment:committed,forecastCost,quoteGp,forecastGp,leakage,leakagePct:estimatedCost?this.r(leakage/estimatedCost*100):null,marginPct:actualRevenue?this.r(forecastGp/actualRevenue*100):0,risk:leakage>0.005?'LEAKAGE':leakage<-0.005?'SAVING':'ON_PLAN'});}}return out.sort((a:any,b:any)=>b.leakage-a.leakage);}

  async vendorScorecards(u:ScopeUser){this.internal(u);const [vendors,pos,profiles,incidents]=await Promise.all([this.db.organization.findMany({where:{active:true,roles:{has:'VENDOR'}},select:{id:true,code:true,name:true,countryCode:true}}),this.poRows(),this.profiles(),this.incidents()]);const rows:any[]=[];for(const v of vendors){const vp=pos.filter((p:any)=>p.vendorId===v.id&&p.approved),delivered=vp.filter((p:any)=>p.receipts.length),onTime=delivered.filter((p:any)=>p.expectedDate&&Math.max(...p.receipts.map((r:any)=>new Date(r.receivedAt||r.createdAt).getTime()))<=new Date(p.expectedDate).getTime()).length,late=delivered.filter((p:any)=>p.expectedDate&&Math.max(...p.receipts.map((r:any)=>new Date(r.receivedAt||r.createdAt).getTime()))>new Date(p.expectedDate).getTime()).length,inv=await this.db.financeLine.findMany({where:{serviceProviderId:v.id,source:'PROCUREMENT',status:{not:'CANCELLED'}},select:{invoiceNo:true,status:true,amount:true,finalAmount:true}}),invoiceCoverage=inv.length?this.r(inv.filter((x:any)=>x.invoiceNo).length/inv.length*100):0,gov=await this.governance(v.id),vi=incidents.filter((x:any)=>x.vendorId===v.id&&x.status!=='CLOSED');const slaScore=delivered.length?this.r(onTime/delivered.length*100):null;rows.push({...v,...gov,poCount:vp.length,deliveredPoCount:delivered.length,onTimeCount:onTime,lateCount:late,onTimePct:slaScore,invoiceCoveragePct:invoiceCoverage,openIncidents:vi.length,highCriticalIncidents:vi.filter((x:any)=>['HIGH','CRITICAL'].includes(x.severity)).length,score:slaScore==null?null:Math.max(0,this.r(slaScore-vi.filter((x:any)=>x.severity==='CRITICAL').length*20-vi.filter((x:any)=>x.severity==='HIGH').length*10))});}return rows.sort((a:any,b:any)=>(Number(b.poCount)-Number(a.poCount))||String(a.name).localeCompare(String(b.name)));}
  async vendorDetail(vendorId:string,u:ScopeUser){this.internal(u);const v=await this.vendor(vendorId),score=(await this.vendorScorecards(u)).find((x:any)=>x.id===vendorId),pos=(await this.poRows()).filter((p:any)=>p.vendorId===vendorId),inc=(await this.incidents()).filter((x:any)=>x.vendorId===vendorId);return {vendor:v,scorecard:score,purchaseOrders:pos,incidents:inc,governance:await this.governance(vendorId)};}
  async dashboard(u:ScopeUser){this.internal(u);const [margins,vendors]=await Promise.all([this.marginLeakage(undefined,u),this.vendorScorecards(u)]);const cur=new Map<string,number>();for(const x of margins)cur.set(x.currency,this.r((cur.get(x.currency)||0)+Number(x.leakage||0)));return {jobs:margins.length,leakageJobs:margins.filter((x:any)=>x.risk==='LEAKAGE').length,totalLeakageByCurrency:Array.from(cur.entries()).map(([currency,amount])=>({currency,amount})),vendors:vendors.length,blockedVendors:vendors.filter((x:any)=>x.blocking).length,preferredVendors:vendors.filter((x:any)=>x.preferred).length,highRiskVendors:vendors.filter((x:any)=>['HIGH','RESTRICTED'].includes(String(x.riskRating))).length,openIncidents:vendors.reduce((s:number,x:any)=>s+Number(x.openIncidents||0),0),lateDeliveries:vendors.reduce((s:number,x:any)=>s+Number(x.lateCount||0),0)};}
}
