import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser, bookingScope } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SOURCE='ANCLINE_DATA_QUALITY';
const now=()=>new Date();
const makeId=(p:string)=>`${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;

@Injectable()
export class DataQualityService {
 constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
 private payload(e:any){return (e?.payload||{}) as any;}
 private latest(rows:any[],type:string){const m=new Map<string,any>();for(const e of rows)if(e.objectType===type)m.set(e.objectId,{...this.payload(e),updatedAt:e.createdAt,eventType:e.eventType});return [...m.values()];}
 private admin(user:ScopeUser){if(user.role!=='GLOBAL_ADMIN')throw new ForbiddenException('Global administrator access required');}
 private async write(type:string,eventType:string,id:string,payload:any,user:ScopeUser){const row=await this.prisma.integrationEvent.create({data:{sourceSystem:SOURCE,objectType:type,objectId:id,eventType,status:'COMPLETED',payload:{...payload,updatedBy:user.sub},completedAt:now()}});await this.audit.log({actorId:user.sub,action:eventType,objectType:type,objectId:id,bookingId:payload.bookingId||undefined,detail:payload});return row.payload;}
 private value(obj:any,path?:string|null){if(!path)return undefined;return String(path).split('.').reduce((v:any,k:string)=>v==null?undefined:v[k],obj);}
 private matches(v:any,op:string,target:any){const o=String(op||'REQUIRED').toUpperCase();if(o==='REQUIRED'||o==='EXISTS')return !(v==null||v===''||(Array.isArray(v)&&!v.length));if(o==='EQUALS')return String(v??'')===String(target??'');if(o==='NOT_EQUALS')return String(v??'')!==String(target??'');if(o==='GT')return Number(v)>Number(target);if(o==='GTE')return Number(v)>=Number(target);if(o==='LT')return Number(v)<Number(target);if(o==='LTE')return Number(v)<=Number(target);if(o==='CONTAINS')return String(v??'').toLowerCase().includes(String(target??'').toLowerCase());if(o==='IN')return String(target||'').split(',').map(x=>x.trim()).includes(String(v??''));if(o==='REGEX'){try{return new RegExp(String(target||''),'i').test(String(v??''));}catch{return false;}}return true;}
 async rules(user:ScopeUser){this.scope.assertInternal(user);const rows=await this.prisma.integrationEvent.findMany({where:{sourceSystem:SOURCE},orderBy:{createdAt:'asc'}});return this.latest(rows,'ValidationRule');}
 async setRule(body:any,user:ScopeUser){this.admin(user);if(!body?.name||!body?.objectType||!body?.field)throw new BadRequestException('Name, object type and field are required');const ruleId=String(body.ruleId||makeId('DQR'));const payload={ruleId,name:String(body.name),objectType:String(body.objectType).toUpperCase(),field:String(body.field),operator:String(body.operator||'REQUIRED').toUpperCase(),value:body.value??null,severity:String(body.severity||'ERROR').toUpperCase(),action:String(body.action||'WARN').toUpperCase(),gate:String(body.gate||'ANY').toUpperCase(),branchId:body.branchId||null,customerId:body.customerId||null,message:body.message||null,active:body.active!==false};return this.write('ValidationRule','VALIDATION_RULE_SET',ruleId,payload,user);}
 private async bookingRecord(id:string,user:ScopeUser){await this.scope.assertBookingAccess(user,id);const b=await this.prisma.booking.findUnique({where:{id},include:{customer:true,rateQuote:true,documents:true,financeLines:true,containers:true}});if(!b)throw new BadRequestException('Booking not found');return b as any;}
 private async baseline(b:any){const issues:any[]=[];const add=(code:string,severity:string,message:string,field?:string)=>issues.push({code,severity,message,field:field||null,source:'BASELINE'});
  for(const [field,label] of [['bookingNo','Booking number'],['customerId','Customer'],['origin','Origin'],['destination','Destination']] as any[])if(!b[field])add(`REQ_${field.toUpperCase()}`,'ERROR',`${label} is required`,field);
  if(b.etd&&b.eta&&new Date(b.eta).getTime()<new Date(b.etd).getTime())add('DATE_ETA_BEFORE_ETD','ERROR','ETA is earlier than ETD','eta');
  const dg=String(b.specialCargo||'').toUpperCase().includes('DG')||!!b.dgUnNo||!!b.dgImoClass;if(dg&&!b.dgUnNo)add('DG_UN_MISSING','ERROR','Dangerous-goods UN number is missing','dgUnNo');if(dg&&!b.dgImoClass)add('DG_CLASS_MISSING','ERROR','Dangerous-goods IMO class is missing','dgImoClass');
  if(b.rateQuote&&String(b.rateQuote.customerId)!==String(b.customerId))add('QUOTE_CUSTOMER_MISMATCH','ERROR','Selected quote belongs to a different customer','rateQuoteId');
  for(const d of b.documents||[])if(String(d.status).toUpperCase()==='RELEASED'&&!d.fileKey)add('DOC_RELEASED_NO_FILE','WARN',`Released document ${d.documentNo} has no file reference`,'documents');
  for(const f of b.financeLines||[]){if(Number(f.amount)===0)add('FIN_ZERO_AMOUNT','WARN',`Finance line ${f.chargeCode} has zero amount`,'financeLines');if(!f.currency)add('FIN_CURRENCY_MISSING','ERROR',`Finance line ${f.chargeCode} has no currency`,'financeLines');}
  const refs=[['carrierBookingNo',b.carrierBookingNo],['houseBL',b.houseBL],['masterBL',b.masterBL]].filter((x:any)=>x[1]);for(const [field,val] of refs as any[]){const dup=await this.prisma.booking.findFirst({where:{id:{not:b.id},[field]:val},select:{id:true,bookingNo:true}} as any);if(dup)add(`DUP_${String(field).toUpperCase()}`,'ERROR',`${field} ${val} is also used on ${dup.bookingNo}`,field);}
  return issues;
 }
 async checkBooking(id:string,user:ScopeUser,gate='ANY'){const b=await this.bookingRecord(id,user),issues=await this.baseline(b),rules=(await this.rules(user)).filter((r:any)=>r.active!==false&&r.objectType==='BOOKING'&&(r.gate==='ANY'||r.gate===String(gate).toUpperCase())&&(!r.branchId||String(r.branchId)===String(b.owningBranchId))&&(!r.customerId||String(r.customerId)===String(b.customerId)));for(const r of rules){const v=this.value(b,r.field),valid=this.matches(v,r.operator,r.value);if(!valid)issues.push({code:r.ruleId,severity:r.severity||'ERROR',message:r.message||`${r.name}: ${r.field} failed ${r.operator}`,field:r.field,source:'RULE',action:r.action||'WARN',gate:r.gate});}const blockers=issues.filter((x:any)=>String(x.action||'WARN').toUpperCase()==='BLOCK'&&String(x.severity).toUpperCase()==='ERROR');return {bookingId:b.id,bookingNo:b.bookingNo,gate:String(gate).toUpperCase(),issues,blockers,clear:blockers.length===0,completeness:Math.max(0,100-Math.min(100,issues.filter((x:any)=>String(x.code).startsWith('REQ_')).length*25))};}
 async scan(user:ScopeUser){this.scope.assertInternal(user);const bookings=await this.prisma.booking.findMany({where:bookingScope(user),orderBy:{updatedAt:'desc'},take:100,select:{id:true}});const results=[] as any[];for(const b of bookings)results.push(await this.checkBooking(b.id,user,'ANY'));return results;}
 async createRemediation(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.bookingId||!body?.issueCode)throw new BadRequestException('Booking and issue code are required');await this.scope.assertBookingAccess(user,String(body.bookingId));const remediationId=String(body.remediationId||makeId('DQM')),payload={remediationId,bookingId:String(body.bookingId),bookingNo:body.bookingNo||null,issueCode:String(body.issueCode),message:body.message||null,severity:String(body.severity||'ERROR').toUpperCase(),ownerId:body.ownerId||null,dueAt:body.dueAt||null,status:'OPEN',resolution:null,createdBy:user.sub,createdAt:now().toISOString()};await this.write('Remediation','REMEDIATION_CREATED',remediationId,payload,user);if(body.ownerId){await this.prisma.task.create({data:{bookingId:payload.bookingId,title:`Data quality: ${payload.issueCode}${payload.message?` - ${payload.message}`:''}`,ownerId:String(body.ownerId),dueAt:body.dueAt?new Date(body.dueAt):null,status:'Open',slaState:'On Track'}});}return payload;}
 async updateRemediation(id:string,status:string,body:any,user:ScopeUser){this.scope.assertInternal(user);const rows=await this.prisma.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:'Remediation',objectId:id},orderBy:{createdAt:'desc'},take:1});const current:any=this.payload(rows[0]);if(!current?.remediationId)throw new BadRequestException('Remediation not found');await this.scope.assertBookingAccess(user,current.bookingId);const next={...current,status:String(status).toUpperCase(),resolution:body?.resolution||current.resolution||null,resolvedBy:['RESOLVED','CLOSED'].includes(String(status).toUpperCase())?user.sub:null,resolvedAt:['RESOLVED','CLOSED'].includes(String(status).toUpperCase())?now().toISOString():null};await this.write('Remediation','REMEDIATION_STATUS_SET',id,next,user);return next;}
 async dashboard(user:ScopeUser){this.scope.assertInternal(user);const [rules,scan,events]=await Promise.all([this.rules(user),this.scan(user),this.prisma.integrationEvent.findMany({where:{sourceSystem:SOURCE},orderBy:{createdAt:'asc'}})]);const remediations=this.latest(events,'Remediation'),allIssues=scan.flatMap((x:any)=>x.issues.map((i:any)=>({...i,bookingId:x.bookingId,bookingNo:x.bookingNo}))),duplicateIssues=allIssues.filter((x:any)=>String(x.code).startsWith('DUP_'));return {summary:{activeRules:rules.filter((x:any)=>x.active!==false).length,bookingsScanned:scan.length,issues:allIssues.length,errors:allIssues.filter((x:any)=>x.severity==='ERROR').length,warnings:allIssues.filter((x:any)=>x.severity==='WARN').length,duplicates:duplicateIssues.length,openRemediations:remediations.filter((x:any)=>!['RESOLVED','CLOSED'].includes(x.status)).length},rules,bookings:scan,issues:allIssues.slice(0,200),remediations:remediations.slice().reverse().slice(0,100)};}
}
