import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser, bookingScope } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SOURCE='ANCLINE_CUSTOMER_SERVICE';
const CASE='CustomerServiceCase';
const CLAIM='CargoClaim';
const RECOVERY='ServiceRecovery';

@Injectable()
export class CustomerServiceService {
 constructor(private db:PrismaService,private scope:ScopeService,private audit:AuditService){}
 private internal(u:ScopeUser){this.scope.assertInternal(u);}
 private finance(u:ScopeUser){this.scope.assertFinanceAccess(u);}
 private p(e:any){return (e?.payload||{}) as any;}
 private num(v:any,d=0){const n=Number(v);return Number.isFinite(n)?n:d;}
 private iso(v:any){if(!v)return null;const d=new Date(v);if(Number.isNaN(d.getTime()))throw new BadRequestException(`Invalid date: ${v}`);return d.toISOString();}
 private slaHours(severity:string){return severity==='CRITICAL'?4:severity==='HIGH'?12:severity==='MEDIUM'?24:48;}
 private async scopedBooking(id:string,u:ScopeUser){const row=await this.db.booking.findFirst({where:{id,...bookingScope(u)},select:{id:true,bookingNo:true,customerId:true,origin:true,destination:true,status:true,owningBranchId:true,carrier:true}});if(!row)throw new NotFoundException('Booking not found or outside your scope');return row;}
 private async events(type:string){return this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:type},orderBy:{createdAt:'asc'}});}
 private group(events:any[]){const m=new Map<string,any[]>();for(const e of events){if(!m.has(e.objectId))m.set(e.objectId,[]);m.get(e.objectId)!.push(e);}return m;}
 private caseRows(events:any[]){const out:any[]=[];for(const [id,ev] of this.group(events)){const c=ev.find((x:any)=>x.eventType==='CASE_CREATED');if(!c)continue;const base=this.p(c);const updates=ev.filter((x:any)=>x.eventType==='CASE_STATUS_CHANGED');const last=updates[updates.length-1];const resolved=updates.find((x:any)=>['RESOLVED','CLOSED'].includes(String(this.p(x).status)));const csat=ev.filter((x:any)=>x.eventType==='CSAT_RECORDED').at(-1);const status=last?this.p(last).status:'OPEN';const due=new Date(new Date(c.createdAt).getTime()+this.slaHours(base.severity)*3600000);out.push({caseId:id,...base,status,createdAt:c.createdAt,updatedAt:(last||c).createdAt,resolvedAt:resolved?.createdAt||null,slaDueAt:due.toISOString(),slaBreached:!['RESOLVED','CLOSED'].includes(status)&&Date.now()>due.getTime(),csat:csat?this.p(csat):null});}return out.sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());}
 private claimRows(events:any[]){const out:any[]=[];for(const [id,ev] of this.group(events)){const c=ev.find((x:any)=>x.eventType==='CLAIM_CREATED');if(!c)continue;const base=this.p(c);const states=ev.filter((x:any)=>x.eventType.startsWith('CLAIM_')&&x.eventType!=='CLAIM_CREATED');const last=states[states.length-1];const lp=last?this.p(last):{};out.push({claimId:id,...base,...lp,status:lp.status||'DRAFT',createdAt:c.createdAt,updatedAt:(last||c).createdAt});}return out.sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());}
 private recoveryRows(events:any[]){const out:any[]=[];for(const [id,ev] of this.group(events)){const c=ev.find((x:any)=>x.eventType==='RECOVERY_REQUESTED');if(!c)continue;const d=ev.filter((x:any)=>['RECOVERY_APPROVED','RECOVERY_REJECTED','RECOVERY_COMPLETED'].includes(x.eventType)).at(-1);out.push({recoveryId:id,...this.p(c),...(d?this.p(d):{}),status:d?this.p(d).status:'PENDING',createdAt:c.createdAt,updatedAt:(d||c).createdAt});}return out.sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());}
 async customers(u:ScopeUser){this.internal(u);return this.db.organization.findMany({where:{active:true,roles:{has:'CUSTOMER'}},select:{id:true,name:true,code:true},orderBy:{name:'asc'}});}
 async bookings(u:ScopeUser){this.internal(u);return this.db.booking.findMany({where:{...bookingScope(u),status:{not:'CANCELLED'}},select:{id:true,bookingNo:true,customerId:true,origin:true,destination:true,status:true},orderBy:{createdAt:'desc'},take:300});}
 async cases(u:ScopeUser){this.internal(u);const rows=this.caseRows(await this.events(CASE));const allowed=new Set((await this.bookings(u)).map((x:any)=>x.id));return rows.filter(x=>allowed.has(x.bookingId));}
 async createCase(body:any,u:ScopeUser){this.internal(u);const b=await this.scopedBooking(String(body?.bookingId||''),u);const severity=String(body?.severity||'MEDIUM').toUpperCase();if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(severity))throw new BadRequestException('Invalid severity');if(!String(body?.subject||'').trim())throw new BadRequestException('Subject is required');const id=`CASE-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const payload={bookingId:b.id,bookingNo:b.bookingNo,customerId:b.customerId,category:String(body?.category||'SERVICE').toUpperCase(),severity,subject:String(body.subject).trim(),description:String(body?.description||'').trim(),owner:String(body?.owner||u.email||u.sub),contactName:String(body?.contactName||''),contactEmail:String(body?.contactEmail||''),source:String(body?.source||'INTERNAL').toUpperCase(),createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'CASE_CREATED',objectType:CASE,objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'CUSTOMER_SERVICE_CASE_CREATE',objectType:CASE,objectId:id,bookingId:b.id,detail:{bookingNo:b.bookingNo,severity,category:payload.category}});return {caseId:id,...payload,status:'OPEN'};}
 async setCaseStatus(id:string,body:any,u:ScopeUser){this.internal(u);const rows=this.caseRows(await this.events(CASE));const c=rows.find(x=>x.caseId===id);if(!c)throw new NotFoundException('Case not found');await this.scopedBooking(c.bookingId,u);const status=String(body?.status||'').toUpperCase();if(!['OPEN','INVESTIGATING','WAITING_CUSTOMER','WAITING_CARRIER','RESOLVED','CLOSED'].includes(status))throw new BadRequestException('Invalid case status');const payload={status,note:String(body?.note||''),resolution:String(body?.resolution||''),updatedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'CASE_STATUS_CHANGED',objectType:CASE,objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {caseId:id,...payload};}
 async csat(id:string,body:any,u:ScopeUser){this.internal(u);const rows=this.caseRows(await this.events(CASE));const c=rows.find(x=>x.caseId===id);if(!c)throw new NotFoundException('Case not found');await this.scopedBooking(c.bookingId,u);const score=Math.round(this.num(body?.score));if(score<1||score>5)throw new BadRequestException('CSAT score must be 1 to 5');const payload={score,comment:String(body?.comment||''),recordedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'CSAT_RECORDED',objectType:CASE,objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {caseId:id,...payload};}
 async claims(u:ScopeUser){this.internal(u);const rows=this.claimRows(await this.events(CLAIM));const allowed=new Set((await this.bookings(u)).map((x:any)=>x.id));return rows.filter(x=>allowed.has(x.bookingId));}
 async createClaim(body:any,u:ScopeUser){this.internal(u);const b=await this.scopedBooking(String(body?.bookingId||''),u);const amount=this.num(body?.claimedAmount);if(amount<0)throw new BadRequestException('Claim amount cannot be negative');const id=`CLM-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const payload={bookingId:b.id,bookingNo:b.bookingNo,customerId:b.customerId,claimType:String(body?.claimType||'DAMAGE').toUpperCase(),claimedAmount:amount,currency:String(body?.currency||'USD').toUpperCase(),incidentDate:this.iso(body?.incidentDate),notificationDeadline:this.iso(body?.notificationDeadline),liablePartyType:String(body?.liablePartyType||'CARRIER').toUpperCase(),liablePartyId:String(body?.liablePartyId||''),insurerReference:String(body?.insurerReference||''),description:String(body?.description||''),reserveAmount:this.num(body?.reserveAmount,amount),createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'CLAIM_CREATED',objectType:CLAIM,objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {claimId:id,...payload,status:'DRAFT'};}
 async claimAction(id:string,action:string,body:any,u:ScopeUser){this.internal(u);const c=(await this.claims(u)).find(x=>x.claimId===id);if(!c)throw new NotFoundException('Claim not found');const a=action.toUpperCase();const map:Record<string,string>={SUBMIT:'SUBMITTED',ASSESS:'UNDER_ASSESSMENT',APPROVE:'APPROVED',REJECT:'REJECTED',SETTLE:'SETTLED',CLOSE:'CLOSED'};const status=map[a];if(!status)throw new BadRequestException('Invalid claim action');if(['APPROVE','SETTLE'].includes(a))this.finance(u);const payload={status,approvedAmount:a==='APPROVE'?this.num(body?.approvedAmount,c.claimedAmount):c.approvedAmount||null,settledAmount:a==='SETTLE'?this.num(body?.settledAmount,c.approvedAmount||c.claimedAmount):c.settledAmount||null,note:String(body?.note||''),decisionBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:`CLAIM_${a}`,objectType:CLAIM,objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {claimId:id,...payload};}
 async recoveries(u:ScopeUser){this.internal(u);const rows=this.recoveryRows(await this.events(RECOVERY));const allowed=new Set((await this.bookings(u)).map((x:any)=>x.id));return rows.filter(x=>allowed.has(x.bookingId));}
 async requestRecovery(body:any,u:ScopeUser){this.internal(u);const b=await this.scopedBooking(String(body?.bookingId||''),u);const amount=this.num(body?.amount);if(amount<=0)throw new BadRequestException('Recovery amount must be positive');const id=`SR-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const payload={bookingId:b.id,bookingNo:b.bookingNo,customerId:b.customerId,recoveryType:String(body?.recoveryType||'GOODWILL_CREDIT').toUpperCase(),amount,currency:String(body?.currency||'USD').toUpperCase(),reason:String(body?.reason||''),caseId:String(body?.caseId||''),requestedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'RECOVERY_REQUESTED',objectType:RECOVERY,objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {recoveryId:id,...payload,status:'PENDING'};}
 async decideRecovery(id:string,decision:string,body:any,u:ScopeUser){this.finance(u);const r=(await this.recoveries(u)).find(x=>x.recoveryId===id);if(!r)throw new NotFoundException('Recovery request not found');if(!['APPROVE','REJECT','COMPLETE'].includes(decision.toUpperCase()))throw new BadRequestException('Invalid decision');if(decision.toUpperCase()==='COMPLETE'&&r.status!=='APPROVED')throw new BadRequestException('Only approved recovery can be completed');const status=decision.toUpperCase()==='APPROVE'?'APPROVED':decision.toUpperCase()==='REJECT'?'REJECTED':'COMPLETED';const payload={status,note:String(body?.note||''),externalReference:String(body?.externalReference||''),decidedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:`RECOVERY_${status}`,objectType:RECOVERY,objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {recoveryId:id,...payload};}
 async dashboard(u:ScopeUser){this.internal(u);const [cases,claims,recoveries]=await Promise.all([this.cases(u),this.claims(u),this.recoveries(u)]);const csat=cases.filter(x=>x.csat?.score).map(x=>Number(x.csat.score));const openCases=cases.filter(x=>!['RESOLVED','CLOSED'].includes(x.status));const openClaims=claims.filter(x=>!['REJECTED','SETTLED','CLOSED'].includes(x.status));const claimExposure=new Map<string,number>();for(const c of openClaims)claimExposure.set(c.currency,(claimExposure.get(c.currency)||0)+Number(c.reserveAmount||c.claimedAmount||0));return {summary:{openCases:openCases.length,slaBreaches:openCases.filter(x=>x.slaBreached).length,criticalCases:openCases.filter(x=>x.severity==='CRITICAL').length,openClaims:openClaims.length,pendingRecoveries:recoveries.filter(x=>x.status==='PENDING').length,avgCsat:csat.length?Number((csat.reduce((a,b)=>a+b,0)/csat.length).toFixed(2)):null},claimExposure:[...claimExposure].map(([currency,amount])=>({currency,amount:Number(amount.toFixed(2))})),cases,claims,recoveries};}
}
