'use client';

import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtMoney,requireToken} from '../../lib/api';

const month=()=>new Date().toISOString().slice(0,7);
export default function CommercialProfitabilityPage(){
  const [token,setToken]=useState(''),[period,setPeriod]=useState(month()),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [dash,setDash]=useState<any>({}),[profit,setProfit]=useState<any>({jobs:[],byCustomer:[],byLane:[],summary:{}}),[rec,setRec]=useState<any>({opportunities:[],cases:[]}),[exceptions,setExceptions]=useState<any[]>([]);
  async function load(t=token,p=period){if(!t)return;setBusy(true);setMessage('');try{const [d,pr,r,e]=await Promise.all([api('/commercial-profitability/dashboard',t),api(`/commercial-profitability/profitability?period=${p}`,t),api('/commercial-profitability/recoveries',t),api('/commercial-profitability/margin-exceptions',t)]);setDash(d);setProfit(pr);setRec(r);setExceptions(Array.isArray(e)?e:[]);}catch(x:any){setMessage(x.message||'Unable to load commercial profitability');}finally{setBusy(false);}}
  useEffect(()=>{const t=requireToken();if(t){setToken(t);void load(t,period);}},[]);
  async function propose(o:any){setBusy(true);try{await api('/commercial-profitability/recoveries',token,{method:'POST',body:JSON.stringify({...o,reason:`Recover ${o.type.toLowerCase()} exposure`})});setMessage('Recovery submitted for approval.');await load();}catch(x:any){setMessage(x.message);}finally{setBusy(false);}}
  async function decideRecovery(id:string,decision:string){setBusy(true);try{await api(`/commercial-profitability/recoveries/${id}/${decision}`,token,{method:'POST',body:JSON.stringify({})});setMessage(`Recovery ${decision.toLowerCase()}d.`);await load();}catch(x:any){setMessage(x.message);}finally{setBusy(false);}}
  async function submitException(j:any){const reason=window.prompt('Reason for margin exception approval?');if(!reason)return;setBusy(true);try{await api('/commercial-profitability/margin-exceptions',token,{method:'POST',body:JSON.stringify({...j,reason})});setMessage('Margin exception submitted.');await load();}catch(x:any){setMessage(x.message);}finally{setBusy(false);}}
  async function decideException(id:string,decision:string){setBusy(true);try{await api(`/commercial-profitability/margin-exceptions/${id}/${decision}`,token,{method:'POST',body:JSON.stringify({})});setMessage(`Margin exception ${decision.toLowerCase()}d.`);await load();}catch(x:any){setMessage(x.message);}finally{setBusy(false);}}
  const cards=[['Jobs',dash.jobs],['Loss Jobs',dash.lossJobs],['Leakage Jobs',dash.leakageJobs],['Open Recoveries',dash.openRecoveries],['Recovery Approvals',dash.pendingRecoveryApprovals],['Margin Exceptions',dash.pendingMarginExceptions]];
  return <WorkspaceShell title="Commercial Profitability Control" subtitle="Customer and lane profitability, quote-to-actual margin bridge, recovery and exception approvals" active="/commercial-profitability" actions={<button className="btn" disabled={busy} onClick={()=>void load()}>Refresh</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="card" style={{marginBottom:12}}><label style={{maxWidth:220}}><span style={labelStyle}>Reporting month</span><input type="month" style={fieldStyle} value={period} onChange={e=>{setPeriod(e.target.value);void load(token,e.target.value);}}/></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',gap:10,marginTop:12}}>{cards.map(([k,v])=><div key={String(k)}><div className="sub">{k}</div><div style={{fontSize:22,fontWeight:800}}>{v??0}</div></div>)}</div></div>
    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Job Margin Bridge</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Job</th><th>Customer</th><th>Lane</th><th>Currency</th><th>Quoted Cost</th><th>Forecast Cost</th><th>Revenue</th><th>GP</th><th>Margin</th><th>Leakage</th><th>Status</th><th></th></tr></thead><tbody>{(profit.jobs||[]).map((j:any)=><tr key={`${j.bookingId}-${j.currency}`}><td>{j.bookingNo}</td><td>{j.customerName}</td><td>{j.lane}</td><td>{j.currency}</td><td>{fmtMoney(j.quotedCost,j.currency)}</td><td>{fmtMoney(j.forecastCost,j.currency)}</td><td>{fmtMoney(j.forecastRevenue,j.currency)}</td><td>{fmtMoney(j.forecastGp,j.currency)}</td><td>{j.marginPct}%</td><td>{fmtMoney(j.leakage,j.currency)}</td><td><span className="status">{j.marginStatus}</span></td><td>{['LOSS','LEAKAGE'].includes(j.marginStatus)&&<button className="btn" disabled={busy} onClick={()=>void submitException(j)}>Request exception</button>}</td></tr>)}</tbody></table></div></div>
    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Revenue Recovery Opportunities</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Job</th><th>Type</th><th>Container / Charge</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{(rec.opportunities||[]).map((o:any)=><tr key={o.opportunityRef}><td>{o.bookingNo}</td><td>{o.type}</td><td>{o.containerNo||o.chargeCode}</td><td>{fmtMoney(o.amount,o.currency)}</td><td>{o.status}</td><td>{o.status==='OPEN'&&<button className="btn" disabled={busy} onClick={()=>void propose(o)}>Submit recovery</button>}</td></tr>)}</tbody></table></div></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(420px,1fr))',gap:12}}>
      <div className="card"><h3 style={sectionTitle}>Recovery Approval Queue</h3>{(rec.cases||[]).map((x:any)=><div key={x.caseId} style={{padding:'9px 0',borderBottom:'1px solid #e5e9ee'}}><b>{x.caseId}</b> · {x.bookingNo||x.bookingId} · {x.type} · {fmtMoney(x.amount,x.currency)} <span className="status">{x.status}</span>{x.status==='PENDING'&&<div style={{display:'flex',gap:6,marginTop:6}}><button className="btn" onClick={()=>void decideRecovery(x.caseId,'APPROVE')}>Approve</button><button className="btn" onClick={()=>void decideRecovery(x.caseId,'REJECT')}>Reject</button></div>}</div>)}</div>
      <div className="card"><h3 style={sectionTitle}>Margin Exception Queue</h3>{exceptions.map((x:any)=><div key={x.exceptionId} style={{padding:'9px 0',borderBottom:'1px solid #e5e9ee'}}><b>{x.bookingNo||x.bookingId}</b> · GP {fmtMoney(x.forecastGp,x.currency)} · Margin {x.marginPct}% · {x.reason} <span className="status">{x.status}</span>{x.status==='PENDING'&&<div style={{display:'flex',gap:6,marginTop:6}}><button className="btn" onClick={()=>void decideException(x.exceptionId,'APPROVE')}>Approve</button><button className="btn" onClick={()=>void decideException(x.exceptionId,'REJECT')}>Reject</button></div>}</div>)}</div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(420px,1fr))',gap:12,marginTop:12}}><div className="card"><h3 style={sectionTitle}>Customer Profitability</h3>{(profit.byCustomer||[]).slice(0,25).map((x:any)=><div key={`${x.currency}-${x.name}`} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid #eef1f4'}}><span>{x.name} · {x.jobs} jobs</span><b>{fmtMoney(x.gp,x.currency)} GP · {x.marginPct}%</b></div>)}</div><div className="card"><h3 style={sectionTitle}>Lane Profitability</h3>{(profit.byLane||[]).slice(0,25).map((x:any)=><div key={`${x.currency}-${x.name}`} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid #eef1f4'}}><span>{x.name} · {x.jobs} jobs</span><b>{fmtMoney(x.gp,x.currency)} GP · {x.marginPct}%</b></div>)}</div></div>
  </WorkspaceShell>;
}
