'use client';

import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);

export default function GovernancePage(){
  const [token,setToken]=useState('');const [data,setData]=useState<any>({summary:{},referenceData:[],changeRequests:[],permissions:[],thresholds:[],workflows:[],notifications:[]});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const [ref,setRef]=useState({category:'PORT',key:'',label:'',value:'',reason:''});
  const [perm,setPerm]=useState({role:'BRANCH_OPS',capabilities:'BOOKING_READ,BOOKING_UPDATE'});
  const [thr,setThr]=useState({process:'PROCUREMENT',amountMin:'0',amountMax:'',currency:'USD',approverRole:'FINANCE'});
  const [wf,setWf]=useState({process:'BOOKING',trigger:'EXCEPTION_RAISED',conditionField:'severity',operator:'EQUALS',conditionValue:'CRITICAL',action:'ESCALATE',ownerRole:'CONTROL_TOWER',escalateAfterMinutes:'60'});
  const [ntf,setNtf]=useState({eventType:'SLA_BREACH',channels:'IN_APP,EMAIL',recipients:'CONTROL_TOWER',severity:'HIGH'});
  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
  async function load(t=token){try{setData(await api('/governance/dashboard',t));}catch(e:any){setMessage(e.message||'Unable to load governance data');}}
  async function post(path:string,body:any,success:string){setBusy(true);setMessage('');try{await api(path,token,{method:'POST',body:JSON.stringify(body)});setMessage(success);await load();}catch(e:any){setMessage(e.message||'Action failed');}finally{setBusy(false);}}
  const s=data.summary||{};
  return <WorkspaceShell title="Master Data Governance / Rules" subtitle="Controlled reference data, permission matrices, approval thresholds, workflow escalation and notification rules" active="/governance" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="grid" style={{marginBottom:12}}>{[['REFERENCE DATA',s.referenceEntries],['PENDING CHANGES',s.pendingChanges],['ROLE MATRICES',s.permissionRoles],['APPROVAL RULES',s.approvalThresholds],['WORKFLOWS',s.workflowRules],['NOTIFICATIONS',s.notificationRules]].map(([l,v])=><div className="card" key={String(l)}><div className="sub">{l}</div><div className="kpi">{v||0}</div></div>)}</div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Request Master-Data Change</h3><div style={formGrid}>
      <label><span style={labelStyle}>Category *</span><input style={fieldStyle} value={ref.category} onChange={e=>setRef({...ref,category:e.target.value})}/></label>
      <label><span style={labelStyle}>Key *</span><input style={fieldStyle} value={ref.key} onChange={e=>setRef({...ref,key:e.target.value})}/></label>
      <label><span style={labelStyle}>Label</span><input style={fieldStyle} value={ref.label} onChange={e=>setRef({...ref,label:e.target.value})}/></label>
      <label><span style={labelStyle}>Value</span><input style={fieldStyle} value={ref.value} onChange={e=>setRef({...ref,value:e.target.value})}/></label>
      <label><span style={labelStyle}>Reason</span><input style={fieldStyle} value={ref.reason} onChange={e=>setRef({...ref,reason:e.target.value})}/></label>
    </div><div style={{textAlign:'right',marginTop:10}}><button className="btn" disabled={busy} onClick={()=>post('/governance/reference-data/changes',ref,'Master-data change submitted for maker/checker approval.')}>Submit Change</button></div></div>

    <div className="card" style={{marginBottom:12,overflowX:'auto'}}><h3 style={sectionTitle}>Pending Master-Data Changes</h3><table className="table"><thead><tr><th>Category / Key</th><th>Requested By</th><th>Reason</th><th>Status</th><th>Actions</th></tr></thead><tbody>{(data.changeRequests||[]).filter((x:any)=>x.status==='PENDING').map((x:any)=><tr key={x.changeId}><td><b>{x.proposed?.category}</b> · {x.proposed?.key}</td><td>{x.requesterId}</td><td>{x.reason||'-'}</td><td><span className="status">{x.status}</span></td><td><div style={{display:'flex',gap:6}}><button className="btn" onClick={()=>post(`/governance/reference-data/changes/${x.changeId}/approve`,{},'Change approved and published.')}>Approve</button><button className="btn" onClick={()=>post(`/governance/reference-data/changes/${x.changeId}/reject`,{},'Change rejected.')}>Reject</button></div></td></tr>)}{!(data.changeRequests||[]).some((x:any)=>x.status==='PENDING')&&<tr><td colSpan={5}>No pending master-data changes.</td></tr>}</tbody></table></div>

    <div className="grid" style={{alignItems:'start',marginBottom:12}}>
      <div className="card"><h3 style={sectionTitle}>Role / Permission Matrix</h3><div style={formGrid}><label><span style={labelStyle}>Role</span><input style={fieldStyle} value={perm.role} onChange={e=>setPerm({...perm,role:e.target.value})}/></label><label><span style={labelStyle}>Capabilities (comma separated)</span><input style={fieldStyle} value={perm.capabilities} onChange={e=>setPerm({...perm,capabilities:e.target.value})}/></label></div><div style={{textAlign:'right',marginTop:10}}><button className="btn" onClick={()=>post('/governance/permissions',{...perm,capabilities:split(perm.capabilities)},'Permission matrix saved.')}>Save Matrix</button></div><table className="table" style={{marginTop:10}}><tbody>{(data.permissions||[]).map((x:any)=><tr key={x.permissionId}><td><b>{x.role}</b></td><td>{(x.capabilities||[]).join(', ')}</td></tr>)}</tbody></table></div>
      <div className="card"><h3 style={sectionTitle}>Approval Threshold</h3><div style={formGrid}><label><span style={labelStyle}>Process</span><input style={fieldStyle} value={thr.process} onChange={e=>setThr({...thr,process:e.target.value})}/></label><label><span style={labelStyle}>Min Amount</span><input style={fieldStyle} value={thr.amountMin} onChange={e=>setThr({...thr,amountMin:e.target.value})}/></label><label><span style={labelStyle}>Max Amount</span><input style={fieldStyle} value={thr.amountMax} onChange={e=>setThr({...thr,amountMax:e.target.value})}/></label><label><span style={labelStyle}>Currency</span><input style={fieldStyle} value={thr.currency} onChange={e=>setThr({...thr,currency:e.target.value})}/></label><label><span style={labelStyle}>Approver Role</span><input style={fieldStyle} value={thr.approverRole} onChange={e=>setThr({...thr,approverRole:e.target.value})}/></label></div><div style={{textAlign:'right',marginTop:10}}><button className="btn" onClick={()=>post('/governance/approval-thresholds',thr,'Approval threshold saved.')}>Save Threshold</button></div></div>
    </div>

    <div className="grid" style={{alignItems:'start',marginBottom:12}}>
      <div className="card"><h3 style={sectionTitle}>Workflow / Escalation Rule</h3><div style={formGrid}><label><span style={labelStyle}>Process</span><input style={fieldStyle} value={wf.process} onChange={e=>setWf({...wf,process:e.target.value})}/></label><label><span style={labelStyle}>Trigger</span><input style={fieldStyle} value={wf.trigger} onChange={e=>setWf({...wf,trigger:e.target.value})}/></label><label><span style={labelStyle}>Condition Field</span><input style={fieldStyle} value={wf.conditionField} onChange={e=>setWf({...wf,conditionField:e.target.value})}/></label><label><span style={labelStyle}>Condition Value</span><input style={fieldStyle} value={wf.conditionValue} onChange={e=>setWf({...wf,conditionValue:e.target.value})}/></label><label><span style={labelStyle}>Action</span><input style={fieldStyle} value={wf.action} onChange={e=>setWf({...wf,action:e.target.value})}/></label><label><span style={labelStyle}>Owner Role</span><input style={fieldStyle} value={wf.ownerRole} onChange={e=>setWf({...wf,ownerRole:e.target.value})}/></label><label><span style={labelStyle}>Escalate After Minutes</span><input style={fieldStyle} value={wf.escalateAfterMinutes} onChange={e=>setWf({...wf,escalateAfterMinutes:e.target.value})}/></label></div><div style={{textAlign:'right',marginTop:10}}><button className="btn" onClick={()=>post('/governance/workflow-rules',wf,'Workflow rule saved.')}>Save Workflow</button></div></div>
      <div className="card"><h3 style={sectionTitle}>Notification Rule</h3><div style={formGrid}><label><span style={labelStyle}>Event Type</span><input style={fieldStyle} value={ntf.eventType} onChange={e=>setNtf({...ntf,eventType:e.target.value})}/></label><label><span style={labelStyle}>Channels</span><input style={fieldStyle} value={ntf.channels} onChange={e=>setNtf({...ntf,channels:e.target.value})}/></label><label><span style={labelStyle}>Recipients / Roles</span><input style={fieldStyle} value={ntf.recipients} onChange={e=>setNtf({...ntf,recipients:e.target.value})}/></label><label><span style={labelStyle}>Severity</span><input style={fieldStyle} value={ntf.severity} onChange={e=>setNtf({...ntf,severity:e.target.value})}/></label></div><div style={{textAlign:'right',marginTop:10}}><button className="btn" onClick={()=>post('/governance/notification-rules',{...ntf,channels:split(ntf.channels),recipients:split(ntf.recipients)},'Notification rule saved.')}>Save Notification</button></div></div>
    </div>

    <div className="card" style={{overflowX:'auto'}}><h3 style={sectionTitle}>Published Reference Data</h3><table className="table"><thead><tr><th>Category</th><th>Key</th><th>Label</th><th>Value</th><th>Version</th><th>Status</th></tr></thead><tbody>{(data.referenceData||[]).map((x:any)=><tr key={x.referenceId}><td>{x.category}</td><td><b>{x.key}</b></td><td>{x.label}</td><td>{String(x.value??'-')}</td><td>{x.version||1}</td><td><span className="status">{x.active===false?'INACTIVE':'ACTIVE'}</span></td></tr>)}{!(data.referenceData||[]).length&&<tr><td colSpan={6}>No governed reference data published yet.</td></tr>}</tbody></table></div>
  </WorkspaceShell>;
}
