'use client';
import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,labelStyle,sectionTitle,formGrid} from '../../components/WorkspaceShell';
import {api,fmtDate,fmtMoney,requireToken} from '../../lib/api';

const thisPeriod=()=>new Date().toISOString().slice(0,7);

export default function GroupFinancePage(){
  const [token,setToken]=useState('');const [period,setPeriod]=useState(thisPeriod());const [groupCurrency,setGroupCurrency]=useState('USD');
  const [entities,setEntities]=useState<any[]>([]);const [rates,setRates]=useState<any[]>([]);const [ic,setIc]=useState<any[]>([]);const [report,setReport]=useState<any>(null);const [exceptions,setExceptions]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [entityForm,setEntityForm]=useState<any>({branchId:'',entityCode:'',entityName:'',localCurrency:'USD',groupCurrency:'USD',ownershipPct:100});
  const [fxForm,setFxForm]=useState<any>({fromCurrency:'USD',toCurrency:'EUR',rateType:'CLOSING',rate:''});
  const [icForm,setIcForm]=useState<any>({fromEntityId:'',toEntityId:'',amount:'',currency:'USD',description:'Intercompany service charge',transactionDate:new Date().toISOString().slice(0,10)});

  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t,thisPeriod(),'USD');},[]);
  async function load(t=token,p=period,g=groupCurrency){if(!t)return;setBusy(true);setMessage('');try{const [e,r,i,c,x]=await Promise.all([api('/group-finance/entities',t),api(`/group-finance/fx-rates?period=${encodeURIComponent(p)}`,t),api('/group-finance/intercompany',t),api(`/group-finance/consolidation?period=${encodeURIComponent(p)}&groupCurrency=${encodeURIComponent(g)}`,t),api(`/group-finance/exceptions?period=${encodeURIComponent(p)}&groupCurrency=${encodeURIComponent(g)}`,t)]);setEntities(Array.isArray(e)?e:[]);setRates(Array.isArray(r)?r:[]);setIc(Array.isArray(i)?i:[]);setReport(c||null);setExceptions(Array.isArray(x)?x:[]);if(!entityForm.branchId&&Array.isArray(e)&&e[0])setEntityForm((v:any)=>({...v,branchId:e[0].branchId,entityCode:e[0].entityCode,entityName:e[0].entityName,localCurrency:e[0].localCurrency||'USD',groupCurrency:e[0].groupCurrency||g,ownershipPct:e[0].ownershipPct||100}));}catch(err:any){setMessage(err.message||'Unable to load group finance.');}finally{setBusy(false);}}
  async function post(path:string,body:any,success:string){setBusy(true);setMessage('');try{await api(path,token,{method:'POST',body:JSON.stringify(body)});setMessage(success);await load(token,period,groupCurrency);}catch(err:any){setMessage(err.message||'Action failed.');}finally{setBusy(false);}}
  function selectEntity(id:string){const e=entities.find((x:any)=>x.branchId===id);if(!e)return;setEntityForm({branchId:id,entityCode:e.entityCode||e.branchCode,entityName:e.entityName||e.branchName,localCurrency:e.localCurrency||'USD',groupCurrency:e.groupCurrency||groupCurrency,ownershipPct:e.ownershipPct||100,active:e.active!==false});}
  const configured=entities.filter((e:any)=>e.configured&&e.active);const currentIc=ic.filter((x:any)=>x.period===period);

  return <WorkspaceShell title="Group Finance / Consolidation" subtitle="Entity configuration, FX translation, intercompany accounting, eliminations and management consolidation" active="/group-finance" actions={<button className="btn" disabled={busy} onClick={()=>void load()}>{busy?'Working…':'Refresh'}</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="card" style={{marginBottom:12}}><div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'end'}}><label><span style={labelStyle}>Period</span><input type="month" style={fieldStyle} value={period} onChange={e=>{setPeriod(e.target.value);void load(token,e.target.value,groupCurrency);}}/></label><label><span style={labelStyle}>Group Currency</span><input style={{...fieldStyle,width:100}} value={groupCurrency} maxLength={3} onChange={e=>setGroupCurrency(e.target.value.toUpperCase())}/></label><button className="btn" onClick={()=>void load(token,period,groupCurrency)}>Run Consolidation</button></div></div>

    <div className="grid" style={{marginBottom:12}}><div className="card"><div className="sub">REPORTING ENTITIES</div><div className="kpi">{configured.length}</div></div><div className="card"><div className="sub">FX RATES · PERIOD</div><div className="kpi">{rates.length}</div></div><div className="card"><div className="sub">DRAFT INTERCOMPANY</div><div className="kpi">{currentIc.filter((x:any)=>x.status!=='POSTED').length}</div></div><div className="card"><div className="sub">CONSOLIDATION EXCEPTIONS</div><div className="kpi">{exceptions.length}</div></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Reporting Entity Setup</h3><div style={formGrid}><label><span style={labelStyle}>Branch / Entity</span><select style={fieldStyle} value={entityForm.branchId} onChange={e=>selectEntity(e.target.value)}>{entities.map((e:any)=><option key={e.branchId} value={e.branchId}>{e.branchCode} · {e.branchName}</option>)}</select></label><label><span style={labelStyle}>Entity Code</span><input style={fieldStyle} value={entityForm.entityCode||''} onChange={e=>setEntityForm({...entityForm,entityCode:e.target.value})}/></label><label><span style={labelStyle}>Entity Name</span><input style={fieldStyle} value={entityForm.entityName||''} onChange={e=>setEntityForm({...entityForm,entityName:e.target.value})}/></label><label><span style={labelStyle}>Local Currency</span><input style={fieldStyle} maxLength={3} value={entityForm.localCurrency||''} onChange={e=>setEntityForm({...entityForm,localCurrency:e.target.value.toUpperCase()})}/></label><label><span style={labelStyle}>Group Currency</span><input style={fieldStyle} maxLength={3} value={entityForm.groupCurrency||''} onChange={e=>setEntityForm({...entityForm,groupCurrency:e.target.value.toUpperCase()})}/></label><label><span style={labelStyle}>Ownership %</span><input type="number" min="0.01" max="100" step="0.01" style={fieldStyle} value={entityForm.ownershipPct} onChange={e=>setEntityForm({...entityForm,ownershipPct:e.target.value})}/></label></div><div style={{marginTop:10}}><button className="btn" disabled={busy||!entityForm.branchId} onClick={()=>void post(`/group-finance/entities/${encodeURIComponent(entityForm.branchId)}`,entityForm,'Reporting entity saved.')}>Save Entity</button></div><div style={{overflowX:'auto',marginTop:12}}><table className="table"><thead><tr><th>Entity</th><th>Country</th><th>Local</th><th>Group</th><th>Ownership</th><th>Status</th></tr></thead><tbody>{entities.map((e:any)=><tr key={e.branchId}><td><b>{e.entityCode}</b><div className="sub">{e.entityName}</div></td><td>{e.countryCode}</td><td>{e.localCurrency||'-'}</td><td>{e.groupCurrency||'-'}</td><td>{e.ownershipPct}%</td><td><span className="status">{e.configured?'CONFIGURED':'SETUP REQUIRED'}</span></td></tr>)}</tbody></table></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>FX Translation Rates</h3><div style={formGrid}><label><span style={labelStyle}>From</span><input style={fieldStyle} maxLength={3} value={fxForm.fromCurrency} onChange={e=>setFxForm({...fxForm,fromCurrency:e.target.value.toUpperCase()})}/></label><label><span style={labelStyle}>To</span><input style={fieldStyle} maxLength={3} value={fxForm.toCurrency} onChange={e=>setFxForm({...fxForm,toCurrency:e.target.value.toUpperCase()})}/></label><label><span style={labelStyle}>Rate Type</span><select style={fieldStyle} value={fxForm.rateType} onChange={e=>setFxForm({...fxForm,rateType:e.target.value})}><option>AVERAGE</option><option>CLOSING</option></select></label><label><span style={labelStyle}>Rate</span><input type="number" step="0.000001" style={fieldStyle} value={fxForm.rate} onChange={e=>setFxForm({...fxForm,rate:e.target.value})}/></label></div><div style={{marginTop:10}}><button className="btn" disabled={busy} onClick={()=>void post('/group-finance/fx-rates',{...fxForm,period},'FX rate saved.')}>Save FX Rate</button></div><div style={{overflowX:'auto',marginTop:12}}><table className="table"><thead><tr><th>Pair</th><th>Type</th><th>Rate</th><th>Period</th><th>Updated</th></tr></thead><tbody>{rates.map((r:any)=><tr key={r.objectId}><td><b>{r.fromCurrency}/{r.toCurrency}</b></td><td>{r.rateType}</td><td>{r.rate}</td><td>{r.period}</td><td>{fmtDate(r.updatedAt)}</td></tr>)}{rates.length===0&&<tr><td colSpan={5}>No FX rates for {period}.</td></tr>}</tbody></table></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Intercompany Accounting</h3><div style={formGrid}><label><span style={labelStyle}>From Entity</span><select style={fieldStyle} value={icForm.fromEntityId} onChange={e=>setIcForm({...icForm,fromEntityId:e.target.value})}><option value="">Select…</option>{configured.map((e:any)=><option key={e.branchId} value={e.branchId}>{e.entityCode}</option>)}</select></label><label><span style={labelStyle}>To Entity</span><select style={fieldStyle} value={icForm.toEntityId} onChange={e=>setIcForm({...icForm,toEntityId:e.target.value})}><option value="">Select…</option>{configured.map((e:any)=><option key={e.branchId} value={e.branchId}>{e.entityCode}</option>)}</select></label><label><span style={labelStyle}>Amount</span><input type="number" step="0.01" style={fieldStyle} value={icForm.amount} onChange={e=>setIcForm({...icForm,amount:e.target.value})}/></label><label><span style={labelStyle}>Currency</span><input style={fieldStyle} maxLength={3} value={icForm.currency} onChange={e=>setIcForm({...icForm,currency:e.target.value.toUpperCase()})}/></label><label><span style={labelStyle}>Transaction Date</span><input type="date" style={fieldStyle} value={icForm.transactionDate} onChange={e=>setIcForm({...icForm,transactionDate:e.target.value})}/></label><label><span style={labelStyle}>Description</span><input style={fieldStyle} value={icForm.description} onChange={e=>setIcForm({...icForm,description:e.target.value})}/></label></div><div style={{marginTop:10}}><button className="btn" disabled={busy||!icForm.fromEntityId||!icForm.toEntityId||!icForm.amount} onClick={()=>void post('/group-finance/intercompany',icForm,'Intercompany transaction created.')}>Create Intercompany</button></div><div style={{overflowX:'auto',marginTop:12}}><table className="table"><thead><tr><th>Transaction</th><th>Entities</th><th>Date</th><th>Amount</th><th>Description</th><th>Status</th><th>Action</th></tr></thead><tbody>{currentIc.map((x:any)=><tr key={x.transactionNo}><td><b>{x.transactionNo}</b></td><td>{x.fromEntityCode} → {x.toEntityCode}</td><td>{fmtDate(x.transactionDate)}</td><td>{fmtMoney(x.amount,x.currency)}</td><td>{x.description}</td><td><span className="status">{x.status}</span></td><td>{x.status==='POSTED'?`${x.fromJournalNo} / ${x.toJournalNo}`:<button className="btn" disabled={busy} onClick={()=>void post(`/group-finance/intercompany/${encodeURIComponent(x.transactionNo)}/post`,{},'Intercompany journals posted.')}>Post Pair</button>}</td></tr>)}{currentIc.length===0&&<tr><td colSpan={7}>No intercompany transactions in {period}.</td></tr>}</tbody></table></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Consolidated Management P&amp;L / Balance Sheet</h3>{report&&<><div className="grid" style={{marginBottom:10}}><div className="card"><div className="sub">REVENUE</div><div className="kpi">{fmtMoney(report.consolidated?.revenue,report.groupCurrency)}</div></div><div className="card"><div className="sub">EXPENSES</div><div className="kpi">{fmtMoney(report.consolidated?.expenses,report.groupCurrency)}</div></div><div className="card"><div className="sub">NET PROFIT</div><div className="kpi">{fmtMoney(report.consolidated?.netProfit,report.groupCurrency)}</div></div><div className="card"><div className="sub">ASSETS</div><div className="kpi">{fmtMoney(report.consolidated?.assets,report.groupCurrency)}</div></div><div className="card"><div className="sub">LIABILITIES</div><div className="kpi">{fmtMoney(report.consolidated?.liabilities,report.groupCurrency)}</div></div><div className="card"><div className="sub">IC ELIMINATIONS</div><div className="kpi">{fmtMoney(report.eliminations?.revenue,report.groupCurrency)}</div></div></div><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Entity</th><th>Revenue</th><th>Expenses</th><th>Profit</th><th>Assets</th><th>Liabilities</th><th>Journals</th></tr></thead><tbody>{(report.entities||[]).map((e:any)=><tr key={e.entityId}><td><b>{e.entityCode}</b><div className="sub">{e.entityName}</div></td><td>{fmtMoney(e.revenue,report.groupCurrency)}</td><td>{fmtMoney(e.expenses,report.groupCurrency)}</td><td>{fmtMoney(e.netProfit,report.groupCurrency)}</td><td>{fmtMoney(e.assets,report.groupCurrency)}</td><td>{fmtMoney(e.liabilities,report.groupCurrency)}</td><td>{e.journalCount}</td></tr>)}</tbody></table></div></>}</div>

    <div className="card"><h3 style={sectionTitle}>Consolidation Exceptions</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Type</th><th>Reference</th><th>Issue</th></tr></thead><tbody>{exceptions.map((x:any,i:number)=><tr key={`${x.type}-${i}`}><td><span className="status">{x.type}</span></td><td>{x.journalNo||x.transactionNo||x.entityId||'-'}</td><td>{x.message}</td></tr>)}{exceptions.length===0&&<tr><td colSpan={3}>No consolidation exceptions for {period}.</td></tr>}</tbody></table></div></div>
  </WorkspaceShell>;
}
