'use client';

import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtMoney,requireToken} from '../../lib/api';

const nowPeriod=()=>new Date().toISOString().slice(0,7);
export default function VendorControlPage(){
  const [token,setToken]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [dashboard,setDashboard]=useState<any>({}),[margins,setMargins]=useState<any[]>([]),[vendors,setVendors]=useState<any[]>([]),[period,setPeriod]=useState(nowPeriod());
  const [selected,setSelected]=useState<any>(null),[profile,setProfile]=useState<any>({approvalStatus:'APPROVED',riskRating:'MEDIUM',preferred:false,maxSinglePO:'',complianceExpiry:'',insuranceExpiry:'',reviewDate:'',owner:'',notes:''});
  const [incident,setIncident]=useState<any>({severity:'MEDIUM',category:'SERVICE',description:'',status:'OPEN'});
  async function load(t=token,p=period){if(!t)return;setBusy(true);setMessage('');try{const [d,m,v]=await Promise.all([api('/vendor-control/dashboard',{token:t}),api(`/vendor-control/margin-leakage?period=${p}`,{token:t}),api('/vendor-control/vendors',{token:t})]);setDashboard(d);setMargins(m);setVendors(v);if(selected){const s=v.find((x:any)=>x.id===selected.id);if(s)setSelected(s);}}catch(e:any){setMessage(e.message||'Unable to load vendor control');}finally{setBusy(false);}}
  useEffect(()=>{const t=requireToken();if(t){setToken(t);load(t,period);}},[]);
  async function saveProfile(){if(!selected)return;setBusy(true);try{await api(`/vendor-control/vendors/${selected.id}/profile`,{token,method:'POST',body:profile});setMessage('Vendor governance profile saved.');await load();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
  async function addIncident(){if(!selected||!incident.description)return;setBusy(true);try{await api(`/vendor-control/vendors/${selected.id}/incidents`,{token,method:'POST',body:incident});setIncident({...incident,description:''});setMessage('Vendor incident recorded.');await load();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
  function choose(v:any){setSelected(v);setProfile({approvalStatus:v.approvalStatus||'APPROVED',riskRating:v.riskRating||'MEDIUM',preferred:Boolean(v.preferred),maxSinglePO:v.maxSinglePO??'',complianceExpiry:v.complianceExpiry?String(v.complianceExpiry).slice(0,10):'',insuranceExpiry:v.insuranceExpiry?String(v.insuranceExpiry).slice(0,10):'',reviewDate:v.reviewDate?String(v.reviewDate).slice(0,10):'',owner:v.owner||'',notes:v.notes||''});}
  const card=(label:string,value:any)=><div className="card"><div className="sub">{label}</div><div style={{fontSize:24,fontWeight:800}}>{value??0}</div></div>;
  return <WorkspaceShell title="Margin & Vendor Control" subtitle="Margin leakage, supplier SLA and governance" active="/vendor-control" actions={<button className="btn" disabled={busy} onClick={()=>load()}>Refresh</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:14}}>{card('Leakage jobs',dashboard.leakageJobs)}{card('Blocked vendors',dashboard.blockedVendors)}{card('High-risk vendors',dashboard.highRiskVendors)}{card('Open incidents',dashboard.openIncidents)}{card('Late deliveries',dashboard.lateDeliveries)}</div>
    <div className="card" style={{marginBottom:14}}><h3 style={sectionTitle}>Margin Leakage</h3><div style={{maxWidth:220,marginBottom:10}}><label style={labelStyle}>Booking period</label><input style={fieldStyle} type="month" value={period} onChange={e=>{setPeriod(e.target.value);load(token,e.target.value);}}/></div><div style={{overflowX:'auto'}}><table><thead><tr><th>Booking</th><th>Currency</th><th>Estimated Cost</th><th>PO / Forecast Cost</th><th>Leakage</th><th>Forecast GP</th><th>Margin</th><th>Risk</th></tr></thead><tbody>{margins.map((x:any)=><tr key={`${x.bookingId}-${x.currency}`}><td>{x.bookingNo}</td><td>{x.currency}</td><td>{fmtMoney(x.estimatedCost,x.currency)}</td><td>{fmtMoney(x.forecastCost,x.currency)}</td><td>{fmtMoney(x.leakage,x.currency)}</td><td>{fmtMoney(x.forecastGp,x.currency)}</td><td>{Number(x.marginPct||0).toFixed(1)}%</td><td>{x.risk}</td></tr>)}</tbody></table></div></div>
    <div className="card" style={{marginBottom:14}}><h3 style={sectionTitle}>Vendor Performance & Governance</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Vendor</th><th>Approval</th><th>Risk</th><th>POs</th><th>On-time %</th><th>Invoice Coverage</th><th>Incidents</th><th>Blocking</th></tr></thead><tbody>{vendors.map((v:any)=><tr key={v.id} onClick={()=>choose(v)} style={{cursor:'pointer',background:selected?.id===v.id?'#eef4f8':undefined}}><td>{v.name}</td><td>{v.approvalStatus}</td><td>{v.riskRating}</td><td>{v.poCount}</td><td>{v.onTimePct==null?'—':`${v.onTimePct}%`}</td><td>{v.invoiceCoveragePct}%</td><td>{v.openIncidents}</td><td>{v.blocking?'BLOCK':'CLEAR'}</td></tr>)}</tbody></table></div></div>
    {selected&&<><div className="card" style={{marginBottom:14}}><h3 style={sectionTitle}>Governance · {selected.name}</h3><div style={formGrid}><div><label style={labelStyle}>Approval</label><select style={fieldStyle} value={profile.approvalStatus} onChange={e=>setProfile({...profile,approvalStatus:e.target.value})}><option>APPROVED</option><option>CONDITIONAL</option><option>BLOCKED</option></select></div><div><label style={labelStyle}>Risk</label><select style={fieldStyle} value={profile.riskRating} onChange={e=>setProfile({...profile,riskRating:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>RESTRICTED</option></select></div><div><label style={labelStyle}>Maximum Single PO</label><input style={fieldStyle} value={profile.maxSinglePO} onChange={e=>setProfile({...profile,maxSinglePO:e.target.value})}/></div><div><label style={labelStyle}>Compliance Expiry</label><input style={fieldStyle} type="date" value={profile.complianceExpiry} onChange={e=>setProfile({...profile,complianceExpiry:e.target.value})}/></div><div><label style={labelStyle}>Insurance Expiry</label><input style={fieldStyle} type="date" value={profile.insuranceExpiry} onChange={e=>setProfile({...profile,insuranceExpiry:e.target.value})}/></div><div><label style={labelStyle}>Review Date</label><input style={fieldStyle} type="date" value={profile.reviewDate} onChange={e=>setProfile({...profile,reviewDate:e.target.value})}/></div><div><label style={labelStyle}>Owner</label><input style={fieldStyle} value={profile.owner} onChange={e=>setProfile({...profile,owner:e.target.value})}/></div><div><label style={labelStyle}>Preferred</label><input type="checkbox" checked={profile.preferred} onChange={e=>setProfile({...profile,preferred:e.target.checked})}/></div></div><div style={{marginTop:10}}><label style={labelStyle}>Notes</label><input style={fieldStyle} value={profile.notes} onChange={e=>setProfile({...profile,notes:e.target.value})}/></div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={saveProfile}>Save Governance</button></div>
    <div className="card"><h3 style={sectionTitle}>Record Vendor Incident</h3><div style={formGrid}><div><label style={labelStyle}>Severity</label><select style={fieldStyle} value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div><div><label style={labelStyle}>Category</label><input style={fieldStyle} value={incident.category} onChange={e=>setIncident({...incident,category:e.target.value})}/></div><div><label style={labelStyle}>Description</label><input style={fieldStyle} value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})}/></div></div><button className="btn" style={{marginTop:10}} disabled={busy||!incident.description} onClick={addIncident}>Record Incident</button></div></>}
  </WorkspaceShell>;
}
