import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SOURCE='ANCLINE_STATUTORY_FINANCE';
const GROUP_SOURCE='ANCLINE_GROUP_FINANCE';
const GL_SOURCE='ANCLINE_GL';

@Injectable()
export class StatutoryFinanceService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private get db():any{return this.prisma as any;}
  private access(user:ScopeUser){this.scope.assertFinanceAccess(user);}
  private payload(e:any){return (e?.payload||{}) as any;}
  private round(v:any){return Math.round((Number(v||0)+Number.EPSILON)*100)/100;}
  private req(v:any,n:string){const t=String(v??'').trim();if(!t)throw new BadRequestException(`${n} is required`);return t;}
  private period(v:any){const t=String(v||'');if(!/^\d{4}-\d{2}$/.test(t))throw new BadRequestException('Period must be YYYY-MM');return t;}
  private currency(v:any){const c=String(v||'USD').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(c))throw new BadRequestException('Currency must be a 3-letter code');return c;}
  private date(v:any,n:string){const d=new Date(v);if(Number.isNaN(d.getTime()))throw new BadRequestException(`${n} must be a valid date`);return d;}
  private previousPeriod(period:string){const [y,m]=period.split('-').map(Number);const d=new Date(Date.UTC(y,m-2,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
  private periodOf(value:any){const d=this.date(value,'Date');return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}

  private async periodState(period:string){
    const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GL_SOURCE,objectType:'FiscalPeriod',objectId:period},orderBy:{createdAt:'asc'}});
    const last=rows[rows.length-1];return last?{period,status:this.payload(last).status||'OPEN'}:{period,status:'OPEN'};
  }

  private async legalEntityMap(){
    const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:'LegalEntity',eventType:'LEGAL_ENTITY_SET'},orderBy:{createdAt:'asc'}});
    const map=new Map<string,any>();for(const row of rows)map.set(row.objectId,{entityId:row.objectId,...this.payload(row),updatedAt:row.createdAt});return map;
  }

  async legalEntities(user:ScopeUser){
    this.access(user);const [map,branches]=await Promise.all([this.legalEntityMap(),this.db.branch.findMany({orderBy:{code:'asc'}})]);const branchMap=new Map((branches as any[]).map((b:any)=>[b.id,b]));
    return Array.from(map.values()).map((e:any)=>({...e,branches:(e.branchIds||[]).map((id:string)=>branchMap.get(id)).filter(Boolean)})).sort((a:any,b:any)=>String(a.entityCode).localeCompare(String(b.entityCode)));
  }

  async branches(user:ScopeUser){
    this.access(user);const [branches,entities]=await Promise.all([this.db.branch.findMany({orderBy:{code:'asc'}}),this.legalEntityMap()]);const assignment=new Map<string,string>();
    for(const e of entities.values())if(e.active!==false)for(const branchId of e.branchIds||[])assignment.set(String(branchId),String(e.entityId));
    return (branches as any[]).map((b:any)=>({...b,legalEntityId:assignment.get(b.id)||null}));
  }

  async setLegalEntity(entityIdInput:string|undefined,body:any,user:ScopeUser){
    this.access(user);const entityCode=this.req(body?.entityCode,'Entity code').toUpperCase();const entityName=this.req(body?.entityName,'Entity name');const countryCode=this.req(body?.countryCode,'Country code').toUpperCase();const branchIds=[...new Set((Array.isArray(body?.branchIds)?body.branchIds:[]).map(String).filter(Boolean))];if(!branchIds.length)throw new BadRequestException('At least one branch must be assigned');
    const fiscalYearStartMonth=Number(body?.fiscalYearStartMonth||1);if(!Number.isInteger(fiscalYearStartMonth)||fiscalYearStartMonth<1||fiscalYearStartMonth>12)throw new BadRequestException('Fiscal year start month must be 1-12');
    const ownershipPct=body?.ownershipPct==null?100:Number(body.ownershipPct);if(!Number.isFinite(ownershipPct)||ownershipPct<=0||ownershipPct>100)throw new BadRequestException('Ownership % must be greater than 0 and at most 100');
    const branches:any[]=await this.db.branch.findMany({where:{id:{in:branchIds}}});if(branches.length!==branchIds.length)throw new BadRequestException('One or more branches do not exist');
    const entities=await this.legalEntityMap();const entityId=String(entityIdInput||`LE-${entityCode.replace(/[^A-Z0-9]/g,'')}`).toUpperCase();
    for(const e of entities.values()){if(e.entityId!==entityId&&e.active!==false&&String(e.entityCode).toUpperCase()===entityCode)throw new BadRequestException(`Entity code ${entityCode} already exists`);if(e.entityId!==entityId&&e.active!==false&&(e.branchIds||[]).some((id:string)=>branchIds.includes(String(id))))throw new BadRequestException(`A selected branch is already assigned to ${e.entityCode}`);}
    const payload={entityId,entityCode,entityName,countryCode,registrationNo:body?.registrationNo?String(body.registrationNo):null,taxRegistrationNo:body?.taxRegistrationNo?String(body.taxRegistrationNo):null,localCurrency:this.currency(body?.localCurrency||'USD'),groupCurrency:this.currency(body?.groupCurrency||'USD'),fiscalYearStartMonth,ownershipPct:this.round(ownershipPct),branchIds,active:body?.active!==false,notes:body?.notes?String(body.notes):null,updatedBy:user.sub};
    await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'LEGAL_ENTITY_SET',externalId:entityId,objectType:'LegalEntity',objectId:entityId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:user.sub,action:'LEGAL_ENTITY_SET',objectType:'LegalEntity',objectId:entityId,detail:payload});return payload;
  }

  private async fxMap(period?:string){
    const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GROUP_SOURCE,objectType:'FXRate'},orderBy:{createdAt:'asc'}});const map=new Map<string,any>();for(const row of rows){const p=this.payload(row);if(!period||p.period===period)map.set(row.objectId,{...p,updatedAt:row.createdAt});}return map;
  }
  private rateFor(period:string,from:string,to:string,rateType:string,map:Map<string,any>){if(from===to)return 1;const direct=map.get(`${period}:${from}:${to}:${rateType}`);if(direct&&Number(direct.rate)>0)return Number(direct.rate);const inverse=map.get(`${period}:${to}:${from}:${rateType}`);if(inverse&&Number(inverse.rate)>0)return 1/Number(inverse.rate);return null;}

  private buildJournal(rows:any[]){const created=rows.find((e:any)=>e.eventType==='JOURNAL_CREATED');if(!created)return null;const posted=rows.find((e:any)=>e.eventType==='JOURNAL_POSTED');const reversed=rows.find((e:any)=>e.eventType==='JOURNAL_REVERSED');return {...this.payload(created),journalNo:created.objectId,status:reversed?'REVERSED':posted?'POSTED':'DRAFT',createdAt:created.createdAt,postedAt:posted?.createdAt||null};}
  private async journalsRaw(){const events:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GL_SOURCE,objectType:'JournalEntry'},orderBy:{createdAt:'asc'}});const grouped=new Map<string,any[]>();for(const e of events){if(!grouped.has(e.objectId))grouped.set(e.objectId,[]);grouped.get(e.objectId)!.push(e);}return Array.from(grouped.values()).map((rows:any[])=>this.buildJournal(rows)).filter((x:any)=>Boolean(x)) as any[];}
  private async postJournalDirect(input:any,user:ScopeUser){
    const period=this.periodOf(input.journalDate);const state=await this.periodState(period);if(state.status==='CLOSED')throw new BadRequestException(`Period ${period} is closed`);const lines=(input.lines||[]).map((l:any)=>({...l,debit:this.round(l.debit),credit:this.round(l.credit)}));const totalDebit=this.round(lines.reduce((s:number,l:any)=>s+Number(l.debit||0),0)),totalCredit=this.round(lines.reduce((s:number,l:any)=>s+Number(l.credit||0),0));if(Math.abs(totalDebit-totalCredit)>0.005)throw new BadRequestException('Generated journal is not balanced');
    const existing=(await this.journalsRaw()).find((j:any)=>j.reference===input.reference);if(existing)return existing;const journalNo=String(input.journalNo||`${input.prefix||'ST'}-${period.replace('-','')}-${Date.now().toString().slice(-7)}`).toUpperCase();const payload={journalNo,journalDate:new Date(input.journalDate).toISOString(),period,currency:this.currency(input.currency),description:input.description||null,reference:input.reference,source:input.source||'STATUTORY_FINANCE',entityId:input.entityId||null,legalEntityId:input.legalEntityId||null,lines,totalDebit,totalCredit};
    await this.db.$transaction([this.db.integrationEvent.create({data:{sourceSystem:GL_SOURCE,eventType:'JOURNAL_CREATED',externalId:journalNo,objectType:'JournalEntry',objectId:journalNo,status:'COMPLETED',payload,completedAt:new Date()}}),this.db.integrationEvent.create({data:{sourceSystem:GL_SOURCE,eventType:'JOURNAL_POSTED',externalId:journalNo,objectType:'JournalEntry',objectId:journalNo,status:'COMPLETED',payload:{journalNo,postedBy:user.sub,sourceReference:input.reference},completedAt:new Date()}})]);return {...payload,status:'POSTED'};
  }

  private async exposureMap(period?:string){
    const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:'FXExposure'},orderBy:{createdAt:'asc'}});const exposures=new Map<string,any>(),posts=new Map<string,any>();
    for(const row of rows){const p=this.payload(row);if(row.eventType==='FX_EXPOSURE_SET'&&(!period||p.period===period))exposures.set(row.objectId,{exposureId:row.objectId,...p,updatedAt:row.createdAt});if(row.eventType==='FX_REVALUATION_POSTED')posts.set(row.objectId,{...p,postedAt:row.createdAt});}
    for(const [id,e] of exposures){const post=posts.get(id);e.revaluation=post&&new Date(post.postedAt).getTime()>=new Date(e.updatedAt).getTime()?post:null;}return exposures;
  }

  async exposures(period:string|undefined,user:ScopeUser){this.access(user);return Array.from((await this.exposureMap(period)).values()).sort((a:any,b:any)=>String(a.exposureId).localeCompare(String(b.exposureId)));}
  async setExposure(body:any,user:ScopeUser){
    this.access(user);const entities=await this.legalEntityMap();const legalEntityId=this.req(body?.legalEntityId,'Legal entity');const entity=entities.get(legalEntityId);if(!entity||entity.active===false)throw new BadRequestException('Legal entity is not configured or inactive');const period=this.period(body?.period);const foreignCurrency=this.currency(body?.foreignCurrency);if(foreignCurrency===entity.localCurrency)throw new BadRequestException('Foreign currency must differ from local currency');const foreignAmount=Number(body?.foreignAmount),carryingAmountLocal=Number(body?.carryingAmountLocal);if(!Number.isFinite(foreignAmount)||foreignAmount<0)throw new BadRequestException('Foreign amount must be zero or greater');if(!Number.isFinite(carryingAmountLocal)||carryingAmountLocal<0)throw new BadRequestException('Carrying amount must be zero or greater');const monetaryType=String(body?.monetaryType||'ASSET').toUpperCase();if(!['ASSET','LIABILITY'].includes(monetaryType))throw new BadRequestException('Monetary type must be ASSET or LIABILITY');
    const exposureId=String(body?.exposureId||`FXE-${period.replace('-','')}-${Date.now().toString().slice(-7)}`).toUpperCase();const payload={exposureId,period,legalEntityId,entityCode:entity.entityCode,account:this.req(body?.account,'Account').toUpperCase(),description:body?.description?String(body.description):null,reference:body?.reference?String(body.reference):null,monetaryType,foreignCurrency,localCurrency:entity.localCurrency,foreignAmount:this.round(foreignAmount),carryingAmountLocal:this.round(carryingAmountLocal),updatedBy:user.sub};
    await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'FX_EXPOSURE_SET',externalId:exposureId,objectType:'FXExposure',objectId:exposureId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:user.sub,action:'FX_EXPOSURE_SET',objectType:'FXExposure',objectId:exposureId,detail:payload});return payload;
  }

  async revaluationPreview(periodInput:string,user:ScopeUser){
    this.access(user);const period=this.period(periodInput);const [exposures,fx]=await Promise.all([this.exposureMap(period),this.fxMap(period)]);return Array.from(exposures.values()).map((e:any)=>{const closingRate=this.rateFor(period,e.foreignCurrency,e.localCurrency,'CLOSING',fx);const targetLocal=closingRate==null?null:this.round(e.foreignAmount*closingRate);const adjustment=targetLocal==null?null:this.round(targetLocal-e.carryingAmountLocal);return {...e,closingRate,targetLocal,adjustment,status:e.revaluation?'POSTED':closingRate==null?'RATE_MISSING':'PENDING'};});
  }

  async postRevaluation(exposureId:string,user:ScopeUser){
    this.access(user);const all=await this.exposureMap();const e=all.get(exposureId);if(!e)throw new NotFoundException('FX exposure not found');const fx=await this.fxMap(e.period);const rate=this.rateFor(e.period,e.foreignCurrency,e.localCurrency,'CLOSING',fx);if(rate==null)throw new BadRequestException('Closing FX rate is missing');const target=this.round(e.foreignAmount*rate),adjustment=this.round(target-e.carryingAmountLocal);const reference=`FXRV:${exposureId}:${new Date(e.updatedAt).getTime()}`;let journal:any=null;
    if(Math.abs(adjustment)>0.005){const amt=Math.abs(adjustment),asset=e.monetaryType==='ASSET';let lines:any[];if(asset&&adjustment>0)lines=[{account:e.account,description:`FX revaluation ${exposureId}`,debit:amt,credit:0,entityId:e.legalEntityId},{account:'7800-FX-GAIN-LOSS',description:`FX gain ${exposureId}`,debit:0,credit:amt,entityId:e.legalEntityId}];else if(asset)lines=[{account:'7800-FX-GAIN-LOSS',description:`FX loss ${exposureId}`,debit:amt,credit:0,entityId:e.legalEntityId},{account:e.account,description:`FX revaluation ${exposureId}`,debit:0,credit:amt,entityId:e.legalEntityId}];else if(adjustment>0)lines=[{account:'7800-FX-GAIN-LOSS',description:`FX loss ${exposureId}`,debit:amt,credit:0,entityId:e.legalEntityId},{account:e.account,description:`FX revaluation ${exposureId}`,debit:0,credit:amt,entityId:e.legalEntityId}];else lines=[{account:e.account,description:`FX revaluation ${exposureId}`,debit:amt,credit:0,entityId:e.legalEntityId},{account:'7800-FX-GAIN-LOSS',description:`FX gain ${exposureId}`,debit:0,credit:amt,entityId:e.legalEntityId}];journal=await this.postJournalDirect({journalDate:`${e.period}-28T12:00:00.000Z`,currency:e.localCurrency,reference,description:`FX revaluation ${exposureId}`,source:'FX_REVALUATION',prefix:'FX',entityId:e.legalEntityId,legalEntityId:e.legalEntityId,lines},user);}
    const payload={exposureId,period:e.period,closingRate:rate,targetLocal:target,adjustment,journalNo:journal?.journalNo||null,postedBy:user.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'FX_REVALUATION_POSTED',externalId:exposureId,objectType:'FXExposure',objectId:exposureId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:user.sub,action:'FX_REVALUATION_POST',objectType:'FXExposure',objectId:exposureId,detail:payload});return payload;
  }

  private async groupIntercompanyRows(){
    const events:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GROUP_SOURCE,objectType:'IntercompanyTransaction'},orderBy:{createdAt:'asc'}});const grouped=new Map<string,any[]>();for(const e of events){if(!grouped.has(e.objectId))grouped.set(e.objectId,[]);grouped.get(e.objectId)!.push(e);}return Array.from(grouped.values()).map((rows:any[])=>{const created=rows.find((e:any)=>e.eventType==='INTERCOMPANY_CREATED');if(!created)return null;const posted=rows.find((e:any)=>e.eventType==='INTERCOMPANY_POSTED');return {...this.payload(created),transactionNo:created.objectId,status:posted?'POSTED':'DRAFT',postedAt:posted?.createdAt||null};}).filter((x:any)=>Boolean(x)) as any[];
  }
  private async settlementRows(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:'IntercompanySettlement',eventType:'INTERCOMPANY_SETTLEMENT_RECORDED'},orderBy:{createdAt:'asc'}});return rows.map((r:any)=>({settlementId:r.objectId,...this.payload(r),createdAt:r.createdAt}));}
  async intercompanyReconciliation(periodInput:string|undefined,user:ScopeUser){
    this.access(user);const [transactions,settlements]=await Promise.all([this.groupIntercompanyRows(),this.settlementRows()]);const period=periodInput?this.period(periodInput):undefined;return transactions.filter((tx:any)=>tx.status==='POSTED'&&(!period||tx.period===period)).map((tx:any)=>{const rows=settlements.filter((s:any)=>s.transactionNo===tx.transactionNo);const settledAmount=this.round(rows.reduce((s:number,r:any)=>s+Number(r.amount||0),0));const remainingAmount=this.round(Math.max(0,Number(tx.amount||0)-settledAmount));return {...tx,settledAmount,remainingAmount,settlementCount:rows.length,reconciliationStatus:remainingAmount<=0.005?'SETTLED':settledAmount>0?'PART_SETTLED':'OPEN',settlements:rows};}).sort((a:any,b:any)=>String(a.transactionNo).localeCompare(String(b.transactionNo)));
  }

  async recordSettlement(transactionNo:string,body:any,user:ScopeUser){
    this.access(user);const tx=(await this.groupIntercompanyRows()).find((x:any)=>x.transactionNo===transactionNo);if(!tx)throw new NotFoundException('Intercompany transaction not found');if(tx.status!=='POSTED')throw new BadRequestException('Intercompany transaction must be posted first');const reconciliation=(await this.intercompanyReconciliation(undefined,user)).find((x:any)=>x.transactionNo===transactionNo);const amount=this.round(body?.amount);if(!Number.isFinite(amount)||amount<=0)throw new BadRequestException('Settlement amount must be greater than zero');if(amount>Number(reconciliation?.remainingAmount||0)+0.005)throw new BadRequestException('Settlement exceeds remaining intercompany balance');const settlementDate=this.date(body?.settlementDate||new Date(),'Settlement date');const period=this.periodOf(settlementDate);const state=await this.periodState(period);if(state.status==='CLOSED')throw new BadRequestException(`Period ${period} is closed`);const settlementId=String(body?.settlementId||`ICS-${period.replace('-','')}-${Date.now().toString().slice(-7)}`).toUpperCase();const duplicate=await this.db.integrationEvent.findFirst({where:{sourceSystem:SOURCE,objectType:'IntercompanySettlement',objectId:settlementId}});if(duplicate)throw new BadRequestException(`Settlement ${settlementId} already exists`);
    const fromJournalNo=`ICR-${Date.now().toString().slice(-8)}`,toJournalNo=`ICP-${Date.now().toString().slice(-8)}`;const currency=this.currency(tx.currency);const fromRef=`ICSET:${settlementId}:FROM`,toRef=`ICSET:${settlementId}:TO`;const fromLines=[{account:'1000-BANK',description:`IC settlement ${transactionNo}`,debit:amount,credit:0,entityId:tx.fromEntityId},{account:tx.receivableAccount||'1310-INTERCOMPANY-RECEIVABLE',description:`Settle ${transactionNo}`,debit:0,credit:amount,entityId:tx.fromEntityId}];const toLines=[{account:tx.payableAccount||'2310-INTERCOMPANY-PAYABLE',description:`Settle ${transactionNo}`,debit:amount,credit:0,entityId:tx.toEntityId},{account:'1000-BANK',description:`IC settlement ${transactionNo}`,debit:0,credit:amount,entityId:tx.toEntityId}];const now=new Date();const fromPayload={journalNo:fromJournalNo,journalDate:settlementDate.toISOString(),period,currency,description:`Intercompany settlement receipt ${transactionNo}`,reference:fromRef,source:'INTERCOMPANY_SETTLEMENT',entityId:tx.fromEntityId,lines:fromLines,totalDebit:amount,totalCredit:amount};const toPayload={journalNo:toJournalNo,journalDate:settlementDate.toISOString(),period,currency,description:`Intercompany settlement payment ${transactionNo}`,reference:toRef,source:'INTERCOMPANY_SETTLEMENT',entityId:tx.toEntityId,lines:toLines,totalDebit:amount,totalCredit:amount};const settlementPayload={settlementId,transactionNo,settlementDate:settlementDate.toISOString(),period,amount,currency,bankReference:body?.bankReference?String(body.bankReference):null,fromJournalNo,toJournalNo,recordedBy:user.sub};
    await this.db.$transaction([this.db.integrationEvent.create({data:{sourceSystem:GL_SOURCE,eventType:'JOURNAL_CREATED',externalId:fromJournalNo,objectType:'JournalEntry',objectId:fromJournalNo,status:'COMPLETED',payload:fromPayload,completedAt:now}}),this.db.integrationEvent.create({data:{sourceSystem:GL_SOURCE,eventType:'JOURNAL_POSTED',externalId:fromJournalNo,objectType:'JournalEntry',objectId:fromJournalNo,status:'COMPLETED',payload:{journalNo:fromJournalNo,postedBy:user.sub,sourceReference:fromRef},completedAt:now}}),this.db.integrationEvent.create({data:{sourceSystem:GL_SOURCE,eventType:'JOURNAL_CREATED',externalId:toJournalNo,objectType:'JournalEntry',objectId:toJournalNo,status:'COMPLETED',payload:toPayload,completedAt:now}}),this.db.integrationEvent.create({data:{sourceSystem:GL_SOURCE,eventType:'JOURNAL_POSTED',externalId:toJournalNo,objectType:'JournalEntry',objectId:toJournalNo,status:'COMPLETED',payload:{journalNo:toJournalNo,postedBy:user.sub,sourceReference:toRef},completedAt:now}}),this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'INTERCOMPANY_SETTLEMENT_RECORDED',externalId:settlementId,objectType:'IntercompanySettlement',objectId:settlementId,status:'COMPLETED',payload:settlementPayload,completedAt:now}})]);await this.audit.log({actorId:user.sub,action:'INTERCOMPANY_SETTLEMENT_RECORD',objectType:'IntercompanySettlement',objectId:settlementId,detail:settlementPayload});return settlementPayload;
  }

  private isCashAccount(account:any){const a=String(account||'').toUpperCase();return a.startsWith('1000')||a.includes('BANK')||a.includes('CASH');}
  private cashClass(lines:any[]){const accounts=lines.map((l:any)=>String(l.account||'').toUpperCase()).filter((a:string)=>!this.isCashAccount(a));if(accounts.some((a:string)=>/^(15|16|17)/.test(a)||a.includes('FIXED')||a.includes('CAPEX')))return 'INVESTING';if(accounts.some((a:string)=>/^(25|26|27|28|29|3)/.test(a)||a.includes('LOAN')||a.includes('EQUITY')||a.includes('CAPITAL')||a.includes('DIVIDEND')))return 'FINANCING';return 'OPERATING';}
  private async entityResolution(){const entities=await this.legalEntityMap();const branchToEntity=new Map<string,string>();for(const e of entities.values())if(e.active!==false)for(const branchId of e.branchIds||[])branchToEntity.set(String(branchId),String(e.entityId));return {entities,branchToEntity};}
  private resolveLegalEntity(journal:any,branchToEntity:Map<string,string>,bookingMap:Map<string,string|null>,entities:Map<string,any>):string|null{
    const explicit=[journal.legalEntityId,journal.entityId,...(journal.lines||[]).map((l:any)=>l.legalEntityId||l.entityId)].filter(Boolean).map(String);const resolved=new Set<string>();for(const id of explicit){if(entities.has(id))resolved.add(id);else if(branchToEntity.has(id))resolved.add(String(branchToEntity.get(id)));}for(const line of journal.lines||[]){if(line.bookingId){const branchId=bookingMap.get(String(line.bookingId));if(branchId&&branchToEntity.has(branchId))resolved.add(String(branchToEntity.get(branchId)));}}return resolved.size===1?Array.from(resolved)[0]:null;
  }

  async cashFlow(periodInput:string,groupCurrencyInput:string|undefined,user:ScopeUser){
    this.access(user);const period=this.period(periodInput),previous=this.previousPeriod(period),groupCurrency=this.currency(groupCurrencyInput||'USD');const [journals,fxCurrent,fxPrevious,resolution]=await Promise.all([this.journalsRaw(),this.fxMap(period),this.fxMap(previous),this.entityResolution()]);const posted=journals.filter((j:any)=>j.status==='POSTED'&&String(j.period)<=period);const bookingIds=[...new Set(posted.flatMap((j:any)=>(j.lines||[]).map((l:any)=>l.bookingId).filter(Boolean).map(String)))];const bookings:any[]=bookingIds.length?await this.db.booking.findMany({where:{id:{in:bookingIds}},select:{id:true,owningBranchId:true}}):[];const bookingMap=new Map<string,string|null>();for(const b of bookings)bookingMap.set(String(b.id),b.owningBranchId||null);const buckets=new Map<string,any>();const exceptions:any[]=[];
    const ensure=(entityId:string)=>{if(!buckets.has(entityId)){const e=resolution.entities.get(entityId)||{};buckets.set(entityId,{legalEntityId:entityId,entityCode:e.entityCode||entityId,entityName:e.entityName||entityId,operating:0,investing:0,financing:0,openingByCurrency:new Map<string,number>(),closingByCurrency:new Map<string,number>()});}return buckets.get(entityId);};
    for(const journal of posted){const entityId=this.resolveLegalEntity(journal,resolution.branchToEntity,bookingMap,resolution.entities);if(!entityId)continue;const bucket=ensure(entityId);const cashLines=(journal.lines||[]).filter((l:any)=>this.isCashAccount(l.account));if(!cashLines.length)continue;const cashNet=this.round(cashLines.reduce((s:number,l:any)=>s+Number(l.debit||0)-Number(l.credit||0),0));if(!cashNet)continue;const ccy=this.currency(journal.currency);bucket.closingByCurrency.set(ccy,this.round((bucket.closingByCurrency.get(ccy)||0)+cashNet));if(String(journal.period)<period)bucket.openingByCurrency.set(ccy,this.round((bucket.openingByCurrency.get(ccy)||0)+cashNet));if(String(journal.period)===period){const rate=this.rateFor(period,ccy,groupCurrency,'AVERAGE',fxCurrent);if(rate==null){exceptions.push({type:'FX_RATE_MISSING',journalNo:journal.journalNo,fromCurrency:ccy,toCurrency:groupCurrency,rateType:'AVERAGE'});continue;}const translated=this.round(cashNet*rate);const cls=this.cashClass(journal.lines||[]);bucket[cls.toLowerCase()]=this.round(bucket[cls.toLowerCase()]+translated);}}
    const perEntity:any[]=[];for(const bucket of buckets.values()){let openingCash=0,closingCash=0;for(const [ccy,amount] of bucket.openingByCurrency.entries()){const rate=this.rateFor(previous,ccy,groupCurrency,'CLOSING',fxPrevious);if(rate==null){exceptions.push({type:'FX_RATE_MISSING',legalEntityId:bucket.legalEntityId,fromCurrency:ccy,toCurrency:groupCurrency,rateType:'PREVIOUS_CLOSING'});continue;}openingCash=this.round(openingCash+Number(amount)*rate);}for(const [ccy,amount] of bucket.closingByCurrency.entries()){const rate=this.rateFor(period,ccy,groupCurrency,'CLOSING',fxCurrent);if(rate==null){exceptions.push({type:'FX_RATE_MISSING',legalEntityId:bucket.legalEntityId,fromCurrency:ccy,toCurrency:groupCurrency,rateType:'CLOSING'});continue;}closingCash=this.round(closingCash+Number(amount)*rate);}const netBeforeFx=this.round(bucket.operating+bucket.investing+bucket.financing),fxEffect=this.round(closingCash-openingCash-netBeforeFx);perEntity.push({legalEntityId:bucket.legalEntityId,entityCode:bucket.entityCode,entityName:bucket.entityName,operating:bucket.operating,investing:bucket.investing,financing:bucket.financing,netBeforeFx,fxEffect,openingCash,closingCash});}
    const total={operating:this.round(perEntity.reduce((s:number,e:any)=>s+e.operating,0)),investing:this.round(perEntity.reduce((s:number,e:any)=>s+e.investing,0)),financing:this.round(perEntity.reduce((s:number,e:any)=>s+e.financing,0)),netBeforeFx:this.round(perEntity.reduce((s:number,e:any)=>s+e.netBeforeFx,0)),fxEffect:this.round(perEntity.reduce((s:number,e:any)=>s+e.fxEffect,0)),openingCash:this.round(perEntity.reduce((s:number,e:any)=>s+e.openingCash,0)),closingCash:this.round(perEntity.reduce((s:number,e:any)=>s+e.closingCash,0))};return {period,previousPeriod:previous,groupCurrency,total,perEntity,exceptions};
  }

  private async closeState(entityId:string,period:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:'EntityClose',objectId:`${entityId}:${period}`},orderBy:{createdAt:'asc'}});const last=rows[rows.length-1];return last?{entityId,period,status:this.payload(last).status||'OPEN',note:this.payload(last).note||null,updatedAt:last.createdAt,updatedBy:this.payload(last).updatedBy||null}:{entityId,period,status:'OPEN',note:null,updatedAt:null,updatedBy:null};}
  async closeReadiness(entityId:string,periodInput:string,user:ScopeUser){
    this.access(user);const period=this.period(periodInput);const entities=await this.legalEntityMap();const entity=entities.get(entityId);if(!entity)throw new NotFoundException('Legal entity not found');const [globalPeriod,preview,journals,resolution,ic]=await Promise.all([this.periodState(period),this.revaluationPreview(period,user),this.journalsRaw(),this.entityResolution(),this.intercompanyReconciliation(period,user)]);const bookingIds=[...new Set(journals.flatMap((j:any)=>(j.lines||[]).map((l:any)=>l.bookingId).filter(Boolean).map(String)))];const bookings:any[]=bookingIds.length?await this.db.booking.findMany({where:{id:{in:bookingIds}},select:{id:true,owningBranchId:true}}):[];const bookingMap=new Map<string,string|null>();for(const b of bookings)bookingMap.set(String(b.id),b.owningBranchId||null);const blockers:any[]=[];if(globalPeriod.status!=='CLOSED')blockers.push({type:'GLOBAL_PERIOD_OPEN',message:`Global GL period ${period} is ${globalPeriod.status}`});const pendingFx=preview.filter((x:any)=>x.legalEntityId===entityId&&x.status!=='POSTED');for(const x of pendingFx)blockers.push({type:x.status==='RATE_MISSING'?'FX_RATE_MISSING':'FX_REVALUATION_PENDING',objectId:x.exposureId,message:`FX exposure ${x.exposureId} is ${x.status.toLowerCase()}`});const drafts=journals.filter((j:any)=>j.period===period&&j.status==='DRAFT'&&this.resolveLegalEntity(j,resolution.branchToEntity,bookingMap,resolution.entities)===entityId);for(const j of drafts)blockers.push({type:'DRAFT_JOURNAL',objectId:j.journalNo,message:`Journal ${j.journalNo} is still draft`});const draftIc=ic.filter((x:any)=>x.status==='DRAFT'&&(resolution.branchToEntity.get(String(x.fromEntityId))===entityId||resolution.branchToEntity.get(String(x.toEntityId))===entityId));for(const x of draftIc)blockers.push({type:'INTERCOMPANY_UNPOSTED',objectId:x.transactionNo,message:`Intercompany transaction ${x.transactionNo} is not posted`});return {entityId,entityCode:entity.entityCode,period,globalPeriodStatus:globalPeriod.status,ready:blockers.length===0,blockers};
  }
  async closes(periodInput:string,user:ScopeUser){this.access(user);const period=this.period(periodInput);const entities=Array.from((await this.legalEntityMap()).values()).filter((e:any)=>e.active!==false);const out:any[]=[];for(const e of entities){const [state,readiness]=await Promise.all([this.closeState(e.entityId,period),this.closeReadiness(e.entityId,period,user)]);out.push({...state,entityCode:e.entityCode,entityName:e.entityName,ready:readiness.ready,blockers:readiness.blockers});}return out;}
  async setClose(entityId:string,periodInput:string,body:any,user:ScopeUser){this.access(user);const period=this.period(periodInput);const entities=await this.legalEntityMap();if(!entities.has(entityId))throw new NotFoundException('Legal entity not found');const status=String(body?.status||'OPEN').toUpperCase();if(!['OPEN','REVIEW','CERTIFIED'].includes(status))throw new BadRequestException('Close status must be OPEN, REVIEW or CERTIFIED');if(status==='CERTIFIED'){const readiness=await this.closeReadiness(entityId,period,user);if(!readiness.ready)throw new BadRequestException(`Entity close has ${readiness.blockers.length} blocker(s)`);}const objectId=`${entityId}:${period}`;const payload={entityId,period,status,note:body?.note?String(body.note):null,updatedBy:user.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'ENTITY_CLOSE_STATUS_SET',externalId:objectId,objectType:'EntityClose',objectId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:user.sub,action:'ENTITY_CLOSE_STATUS_SET',objectType:'EntityClose',objectId,detail:payload});return this.closeState(entityId,period);}

  async dashboard(periodInput:string,groupCurrencyInput:string|undefined,user:ScopeUser){this.access(user);const period=this.period(periodInput);const [entities,preview,ic,cash,closes]=await Promise.all([this.legalEntities(user),this.revaluationPreview(period,user),this.intercompanyReconciliation(period,user),this.cashFlow(period,groupCurrencyInput,user),this.closes(period,user)]);return {period,groupCurrency:cash.groupCurrency,legalEntityCount:entities.filter((e:any)=>e.active!==false).length,pendingRevaluations:preview.filter((x:any)=>x.status!=='POSTED').length,openIntercompany:ic.filter((x:any)=>x.reconciliationStatus!=='SETTLED').length,certifiedEntities:closes.filter((x:any)=>x.status==='CERTIFIED').length,closeReadyEntities:closes.filter((x:any)=>x.ready).length,closingCash:cash.total.closingCash,cashFlowExceptions:cash.exceptions.length};}
}
