'use client';

import {useEffect,useMemo,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

type Booking={id:string;bookingNo:string;origin:string;destination:string;customer?:{name:string}};
type Case={id:string;caseId:string;objectId:string;status:string;externalId?:string|null;payload:any;booking?:Booking|null;updatedAt:string};
const blank={bookingId:'',declarationNo:'',customsOffice:'',brokerName:'',brokerReference:'',clearanceType:'IMPORT',entryType:'STANDARD',commoditySummary:'',hsCode:'',dutyAmount:'',taxAmount:'',otherCharges:'',currency:'USD',inspectionLocation:'',holdReason:'',remarks:''};
const statuses=['DRAFT','SUBMITTED','UNDER_REVIEW','INSPECTION','ON_HOLD','DUTY_PENDING','CLEARED','RELEASED','CANCELLED'];

export default function CustomsPage(){
  const [token,setToken]=useState('');const [cases,setCases]=useState<Case[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [form,setForm]=useState(blank);const [showForm,setShowForm]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [search,setSearch]=useState('');const [filter,setFilter]=useState('ALL');
  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
  async function load(t=token){try{const [c,b]=await Promise.all([api('/customs',t),api('/bookings',t)]);setCases(Array.isArray(c)?c:[]);setBookings(Array.isArray(b)?b:[]);}catch(e:any){setMessage(e?.message||'Unable to load customs clearance data');}}
  function set(k:keyof typeof blank,v:string){setForm(x=>({...x,[k]:v}));}
  async function create(){if(!form.bookingId){setMessage('Booking is required.');return;}setBusy(true);setMessage('');try{await api('/customs',token,{method:'POST',body:JSON.stringify({...form,dutyAmount:form.dutyAmount||null,taxAmount:form.taxAmount||null,otherCharges:form.otherCharges||null})});setForm(blank);setShowForm(false);setMessage('Customs clearance case created.');await load();}catch(e:any){setMessage(e?.message||'Could not create customs case');}finally{setBusy(false);}}
  async function transition(id:string,status:string){if(status==='CANCELLED'&&!confirm('Cancel this customs case?'))return;setBusy(true);setMessage('');try{await api(`/customs/${id}/status/${status}`,token,{method:'POST'});setMessage(`Customs case moved to ${status}.`);await load();}catch(e:any){setMessage(e?.message||'Could not update customs case');}finally{setBusy(false);}}
  const visible=useMemo(()=>{const q=search.trim().toLowerCase();return cases.filter(c=>(filter==='ALL'||c.status===filter)&&(!q||[c.externalId,c.booking?.bookingNo,c.booking?.customer?.name,c.payload?.brokerName,c.payload?.customsOffice,c.payload?.hsCode,c.payload?.commoditySummary].some(v=>String(v||'').toLowerCase().includes(q))));},[cases,search,filter]);
  const open=cases.filter(c=>!['CLEARED','RELEASED','CANCELLED'].includes(c.status)).length;const holds=cases.filter(c=>['ON_HOLD','INSPECTION','DUTY_PENDING'].includes(c.status)).length;const cleared=cases.filter(c=>c.status==='CLEARED').length;const released=cases.filter(c=>c.status==='RELEASED').length;
  return <WorkspaceShell title="Customs Clearance" subtitle="Declaration, inspection, duty and release control" active="/customs" actions={<button className="btn" onClick={()=>setShowForm(v=>!v)}>{showForm?'Close Form':'+ Customs Case'}</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12,marginBottom:12}}><Kpi l="Open Cases" v={open}/><Kpi l="Inspection / Hold" v={holds}/><Kpi l="Cleared" v={cleared}/><Kpi l="Released" v={released}/></div>
    {showForm&&<div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Create Customs Clearance Case</h3><div style={formGrid}>
      <label><span style={labelStyle}>Booking</span><select value={form.bookingId} onChange={e=>set('bookingId',e.target.value)} style={fieldStyle}><option value="">-- Select booking --</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.bookingNo} — {b.customer?.name||''} — {b.origin} → {b.destination}</option>)}</select></label>
      <Input l="Declaration / Entry No." v={form.declarationNo} onChange={v=>set('declarationNo',v)}/><Input l="Customs Office" v={form.customsOffice} onChange={v=>set('customsOffice',v)}/><Input l="Broker" v={form.brokerName} onChange={v=>set('brokerName',v)}/><Input l="Broker Reference" v={form.brokerReference} onChange={v=>set('brokerReference',v)}/>
      <label><span style={labelStyle}>Clearance Type</span><select value={form.clearanceType} onChange={e=>set('clearanceType',e.target.value)} style={fieldStyle}><option>IMPORT</option><option>EXPORT</option><option>TRANSIT</option><option>TEMPORARY</option></select></label>
      <Input l="Entry Type" v={form.entryType} onChange={v=>set('entryType',v)}/><Input l="HS Code" v={form.hsCode} onChange={v=>set('hsCode',v)}/><Input l="Commodity Summary" v={form.commoditySummary} onChange={v=>set('commoditySummary',v)}/><Input l="Duty Amount" v={form.dutyAmount} type="number" onChange={v=>set('dutyAmount',v)}/><Input l="Tax Amount" v={form.taxAmount} type="number" onChange={v=>set('taxAmount',v)}/><Input l="Other Charges" v={form.otherCharges} type="number" onChange={v=>set('otherCharges',v)}/><Input l="Currency" v={form.currency} onChange={v=>set('currency',v)}/><Input l="Inspection Location" v={form.inspectionLocation} onChange={v=>set('inspectionLocation',v)}/><Input l="Hold Reason" v={form.holdReason} onChange={v=>set('holdReason',v)}/>
    </div><label style={{display:'block',marginTop:10}}><span style={labelStyle}>Remarks</span><textarea value={form.remarks} onChange={e=>set('remarks',e.target.value)} style={{...fieldStyle,minHeight:72}}/></label><div style={{textAlign:'right',marginTop:12}}><button className="btn" disabled={busy} onClick={create}>{busy?'Working...':'Create Customs Case'}</button></div></div>}
    <div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap',marginBottom:10}}><div><h3 style={{margin:0}}>Customs Control Board</h3><span className="sub">{visible.length} visible cases</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search declaration, booking, broker..." style={{...fieldStyle,width:260}}/><select value={filter} onChange={e=>setFilter(e.target.value)} style={{...fieldStyle,width:170}}><option value="ALL">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div>
      <div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Declaration</th><th>Booking</th><th>Broker / Office</th><th>Commodity</th><th>Duty / Tax</th><th>Inspection / Hold</th><th>Status</th><th>Workflow</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan={8}>No customs cases found.</td></tr>:visible.map(c=><tr key={c.id}><td><b>{c.payload?.declarationNo||c.externalId||'-'}</b><div className="sub">{c.payload?.clearanceType||''}</div></td><td><a href={`/bookings/${c.objectId}`} style={{fontWeight:800,color:'#123b61'}}>{c.booking?.bookingNo||c.objectId}</a><div className="sub">{c.booking?.customer?.name||''}</div></td><td>{c.payload?.brokerName||'-'}<div className="sub">{c.payload?.customsOffice||'-'}</div></td><td>{c.payload?.commoditySummary||'-'}<div className="sub">HS {c.payload?.hsCode||'-'}</div></td><td>{c.payload?.currency||'USD'} {Number(c.payload?.dutyAmount||0).toFixed(2)}<div className="sub">Tax {Number(c.payload?.taxAmount||0).toFixed(2)}</div></td><td>{c.payload?.inspectionLocation||'-'}<div className="sub">{c.payload?.holdReason||''}</div></td><td><span className="status">{c.status}</span></td><td><div style={{display:'flex',gap:5,flexWrap:'wrap',minWidth:220}}>{c.status==='DRAFT'&&<button className="btn" disabled={busy} onClick={()=>transition(c.id,'SUBMITTED')}>Submit</button>}{['SUBMITTED','UNDER_REVIEW'].includes(c.status)&&<button className="btn" disabled={busy} onClick={()=>transition(c.id,'INSPECTION')}>Inspection</button>}{!['CLEARED','RELEASED','CANCELLED'].includes(c.status)&&<button className="btn" disabled={busy} onClick={()=>transition(c.id,'CLEARED')}>Clear</button>}{c.status==='CLEARED'&&<button className="btn" disabled={busy} onClick={()=>transition(c.id,'RELEASED')}>Release</button>}{!['RELEASED','CANCELLED'].includes(c.status)&&<button className="btn" disabled={busy} onClick={()=>transition(c.id,'CANCELLED')}>Cancel</button>}</div></td></tr>)}</tbody></table></div>
    </div>
  </WorkspaceShell>;
}
function Kpi({l,v}:{l:string;v:number}){return <div className="card"><div className="sub">{l}</div><div className="kpi">{v}</div></div>}
function Input({l,v,onChange,type='text'}:{l:string;v:string;onChange:(v:string)=>void;type?:string}){return <label><span style={labelStyle}>{l}</span><input type={type} value={v} onChange={e=>onChange(e.target.value)} style={fieldStyle}/></label>}
