'use client';
import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

export default function EnterpriseRiskPage(){
 const [token,setToken]=useState(''),[data,setData]=useState<any>({summary:{},screenings:[],policies:[],certificates:[],dgReviews:[],documents:[],holds:[],recoveries:[],expiry:[]}),[customers,setCustomers]=useState<any[]>([]),[bookings,setBookings]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [policy,setPolicy]=useState<any>({requireKyc:true,requireInsurance:false,requireInsuranceForDG:true,screeningValidityDays:365,documentWarningDays:30});
 const [screen,setScreen]=useState<any>({organizationId:'',kycStatus:'APPROVED',sanctionsStatus:'CLEAR',pepStatus:'CLEAR',expiresAt:'',provider:'MANUAL',reference:'',notes:''});
 const [ins,setIns]=useState<any>({policyNo:'',insurer:'',currency:'USD',limit:0,deductible:0,validFrom:'',validTo:'',active:true});
 const [cert,setCert]=useState<any>({bookingId:'',policyId:'',certificateNo:'',insuredValue:0,currency:'USD',status:'ISSUED'});
 const [dg,setDg]=useState<any>({bookingId:'',declarationReceived:false,sdsReceived:false,carrierAccepted:false,status:'PENDING',notes:''});
 const [doc,setDoc]=useState<any>({organizationId:'',documentType:'BUSINESS_LICENSE',reference:'',issuedAt:'',expiresAt:'',status:'VALID'});
 const [hold,setHold]=useState<any>({bookingId:'',type:'COMPLIANCE',reason:'Risk review required'});
 const [rec,setRec]=useState<any>({claimId:'',bookingId:'',insurer:'',policyId:'',amount:0,currency:'USD',status:'OPEN',subrogationParty:'',reference:'',notes:''});
 useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
 async function load(t=token){try{const [d,c,b]=await Promise.all([api('/enterprise-risk/dashboard',t),api('/enterprise-risk/customers',t),api('/enterprise-risk/bookings',t)]);setData(d);setCustomers(c);setBookings(b);}catch(e:any){setMessage(e.message||'Unable to load Enterprise Risk');}}
 async function post(path:string,body:any,ok:string){setBusy(true);try{await api(path,token,{method:'POST',body:JSON.stringify(body)});setMessage(ok);await load();}catch(e:any){setMessage(e.message||'Action failed');}finally{setBusy(false);}}
 const s=data.summary||{};
 return <WorkspaceShell title="Enterprise Risk / Insurance" subtitle="KYC & sanctions, cargo insurance, dangerous goods, compliance expiry, risk holds and insurer recovery" active="/enterprise-risk" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
  {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:12}}>{[['Active Policies',s.activePolicies],['Active Holds',s.activeHolds],['Sanctions Matches',s.sanctionsMatches],['Pending DG',s.pendingDG],['Expiring 30d',s.expiring30d],['Open Recoveries',s.openInsuranceRecoveries]].map(([a,b])=><div className="card" key={String(a)}><div className="sub">{a}</div><div style={{fontSize:24,fontWeight:800}}>{b??0}</div></div>)}</div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Global Risk Policy</h3><div style={formGrid}>
   {['requireKyc','requireInsurance','requireInsuranceForDG'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type="checkbox" checked={Boolean(policy[k])} onChange={e=>setPolicy({...policy,[k]:e.target.checked})}/></label>)}
   <label><span style={labelStyle}>Screening validity days</span><input style={fieldStyle} type="number" value={policy.screeningValidityDays} onChange={e=>setPolicy({...policy,screeningValidityDays:Number(e.target.value)})}/></label>
   <label><span style={labelStyle}>Document warning days</span><input style={fieldStyle} type="number" value={policy.documentWarningDays} onChange={e=>setPolicy({...policy,documentWarningDays:Number(e.target.value)})}/></label>
  </div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/enterprise-risk/policy',policy,'Risk policy saved.')}>Save Policy</button></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>KYC / Sanctions Screening</h3><div style={formGrid}>
   <label><span style={labelStyle}>Customer</span><select style={fieldStyle} value={screen.organizationId} onChange={e=>setScreen({...screen,organizationId:e.target.value})}><option value="">Select</option>{customers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
   {['kycStatus','sanctionsStatus','pepStatus','provider','reference','expiresAt'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input style={fieldStyle} type={k==='expiresAt'?'date':'text'} value={screen[k]} onChange={e=>setScreen({...screen,[k]:e.target.value})}/></label>)}
  </div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/enterprise-risk/screenings',screen,'Screening saved.')}>Save Screening</button>
  <div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Counterparty</th><th>KYC</th><th>Sanctions</th><th>PEP</th><th>Expires</th></tr></thead><tbody>{(data.screenings||[]).map((x:any)=><tr key={x.organizationId}><td>{x.counterpartyName}</td><td>{x.kycStatus}</td><td>{x.sanctionsStatus}</td><td>{x.pepStatus}</td><td>{String(x.expiresAt||'—').slice(0,10)}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Cargo Insurance</h3><div style={formGrid}>{['policyNo','insurer','currency','limit','deductible','validFrom','validTo'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input style={fieldStyle} type={['limit','deductible'].includes(k)?'number':['validFrom','validTo'].includes(k)?'date':'text'} value={ins[k]} onChange={e=>setIns({...ins,[k]:['limit','deductible'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/enterprise-risk/insurance-policies',ins,'Insurance policy saved.')}>Save Insurance Policy</button>
  <div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Policy</th><th>Insurer</th><th>Limit</th><th>Deductible</th><th>Valid To</th></tr></thead><tbody>{(data.policies||[]).map((x:any)=><tr key={x.policyId}><td>{x.policyNo}</td><td>{x.insurer}</td><td>{x.currency} {Number(x.limit||0).toFixed(2)}</td><td>{x.currency} {Number(x.deductible||0).toFixed(2)}</td><td>{String(x.validTo||'—').slice(0,10)}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Booking Insurance Certificate</h3><div style={formGrid}><label><span style={labelStyle}>Booking</span><select style={fieldStyle} value={cert.bookingId} onChange={e=>setCert({...cert,bookingId:e.target.value})}><option value="">Select</option>{bookings.map((x:any)=><option key={x.id} value={x.id}>{x.bookingNo}</option>)}</select></label><label><span style={labelStyle}>Policy</span><select style={fieldStyle} value={cert.policyId} onChange={e=>setCert({...cert,policyId:e.target.value})}><option value="">Select</option>{(data.policies||[]).map((x:any)=><option key={x.policyId} value={x.policyId}>{x.policyNo}</option>)}</select></label>{['certificateNo','insuredValue','currency','status'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input style={fieldStyle} type={k==='insuredValue'?'number':'text'} value={cert[k]} onChange={e=>setCert({...cert,[k]:k==='insuredValue'?Number(e.target.value):e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/enterprise-risk/certificates',cert,'Insurance certificate issued.')}>Issue Certificate</button></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Dangerous Goods Review</h3><div style={formGrid}><label><span style={labelStyle}>Booking</span><select style={fieldStyle} value={dg.bookingId} onChange={e=>setDg({...dg,bookingId:e.target.value})}><option value="">Select DG booking</option>{bookings.filter((x:any)=>x.dgUnNo||x.dgImoClass||String(x.specialCargo||'').toUpperCase().includes('DG')).map((x:any)=><option key={x.id} value={x.id}>{x.bookingNo}</option>)}</select></label>{['declarationReceived','sdsReceived','carrierAccepted'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type="checkbox" checked={Boolean(dg[k])} onChange={e=>setDg({...dg,[k]:e.target.checked})}/></label>)}<label><span style={labelStyle}>Status</span><select style={fieldStyle} value={dg.status} onChange={e=>setDg({...dg,status:e.target.value})}>{['PENDING','APPROVED','REJECTED'].map(x=><option key={x}>{x}</option>)}</select></label></div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/enterprise-risk/dg-reviews',dg,'DG review saved.')}>Save DG Review</button></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Compliance Documents & Expiry</h3><div style={formGrid}><label><span style={labelStyle}>Organization</span><select style={fieldStyle} value={doc.organizationId} onChange={e=>setDoc({...doc,organizationId:e.target.value})}><option value="">Select</option>{customers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{['documentType','reference','issuedAt','expiresAt','status'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input style={fieldStyle} type={['issuedAt','expiresAt'].includes(k)?'date':'text'} value={doc[k]} onChange={e=>setDoc({...doc,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/enterprise-risk/documents',doc,'Compliance document saved.')}>Save Document</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Type</th><th>Reference</th><th>Owner</th><th>Expires</th></tr></thead><tbody>{(data.expiry||[]).map((x:any,i:number)=><tr key={`${x.type}-${x.reference}-${i}`}><td>{x.type}</td><td>{x.reference}</td><td>{x.owner}</td><td>{String(x.expiresAt||'').slice(0,10)}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Booking Risk Holds</h3><div style={formGrid}><label><span style={labelStyle}>Booking</span><select style={fieldStyle} value={hold.bookingId} onChange={e=>setHold({...hold,bookingId:e.target.value})}><option value="">Select</option>{bookings.map((x:any)=><option key={x.id} value={x.id}>{x.bookingNo}</option>)}</select></label>{['type','reason'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input style={fieldStyle} value={hold[k]} onChange={e=>setHold({...hold,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post(`/enterprise-risk/bookings/${hold.bookingId}/holds`,{type:hold.type,reason:hold.reason},'Risk hold placed.')}>Place Hold</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Booking</th><th>Type</th><th>Reason</th><th>Placed</th><th>Action</th></tr></thead><tbody>{(data.holds||[]).map((x:any)=><tr key={x.holdId}><td>{bookings.find((b:any)=>b.id===x.bookingId)?.bookingNo||x.bookingId}</td><td>{x.type}</td><td>{x.reason}</td><td>{String(x.placedAt||'').slice(0,10)}</td><td><button className="btn" disabled={busy} onClick={()=>void post(`/enterprise-risk/holds/${x.holdId}/release`,{reason:'Risk cleared'},'Risk hold released.')}>Release</button></td></tr>)}</tbody></table></div></div>
  <div className="card"><h3 style={sectionTitle}>Insurance Recovery / Subrogation</h3><div style={formGrid}>{['claimId','bookingId','insurer','policyId','amount','currency','status','subrogationParty','reference'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input style={fieldStyle} type={k==='amount'?'number':'text'} value={rec[k]} onChange={e=>setRec({...rec,[k]:k==='amount'?Number(e.target.value):e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/enterprise-risk/recoveries',rec,'Insurance recovery created.')}>Create Recovery</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Recovery</th><th>Claim/Booking</th><th>Insurer</th><th>Amount</th><th>Status</th><th>Subrogation</th></tr></thead><tbody>{(data.recoveries||[]).map((x:any)=><tr key={x.recoveryId}><td>{x.recoveryId}</td><td>{x.claimId||x.bookingId}</td><td>{x.insurer||'—'}</td><td>{x.currency} {Number(x.amount||0).toFixed(2)}</td><td>{x.status}</td><td>{x.subrogationParty||'—'}</td></tr>)}</tbody></table></div></div>
 </WorkspaceShell>;
}
