import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SRC='ANCLINE_TREASURY', ACC='ANCLINE_ACCOUNTING', CREDIT='ANCLINE_CREDIT_CONTROL', GL='ANCLINE_GL', STAT='ANCLINE_STATUTORY_FINANCE';
const DAY=86400000;

@Injectable()
export class TreasuryService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private get db():any{return this.prisma as any;}
  private access(u:ScopeUser){this.scope.assertFinanceAccess(u);}
  private p(e:any){return (e?.payload||{}) as any;}
  private r(v:any){return Math.round((Number(v||0)+Number.EPSILON)*100)/100;}
  private req(v:any,n:string){const s=String(v??'').trim();if(!s)throw new BadRequestException(`${n} is required`);return s;}
  private cur(v:any){const s=String(v||'USD').toUpperCase();if(!/^[A-Z]{3}$/.test(s))throw new BadRequestException('Invalid currency');return s;}
  private dt(v:any,n='Date'){const d=new Date(v);if(Number.isNaN(d.getTime()))throw new BadRequestException(`${n} is invalid`);return d;}
  private per(v:any){const d=this.dt(v);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
  private norm(v:any){return String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');}

  private async entityMap(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:STAT,objectType:'LegalEntity',eventType:'LEGAL_ENTITY_SET'},orderBy:{createdAt:'asc'}});const m=new Map<string,any>();for(const x of rows)m.set(x.objectId,{entityId:x.objectId,...this.p(x)});return m;}
  async legalEntities(u:ScopeUser){this.access(u);return Array.from((await this.entityMap()).values()).filter((x:any)=>x.active!==false);}

  private async accountMap(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'BankAccount',eventType:'BANK_ACCOUNT_SET'},orderBy:{createdAt:'asc'}});const m=new Map<string,any>();for(const x of rows)m.set(x.objectId,{accountId:x.objectId,...this.p(x),updatedAt:x.createdAt});return m;}
  private async bankMovements(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:CREDIT,objectType:'BankTransaction',eventType:'BANK_TRANSACTION_IMPORTED'},orderBy:{createdAt:'asc'}});return rows.map((x:any)=>{const p=this.p(x);return {account:p.account||'',currency:this.cur(p.currency),amount:this.r(p.amount),direction:String(p.direction||'CREDIT').toUpperCase()};});}

  async bankAccounts(u:ScopeUser):Promise<any[]>{
    this.access(u);const [accounts,entities,moves,runs]=await Promise.all([this.accountMap(),this.entityMap(),this.bankMovements(),this.runRows()]);const approved=runs.filter((x:any)=>x.status==='APPROVED');const out:any[]=[];
    for(const a of accounts.values()){const keys=[a.accountId,a.accountReference,a.iban].map((x:any)=>this.norm(x)).filter(Boolean);const movement=this.r(moves.filter((x:any)=>x.currency===a.currency&&keys.includes(this.norm(x.account))).reduce((s:number,x:any)=>s+(x.direction==='CREDIT'?x.amount:-x.amount),0));const statementBalance=this.r(Number(a.openingBalance||0)+movement);const committed=this.r(approved.filter((x:any)=>x.bankAccountId===a.accountId).reduce((s:number,x:any)=>s+Number(x.totalAmount||0),0));const available=this.r(statementBalance+Number(a.overdraftLimit||0)-committed);out.push({...a,entity:entities.get(a.entityId)||null,statementBalance,committedPayments:committed,availableLiquidity:available,liquidityStatus:available<0?'BREACH':statementBalance-committed<Number(a.minimumCash||0)?'LOW':'OK'});}return out;
  }

  async setBankAccount(id:string|undefined,b:any,u:ScopeUser){
    this.access(u);const entities=await this.entityMap(),entityId=this.req(b?.entityId,'Legal entity');if(!entities.has(entityId))throw new BadRequestException('Legal entity not found');const accountId=String(id||`BA-${Date.now().toString().slice(-9)}`).toUpperCase();const payload={accountId,entityId,bankName:this.req(b?.bankName,'Bank name'),accountName:this.req(b?.accountName,'Account name'),accountReference:this.req(b?.accountReference||b?.iban,'Account reference'),iban:b?.iban?String(b.iban).toUpperCase():null,swiftCode:b?.swiftCode?String(b.swiftCode).toUpperCase():null,currency:this.cur(b?.currency),glAccount:String(b?.glAccount||'1000-BANK').toUpperCase(),openingBalance:this.r(b?.openingBalance),overdraftLimit:this.r(b?.overdraftLimit),minimumCash:this.r(b?.minimumCash),active:b?.active!==false,notes:b?.notes?String(b.notes):null,updatedBy:u.sub};if(payload.overdraftLimit<0||payload.minimumCash<0)throw new BadRequestException('Liquidity limits cannot be negative');await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'BANK_ACCOUNT_SET',externalId:accountId,objectType:'BankAccount',objectId:accountId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'TREASURY_BANK_ACCOUNT_SET',objectType:'BankAccount',objectId:accountId,detail:payload});return payload;
  }

  private buildInvoice(rows:any[]){const c=rows.find((e:any)=>e.eventType==='INVOICE_CREATED');if(!c)return null;const b=this.p(c),issued=rows.find((e:any)=>e.eventType==='INVOICE_ISSUED'),ctl=rows.filter((e:any)=>['INVOICE_DISPUTED','INVOICE_RESOLVED','INVOICE_VOIDED'].includes(e.eventType)).pop(),payments=rows.filter((e:any)=>e.eventType==='PAYMENT_RECORDED');const paid=this.r(payments.reduce((s:number,e:any)=>s+Number(this.p(e).amount||0),0)),total=this.r(b.totalAmount),balance=this.r(Math.max(0,total-paid));let status='DRAFT';if(ctl?.eventType==='INVOICE_VOIDED')status='VOID';else if(ctl?.eventType==='INVOICE_DISPUTED')status='DISPUTED';else if(balance<=0.005&&total>0)status='PAID';else if(paid>0)status='PART_PAID';else if(issued)status='ISSUED';return {invoiceNo:String(b.invoiceNo||c.objectId),invoiceType:String(b.invoiceType||'AR').toUpperCase(),bookingId:String(b.bookingId||''),partyId:b.partyId||null,partyName:b.partyName||null,currency:this.cur(b.currency),balanceAmount:balance,dueDate:b.dueDate||null,status};}
  private async invoices(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:ACC,objectType:'FinanceInvoice'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const x of rows){if(!g.has(x.objectId))g.set(x.objectId,[]);g.get(x.objectId)!.push(x);}return Array.from(g.values()).map((x:any[])=>this.buildInvoice(x)).filter(Boolean) as any[];}

  private async runRows(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'PaymentRun'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const x of rows){if(!g.has(x.objectId))g.set(x.objectId,[]);g.get(x.objectId)!.push(x);}const out:any[]=[];for(const ev of g.values()){const c=ev.find((e:any)=>e.eventType==='PAYMENT_RUN_CREATED');if(!c)continue;const cancel=[...ev].reverse().find((e:any)=>e.eventType==='PAYMENT_RUN_CANCELLED'),posted=ev.find((e:any)=>e.eventType==='PAYMENT_RUN_POSTED'),approved=ev.find((e:any)=>e.eventType==='PAYMENT_RUN_APPROVED');out.push({...this.p(c),runNo:c.objectId,status:cancel?'CANCELLED':posted?'POSTED':approved?'APPROVED':'DRAFT',createdAt:c.createdAt,approvedAt:approved?.createdAt||null,postedAt:posted?.createdAt||null});}return out;}
  async paymentRuns(u:ScopeUser){this.access(u);return (await this.runRows()).sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());}
  async eligibleAP(u:ScopeUser){this.access(u);const [inv,runs]=await Promise.all([this.invoices(),this.runRows()]);const reserved=new Set<string>();for(const x of runs.filter((r:any)=>['DRAFT','APPROVED'].includes(r.status)))for(const i of x.items||[])reserved.add(String(i.invoiceNo));return inv.filter((i:any)=>i.invoiceType==='AP'&&['ISSUED','PART_PAID'].includes(i.status)&&i.balanceAmount>0&&!reserved.has(i.invoiceNo));}

  async createPaymentRun(b:any,u:ScopeUser){
    this.access(u);const accountId=this.req(b?.bankAccountId,'Bank account'),accounts=await this.bankAccounts(u),bank=accounts.find((x:any)=>x.accountId===accountId&&x.active!==false);if(!bank)throw new BadRequestException('Active bank account not found');const nos=[...new Set((Array.isArray(b?.invoiceNos)?b.invoiceNos:[]).map(String))] as string[];if(!nos.length)throw new BadRequestException('Select supplier invoices');const eligible=await this.eligibleAP(u),selected=eligible.filter((x:any)=>nos.includes(x.invoiceNo));if(selected.length!==nos.length)throw new BadRequestException('One or more invoices are no longer eligible');if(selected.some((x:any)=>x.currency!==bank.currency))throw new BadRequestException('Invoice currency must match bank currency');const date=this.dt(b?.paymentDate||new Date(),'Payment date'),runNo=String(b?.runNo||`PAY-${date.toISOString().slice(0,10).replace(/-/g,'')}-${Date.now().toString().slice(-6)}`).toUpperCase(),items=selected.map((x:any)=>({invoiceNo:x.invoiceNo,bookingId:x.bookingId,partyId:x.partyId,partyName:x.partyName,amount:x.balanceAmount,currency:x.currency,dueDate:x.dueDate})),totalAmount=this.r(items.reduce((s:number,x:any)=>s+x.amount,0));if(await this.db.integrationEvent.findFirst({where:{sourceSystem:SRC,objectType:'PaymentRun',objectId:runNo}}))throw new BadRequestException('Payment run already exists');const payload={runNo,bankAccountId:accountId,currency:bank.currency,paymentDate:date.toISOString(),items,totalAmount,invoiceCount:items.length,notes:b?.notes?String(b.notes):null,createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'PAYMENT_RUN_CREATED',externalId:runNo,objectType:'PaymentRun',objectId:runNo,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'TREASURY_PAYMENT_RUN_CREATE',objectType:'PaymentRun',objectId:runNo,detail:{accountId,totalAmount,currency:bank.currency}});return {...payload,status:'DRAFT'};
  }

  async approvePaymentRun(runNo:string,u:ScopeUser){this.access(u);const run=(await this.runRows()).find((x:any)=>x.runNo===runNo);if(!run)throw new NotFoundException('Payment run not found');if(run.status!=='DRAFT')throw new BadRequestException(`Cannot approve from ${run.status}`);const bank=(await this.bankAccounts(u)).find((x:any)=>x.accountId===run.bankAccountId);if(!bank)throw new BadRequestException('Bank account not found');const capacity=this.r(bank.statementBalance+Number(bank.overdraftLimit||0));if(Number(run.totalAmount)>capacity+0.005)throw new BadRequestException(`Payment run exceeds available liquidity by ${this.r(Number(run.totalAmount)-capacity)} ${run.currency}`);const projected=this.r(bank.statementBalance-Number(run.totalAmount));await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'PAYMENT_RUN_APPROVED',externalId:runNo,objectType:'PaymentRun',objectId:runNo,status:'COMPLETED',payload:{runNo,approvedBy:u.sub,projectedBalance:projected,minimumCashBreach:projected<Number(bank.minimumCash||0)},completedAt:new Date()}});return {ok:true,runNo,status:'APPROVED',projectedBalance:projected,minimumCashBreach:projected<Number(bank.minimumCash||0)};}

  private async journalRefs(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GL,objectType:'JournalEntry',eventType:'JOURNAL_CREATED'}});return new Set(rows.map((x:any)=>String(this.p(x).reference||'')).filter(Boolean));}
  private async periodStatus(period:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GL,objectType:'FiscalPeriod',objectId:period},orderBy:{createdAt:'asc'}});return rows.length?String(this.p(rows[rows.length-1]).status||'OPEN'):'OPEN';}

  async postPaymentRun(runNo:string,u:ScopeUser){
    this.access(u);const run=(await this.runRows()).find((x:any)=>x.runNo===runNo);if(!run)throw new NotFoundException('Payment run not found');if(run.status==='POSTED')return run;if(run.status!=='APPROVED')throw new BadRequestException(`Cannot post from ${run.status}`);const bank=(await this.accountMap()).get(run.bankAccountId);if(!bank||bank.active===false)throw new BadRequestException('Bank account is inactive');const period=this.per(run.paymentDate);if(await this.periodStatus(period)==='CLOSED')throw new BadRequestException(`Period ${period} is closed`);const inv=await this.invoices(),refs=await this.journalRefs();for(const item of run.items||[]){const x=inv.find((i:any)=>i.invoiceNo===item.invoiceNo);if(!x||!['ISSUED','PART_PAID'].includes(x.status)||Math.abs(Number(x.balanceAmount)-Number(item.amount))>0.005)throw new BadRequestException(`Invoice ${item.invoiceNo} changed after approval`);if(!refs.has(`INVOICE:${item.invoiceNo}:ISSUE`))throw new BadRequestException(`Invoice ${item.invoiceNo} must be posted to GL first`);}
    const posted:any[]=await this.db.$transaction(async(tx:any)=>{const out:any[]=[];for(const item of run.items||[]){const pe=await tx.integrationEvent.create({data:{sourceSystem:ACC,eventType:'PAYMENT_RECORDED',externalId:`TREASURY:${runNo}:${item.invoiceNo}`,objectType:'FinanceInvoice',objectId:item.invoiceNo,status:'COMPLETED',payload:{invoiceNo:item.invoiceNo,amount:this.r(item.amount),currency:run.currency,paidAt:run.paymentDate,method:'TREASURY_PAYMENT_RUN',reference:runNo,recordedBy:u.sub},completedAt:new Date()}});const jn=`TP-${period.replace('-','')}-${String(pe.id).replace(/[^a-z0-9]/gi,'').slice(-8).toUpperCase()}`,amount=this.r(item.amount),lines=[{account:'2000-ACCOUNTS-PAYABLE',description:`Settle ${item.invoiceNo}`,debit:amount,credit:0,partyId:item.partyId,bookingId:item.bookingId},{account:String(bank.glAccount||'1000-BANK').toUpperCase(),description:`Treasury posting ${item.invoiceNo}`,debit:0,credit:amount,partyId:item.partyId,bookingId:item.bookingId,bankAccountId:run.bankAccountId}],payload={journalNo:jn,journalDate:run.paymentDate,period,currency:run.currency,description:`Supplier payment ${item.invoiceNo}`,reference:`PAYMENT:${pe.id}`,source:'TREASURY_PAYMENT_RUN',entityId:bank.entityId,legalEntityId:bank.entityId,lines,totalDebit:amount,totalCredit:amount};await tx.integrationEvent.create({data:{sourceSystem:GL,eventType:'JOURNAL_CREATED',externalId:jn,objectType:'JournalEntry',objectId:jn,status:'COMPLETED',payload,completedAt:new Date()}});await tx.integrationEvent.create({data:{sourceSystem:GL,eventType:'JOURNAL_POSTED',externalId:jn,objectType:'JournalEntry',objectId:jn,status:'COMPLETED',payload:{journalNo:jn,postedBy:u.sub,automated:true,sourceReference:`PAYMENT:${pe.id}`},completedAt:new Date()}});await tx.financeLine.updateMany({where:{invoiceNo:item.invoiceNo},data:{status:'PAID'}});out.push({invoiceNo:item.invoiceNo,paymentEventId:pe.id,journalNo:jn,amount});}await tx.integrationEvent.create({data:{sourceSystem:SRC,eventType:'PAYMENT_RUN_POSTED',externalId:runNo,objectType:'PaymentRun',objectId:runNo,status:'COMPLETED',payload:{runNo,postedBy:u.sub,postedAt:new Date().toISOString(),items:out},completedAt:new Date()}});return out;});await this.audit.log({actorId:u.sub,action:'TREASURY_PAYMENT_RUN_POST',objectType:'PaymentRun',objectId:runNo,detail:{totalAmount:run.totalAmount,currency:run.currency,count:posted.length}});return {ok:true,runNo,status:'POSTED',items:posted};
  }

  async cancelPaymentRun(runNo:string,b:any,u:ScopeUser){this.access(u);const run=(await this.runRows()).find((x:any)=>x.runNo===runNo);if(!run)throw new NotFoundException('Payment run not found');if(!['DRAFT','APPROVED'].includes(run.status))throw new BadRequestException(`Cannot cancel from ${run.status}`);const reason=this.req(b?.reason||'Cancelled by treasury','Reason');await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'PAYMENT_RUN_CANCELLED',externalId:runNo,objectType:'PaymentRun',objectId:runNo,status:'COMPLETED',payload:{runNo,reason,cancelledBy:u.sub},completedAt:new Date()}});return {ok:true,runNo,status:'CANCELLED'};}

  private async forecastMap(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'ForecastItem'},orderBy:{createdAt:'asc'}}),m=new Map<string,any>();for(const x of rows){if(x.eventType==='FORECAST_ITEM_SET')m.set(x.objectId,{forecastId:x.objectId,...this.p(x),status:'ACTIVE'});if(x.eventType==='FORECAST_ITEM_CANCELLED'&&m.has(x.objectId))m.set(x.objectId,{...m.get(x.objectId),status:'CANCELLED'});}return m;}
  async forecastItems(u:ScopeUser){this.access(u);return Array.from((await this.forecastMap()).values());}
  async setForecastItem(b:any,u:ScopeUser){this.access(u);const id=String(b?.forecastId||`FC-${Date.now().toString().slice(-9)}`).toUpperCase(),direction=String(b?.direction||'OUTFLOW').toUpperCase();if(!['INFLOW','OUTFLOW'].includes(direction))throw new BadRequestException('Direction must be INFLOW or OUTFLOW');const amount=this.r(b?.amount);if(amount<=0)throw new BadRequestException('Amount must be greater than zero');const payload={forecastId:id,forecastDate:this.dt(b?.forecastDate,'Forecast date').toISOString(),direction,amount,currency:this.cur(b?.currency),category:String(b?.category||'OTHER').toUpperCase(),description:this.req(b?.description,'Description'),entityId:b?.entityId?String(b.entityId):null,probability:Math.max(0,Math.min(100,Number(b?.probability??100))),updatedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'FORECAST_ITEM_SET',externalId:id,objectType:'ForecastItem',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return payload;}
  async cancelForecastItem(id:string,u:ScopeUser){this.access(u);if(!(await this.forecastMap()).has(id))throw new NotFoundException('Forecast item not found');await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'FORECAST_ITEM_CANCELLED',externalId:id,objectType:'ForecastItem',objectId:id,status:'COMPLETED',payload:{cancelledBy:u.sub},completedAt:new Date()}});return {ok:true};}

  async cashForecast(daysInput:any,u:ScopeUser){
    this.access(u);const days=Math.max(7,Math.min(180,Number(daysInput||56))),start=new Date();start.setUTCHours(0,0,0,0);const [accounts,inv,runs,items]=await Promise.all([this.bankAccounts(u),this.invoices(),this.runRows(),this.forecastItems(u)]),approved=runs.filter((x:any)=>x.status==='APPROVED'),reserved=new Set<string>();for(const x of approved)for(const i of x.items||[])reserved.add(String(i.invoiceNo));const currencies=[...new Set(accounts.filter((x:any)=>x.active!==false).map((x:any)=>String(x.currency)))] as string[],result:any[]=[];
    for(const currency of currencies){let cash=this.r(accounts.filter((x:any)=>x.currency===currency&&x.active!==false).reduce((s:number,x:any)=>s+Number(x.statementBalance||0),0));const overdraft=this.r(accounts.filter((x:any)=>x.currency===currency&&x.active!==false).reduce((s:number,x:any)=>s+Number(x.overdraftLimit||0),0)),minimumCash=this.r(accounts.filter((x:any)=>x.currency===currency&&x.active!==false).reduce((s:number,x:any)=>s+Number(x.minimumCash||0),0)),buckets:any[]=[];for(let n=0;n<days;n++){const d=new Date(start.getTime()+n*DAY),next=new Date(d.getTime()+DAY),inside=(v:any)=>{const z=new Date(v);return !Number.isNaN(z.getTime())&&z>=d&&z<next;};const ar=this.r(inv.filter((x:any)=>x.invoiceType==='AR'&&['ISSUED','PART_PAID'].includes(x.status)&&x.currency===currency&&x.balanceAmount>0&&inside(x.dueDate||d)).reduce((s:number,x:any)=>s+x.balanceAmount,0)),ap=this.r(inv.filter((x:any)=>x.invoiceType==='AP'&&['ISSUED','PART_PAID'].includes(x.status)&&x.currency===currency&&x.balanceAmount>0&&!reserved.has(x.invoiceNo)&&inside(x.dueDate||d)).reduce((s:number,x:any)=>s+x.balanceAmount,0)),runOut=this.r(approved.filter((x:any)=>x.currency===currency&&inside(x.paymentDate)).reduce((s:number,x:any)=>s+Number(x.totalAmount||0),0)),manual=(items as any[]).filter((x:any)=>x.status==='ACTIVE'&&x.currency===currency&&inside(x.forecastDate)),mi=this.r(manual.filter((x:any)=>x.direction==='INFLOW').reduce((s:number,x:any)=>s+x.amount*x.probability/100,0)),mo=this.r(manual.filter((x:any)=>x.direction==='OUTFLOW').reduce((s:number,x:any)=>s+x.amount*x.probability/100,0)),opening=cash,net=this.r(ar+mi-ap-runOut-mo);cash=this.r(cash+net);buckets.push({date:d.toISOString().slice(0,10),opening,arInflow:ar,manualInflow:mi,apOutflow:ap,paymentRuns:runOut,manualOutflow:mo,net,closing:cash,availableLiquidity:this.r(cash+overdraft),status:cash+overdraft<0?'BREACH':cash<minimumCash?'LOW':'OK'});}result.push({currency,openingCash:buckets[0]?.opening||0,overdraft,minimumCash,closingCash:cash,buckets});}return {days,currencies:result};
  }

  async liquidity(u:ScopeUser){this.access(u);const accounts=await this.bankAccounts(u);return {accounts,breachCount:accounts.filter((x:any)=>x.liquidityStatus==='BREACH').length,lowCount:accounts.filter((x:any)=>x.liquidityStatus==='LOW').length};}
  async dashboard(u:ScopeUser){this.access(u);const [accounts,runs,ap,items]=await Promise.all([this.bankAccounts(u),this.runRows(),this.eligibleAP(u),this.forecastItems(u)]);return {bankAccountCount:accounts.filter((x:any)=>x.active!==false).length,liquidityAlerts:accounts.filter((x:any)=>x.liquidityStatus!=='OK').length,approvedRuns:runs.filter((x:any)=>x.status==='APPROVED').length,draftRuns:runs.filter((x:any)=>x.status==='DRAFT').length,eligibleAPCount:ap.length,eligibleAPByCurrency:Array.from(ap.reduce((m:Map<string,number>,x:any)=>m.set(x.currency,this.r((m.get(x.currency)||0)+x.balanceAmount)),new Map<string,number>()).entries()).map(([currency,amount])=>({currency,amount})),activeForecastItems:(items as any[]).filter((x:any)=>x.status==='ACTIVE').length};}
}
