'use client';
import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

export default function CustomerServicePage(){
 const [token,setToken]=useState(''),[data,setData]=useState<any>({summary:{},cases:[],claims:[],recoveries:[],claimExposure:[]}),[bookings,setBookings]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [caseForm,setCaseForm]=useState<any>({bookingId:'',category:'SERVICE',severity:'MEDIUM',subject:'',description:'',owner:'',contactName:'',contactEmail:'',source:'INTERNAL'});
 const [claim,setClaim]=useState<any>({bookingId:'',claimType:'DAMAGE',claimedAmount:'0',currency:'USD',incidentDate:'',notificationDeadline:'',liablePartyType:'CARRIER',liablePartyId:'',insurerReference:'',description:'',reserveAmount:'0'});
 const [recovery,setRecovery]=useState<any>({bookingId:'',caseId:'',recoveryType:'GOODWILL_CREDIT',amount:'0',currency:'USD',reason:''});
 useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
 async function load(t=token){try{const [d,b]=await Promise.all([api('/customer-service/dashboard',t),api('/customer-service/bookings',t)]);setData(d);setBookings(b);}catch(e:any){setMessage(e.message||'Unable to load Customer Service');}}
 async function createCase(){setBusy(true);try{await api('/customer-service/cases',token,{method:'POST',body:JSON.stringify(caseForm)});setCaseForm({...caseForm,subject:'',description:''});setMessage('Case created.');await load();}catch(e:any){setMessage(e.message||'Case creation failed');}finally{setBusy(false);}}
 async function caseStatus(id:string,status:string){setBusy(true);try{await api(`/customer-service/cases/${id}/status`,token,{method:'POST',body:JSON.stringify({status})});await load();}catch(e:any){setMessage(e.message||'Case update failed');}finally{setBusy(false);}}
 async function csat(id:string){const score=Number(prompt('CSAT score 1-5?')||0);if(!score)return;try{await api(`/customer-service/cases/${id}/csat`,token,{method:'POST',body:JSON.stringify({score})});await load();}catch(e:any){setMessage(e.message||'CSAT failed');}}
 async function createClaim(){setBusy(true);try{await api('/customer-service/claims',token,{method:'POST',body:JSON.stringify({...claim,claimedAmount:Number(claim.claimedAmount),reserveAmount:Number(claim.reserveAmount)})});setMessage('Cargo claim created.');await load();}catch(e:any){setMessage(e.message||'Claim creation failed');}finally{setBusy(false);}}
 async function claimAction(id:string,action:string){setBusy(true);try{const body:any={};if(action==='APPROVE')body.approvedAmount=Number(prompt('Approved amount?')||0);if(action==='SETTLE')body.settledAmount=Number(prompt('Settled amount?')||0);await api(`/customer-service/claims/${id}/${action}`,token,{method:'POST',body:JSON.stringify(body)});await load();}catch(e:any){setMessage(e.message||'Claim action failed');}finally{setBusy(false);}}
 async function createRecovery(){setBusy(true);try{await api('/customer-service/recoveries',token,{method:'POST',body:JSON.stringify({...recovery,amount:Number(recovery.amount)})});setMessage('Service recovery requested.');await load();}catch(e:any){setMessage(e.message||'Recovery request failed');}finally{setBusy(false);}}
 async function decideRecovery(id:string,d:string){setBusy(true);try{await api(`/customer-service/recoveries/${id}/${d}`,token,{method:'POST',body:JSON.stringify({})});await load();}catch(e:any){setMessage(e.message||'Recovery decision failed');}finally{setBusy(false);}}
 const s=data.summary||{};
 return <WorkspaceShell title="Customer Service / Claims" subtitle="Customer cases, SLA escalation, cargo claims, service recovery and CSAT" active="/customer-service" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
  {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10,marginBottom:12}}>{[['Open Cases',s.openCases],['SLA Breaches',s.slaBreaches],['Critical',s.criticalCases],['Open Claims',s.openClaims],['Pending Recovery',s.pendingRecoveries],['Avg CSAT',s.avgCsat??'—']].map(([a,b])=><div className="card" key={String(a)}><div className="sub">{a}</div><div style={{fontSize:23,fontWeight:800}}>{b??0}</div></div>)}</div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>New Customer Case</h3><div style={formGrid}><label><span style={labelStyle}>Booking</span><select style={fieldStyle} value={caseForm.bookingId} onChange={e=>setCaseForm({...caseForm,bookingId:e.target.value})}><option value="">Select booking</option>{bookings.map((b:any)=><option key={b.id} value={b.id}>{b.bookingNo} · {b.origin}→{b.destination}</option>)}</select></label>{['category','severity','subject','owner','contactName','contactEmail','source'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input style={fieldStyle} value={caseForm[k]} onChange={e=>setCaseForm({...caseForm,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void createCase()}>Create Case</button></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Case & SLA Queue</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Case</th><th>Booking</th><th>Subject</th><th>Severity</th><th>Status</th><th>SLA</th><th>CSAT</th><th>Action</th></tr></thead><tbody>{(data.cases||[]).map((x:any)=><tr key={x.caseId}><td>{x.caseId}</td><td>{x.bookingNo}</td><td>{x.subject}</td><td>{x.severity}</td><td>{x.status}</td><td>{x.slaBreached?'BREACHED':String(x.slaDueAt||'').slice(0,16)}</td><td>{x.csat?.score||'—'}</td><td><button className="btn" onClick={()=>void caseStatus(x.caseId,'INVESTIGATING')}>Investigate</button> <button className="btn" onClick={()=>void caseStatus(x.caseId,'RESOLVED')}>Resolve</button> <button className="btn" onClick={()=>void csat(x.caseId)}>CSAT</button></td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Cargo Claim</h3><div style={formGrid}><label><span style={labelStyle}>Booking</span><select style={fieldStyle} value={claim.bookingId} onChange={e=>setClaim({...claim,bookingId:e.target.value})}><option value="">Select booking</option>{bookings.map((b:any)=><option key={b.id} value={b.id}>{b.bookingNo}</option>)}</select></label>{['claimType','claimedAmount','currency','incidentDate','notificationDeadline','liablePartyType','liablePartyId','insurerReference','reserveAmount'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type={k.includes('Date')||k==='notificationDeadline'?'date':k.includes('Amount')||k==='reserveAmount'?'number':'text'} style={fieldStyle} value={claim[k]} onChange={e=>setClaim({...claim,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void createClaim()}>Create Claim</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Claim</th><th>Booking</th><th>Type</th><th>Claimed</th><th>Reserve</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data.claims||[]).map((x:any)=><tr key={x.claimId}><td>{x.claimId}</td><td>{x.bookingNo}</td><td>{x.claimType}</td><td>{x.currency} {x.claimedAmount}</td><td>{x.currency} {x.reserveAmount}</td><td>{x.status}</td><td>{x.status==='DRAFT'&&<button className="btn" onClick={()=>void claimAction(x.claimId,'SUBMIT')}>Submit</button>} {x.status==='SUBMITTED'&&<button className="btn" onClick={()=>void claimAction(x.claimId,'ASSESS')}>Assess</button>} {x.status==='UNDER_ASSESSMENT'&&<button className="btn" onClick={()=>void claimAction(x.claimId,'APPROVE')}>Approve</button>} {x.status==='APPROVED'&&<button className="btn" onClick={()=>void claimAction(x.claimId,'SETTLE')}>Settle</button>}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Claim Exposure</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Currency</th><th>Open Reserve / Exposure</th></tr></thead><tbody>{(data.claimExposure||[]).map((x:any)=><tr key={x.currency}><td>{x.currency}</td><td>{Number(x.amount||0).toFixed(2)}</td></tr>)}</tbody></table></div></div>
  <div className="card"><h3 style={sectionTitle}>Service Recovery</h3><div style={formGrid}><label><span style={labelStyle}>Booking</span><select style={fieldStyle} value={recovery.bookingId} onChange={e=>setRecovery({...recovery,bookingId:e.target.value})}><option value="">Select booking</option>{bookings.map((b:any)=><option key={b.id} value={b.id}>{b.bookingNo}</option>)}</select></label>{['caseId','recoveryType','amount','currency','reason'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type={k==='amount'?'number':'text'} style={fieldStyle} value={recovery[k]} onChange={e=>setRecovery({...recovery,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void createRecovery()}>Request Recovery</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Recovery</th><th>Booking</th><th>Type</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{(data.recoveries||[]).map((x:any)=><tr key={x.recoveryId}><td>{x.recoveryId}</td><td>{x.bookingNo}</td><td>{x.recoveryType}</td><td>{x.currency} {x.amount}</td><td>{x.status}</td><td>{x.status==='PENDING'&&<><button className="btn" onClick={()=>void decideRecovery(x.recoveryId,'APPROVE')}>Approve</button> <button className="btn" onClick={()=>void decideRecovery(x.recoveryId,'REJECT')}>Reject</button></>} {x.status==='APPROVED'&&<button className="btn" onClick={()=>void decideRecovery(x.recoveryId,'COMPLETE')}>Complete</button>}</td></tr>)}</tbody></table></div></div>
 </WorkspaceShell>;
}
