import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SOURCE='ANCLINE_GOVERNANCE';
const now=()=>new Date();
const makeId=(p:string)=>`${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;

@Injectable()
export class GovernanceService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private events(){return this.prisma.integrationEvent.findMany({where:{sourceSystem:SOURCE},orderBy:{createdAt:'asc'}});}
  private payload(e:any){return (e?.payload||{}) as any;}
  private latest(rows:any[],objectType:string){const m=new Map<string,any>();for(const e of rows)if(e.objectType===objectType)m.set(e.objectId,{...this.payload(e),eventType:e.eventType,updatedAt:e.createdAt});return [...m.values()];}
  private assertAdmin(user:ScopeUser){if(user.role!=='GLOBAL_ADMIN')throw new ForbiddenException('Global administrator access required');}
  private async write(objectType:string,eventType:string,objectId:string,payload:any,user:ScopeUser){const row=await this.prisma.integrationEvent.create({data:{sourceSystem:SOURCE,objectType,objectId,eventType,status:'COMPLETED',payload:{...payload,updatedBy:user.sub},completedAt:now()}});await this.audit.log({actorId:user.sub,action:eventType,objectType,objectId,detail:payload});return row.payload;}

  async dashboard(user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events();const referenceData=this.latest(rows,'ReferenceData'),changeRequests=this.latest(rows,'MasterDataChange'),permissions=this.latest(rows,'PermissionMatrix'),thresholds=this.latest(rows,'ApprovalThreshold'),workflows=this.latest(rows,'WorkflowRule'),notifications=this.latest(rows,'NotificationRule');return {summary:{referenceEntries:referenceData.filter((x:any)=>x.active!==false).length,pendingChanges:changeRequests.filter((x:any)=>x.status==='PENDING').length,permissionRoles:permissions.filter((x:any)=>x.active!==false).length,approvalThresholds:thresholds.filter((x:any)=>x.active!==false).length,workflowRules:workflows.filter((x:any)=>x.active!==false).length,notificationRules:notifications.filter((x:any)=>x.active!==false).length},referenceData,changeRequests,permissions,thresholds,workflows,notifications};}

  async requestReferenceChange(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.category||!body?.key)throw new BadRequestException('Category and key are required');const changeId=String(body.changeId||makeId('MDC'));const currentRows=await this.events();const current=this.latest(currentRows,'ReferenceData').find((x:any)=>x.category===String(body.category)&&x.key===String(body.key));const proposed={referenceId:String(body.referenceId||current?.referenceId||`${body.category}:${body.key}`),category:String(body.category).toUpperCase(),key:String(body.key),label:body.label??current?.label??String(body.key),value:body.value??current?.value??null,active:body.active!==false,effectiveAt:body.effectiveAt||null,notes:body.notes||null};const payload={changeId,status:'PENDING',requesterId:user.email||user.sub,requestedAt:now().toISOString(),reason:body.reason||null,current:current||null,proposed};await this.write('MasterDataChange','MASTER_DATA_CHANGE_REQUESTED',changeId,payload,user);return payload;}

  async decideReferenceChange(changeId:string,decision:'APPROVED'|'REJECTED',body:any,user:ScopeUser){this.assertAdmin(user);const rows=await this.events();const current=this.latest(rows,'MasterDataChange').find((x:any)=>x.changeId===changeId);if(!current)throw new BadRequestException('Master-data change request not found');if(current.status!=='PENDING')throw new BadRequestException(`Change request is already ${current.status}`);const approver=user.email||user.sub;if(String(current.requesterId).toLowerCase()===String(approver).toLowerCase())throw new ForbiddenException('Maker/checker control: requester cannot approve own master-data change');const decided={...current,status:decision,decisionReason:body?.reason||null,decidedBy:approver,decidedAt:now().toISOString()};await this.write('MasterDataChange',decision==='APPROVED'?'MASTER_DATA_CHANGE_APPROVED':'MASTER_DATA_CHANGE_REJECTED',changeId,decided,user);if(decision==='APPROVED'){const ref=decided.proposed;await this.write('ReferenceData','REFERENCE_DATA_PUBLISHED',String(ref.referenceId),{...ref,version:Number((current.current?.version||0))+1,publishedBy:approver,publishedAt:now().toISOString()},user);}return decided;}

  async setPermission(body:any,user:ScopeUser){this.assertAdmin(user);if(!body?.role)throw new BadRequestException('Role is required');const role=String(body.role).toUpperCase(),permissionId=`ROLE:${role}`;const capabilities=Array.isArray(body.capabilities)?body.capabilities.map((x:any)=>String(x).toUpperCase()):[];return this.write('PermissionMatrix','PERMISSION_MATRIX_SET',permissionId,{permissionId,role,capabilities,active:body.active!==false,notes:body.notes||null},user);}

  async setThreshold(body:any,user:ScopeUser){this.assertAdmin(user);if(!body?.process||!body?.approverRole)throw new BadRequestException('Process and approver role are required');const thresholdId=String(body.thresholdId||makeId('THR'));const min=Number(body.amountMin||0),max=body.amountMax==null||body.amountMax===''?null:Number(body.amountMax);if(max!=null&&max<min)throw new BadRequestException('Maximum amount must be greater than or equal to minimum amount');return this.write('ApprovalThreshold','APPROVAL_THRESHOLD_SET',thresholdId,{thresholdId,process:String(body.process).toUpperCase(),amountMin:min,amountMax:max,currency:String(body.currency||'USD').toUpperCase(),approverRole:String(body.approverRole).toUpperCase(),branchId:body.branchId||null,active:body.active!==false,notes:body.notes||null},user);}

  async evaluateThreshold(body:any,user:ScopeUser){this.scope.assertInternal(user);const process=String(body?.process||'').toUpperCase(),currency=String(body?.currency||'USD').toUpperCase(),amount=Number(body?.amount||0),branchId=body?.branchId||null;if(!process)throw new BadRequestException('Process is required');const rows=await this.events(),rules=this.latest(rows,'ApprovalThreshold').filter((x:any)=>x.active!==false&&x.process===process&&x.currency===currency&&amount>=Number(x.amountMin||0)&&(x.amountMax==null||amount<=Number(x.amountMax))&&(!x.branchId||x.branchId===branchId));rules.sort((a:any,b:any)=>Number(!!b.branchId)-Number(!!a.branchId)||Number(b.amountMin||0)-Number(a.amountMin||0));return {process,currency,amount,branchId,matched:rules[0]||null,candidates:rules};}

  async setWorkflow(body:any,user:ScopeUser){this.assertAdmin(user);if(!body?.process||!body?.trigger||!body?.action)throw new BadRequestException('Process, trigger and action are required');const workflowId=String(body.workflowId||makeId('WFR'));return this.write('WorkflowRule','WORKFLOW_RULE_SET',workflowId,{workflowId,process:String(body.process).toUpperCase(),trigger:String(body.trigger).toUpperCase(),conditionField:body.conditionField||null,operator:String(body.operator||'EQUALS').toUpperCase(),conditionValue:body.conditionValue??null,action:String(body.action).toUpperCase(),ownerRole:body.ownerRole?String(body.ownerRole).toUpperCase():null,escalateAfterMinutes:body.escalateAfterMinutes==null||body.escalateAfterMinutes===''?null:Number(body.escalateAfterMinutes),active:body.active!==false,notes:body.notes||null},user);}

  async setNotification(body:any,user:ScopeUser){this.assertAdmin(user);if(!body?.eventType)throw new BadRequestException('Event type is required');const notificationRuleId=String(body.notificationRuleId||makeId('NTF'));const channels=Array.isArray(body.channels)?body.channels.map((x:any)=>String(x).toUpperCase()):['IN_APP'];const recipients=Array.isArray(body.recipients)?body.recipients.map((x:any)=>String(x)):[];return this.write('NotificationRule','NOTIFICATION_RULE_SET',notificationRuleId,{notificationRuleId,eventType:String(body.eventType).toUpperCase(),channels,recipients,severity:String(body.severity||'INFO').toUpperCase(),active:body.active!==false,notes:body.notes||null},user);}
}
