import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser, bookingScope } from '../auth/scope';
import { AuditService } from '../audit/audit.service';
const SOURCE='ANCLINE_COMMERCIAL_GUARDRAILS';
@Injectable()
export class CommercialGuardrailsService {
 constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
 private get db():any{return this.prisma as any;} private p(e:any){return (e?.payload||{}) as any;} private r(v:any){return Math.round((Number(v||0)+Number.EPSILON)*100)/100;} private internal(u:ScopeUser){this.scope.assertInternal(u);} private finance(u:ScopeUser){this.scope.assertFinanceAccess(u);}
 private events(type:string):Promise<any[]>{return this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:type},orderBy:{createdAt:'asc'}});}
 private latest(rows:any[]){const m=new Map<string,any>();for(const e of rows)m.set(String(e.objectId),e);return [...m.values()];}
 async policies(u:ScopeUser){this.internal(u);return this.latest((await this.events('CommercialPolicy')).filter((e:any)=>e.eventType==='POLICY_SET')).map((e:any)=>({policyId:e.objectId,...this.p(e),updatedAt:e.createdAt}));}
 async setPolicy(b:any,u:ScopeUser){this.finance(u);const scopeType=String(b?.scopeType||'GLOBAL').toUpperCase(),scopeKey=scopeType==='GLOBAL'?'GLOBAL':String(b?.scopeKey||'').trim();if(!['GLOBAL','CUSTOMER','LANE'].includes(scopeType)||!scopeKey)throw new BadRequestException('Valid scope is required');const payload={scopeType,scopeKey,minMarginPct:this.r(b?.minMarginPct||0),minGp:this.r(b?.minGp||0),requireQuote:b?.requireQuote!==false,requireCreditApprovalForHighRisk:b?.requireCreditApprovalForHighRisk!==false,expiryWarningDays:Math.max(0,Math.round(Number(b?.expiryWarningDays??7))),active:b?.active!==false,notes:b?.notes?String(b.notes):null,updatedBy:u.sub};const policyId=`${scopeType}:${scopeKey}`;await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'POLICY_SET',externalId:policyId,objectType:'CommercialPolicy',objectId:policyId,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'COMMERCIAL_POLICY_SET',objectType:'CommercialPolicy',objectId:policyId,detail:payload});return {policyId,...payload};}
 private buildApprovals(rows:any[]){const g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const c=ev.find((x:any)=>x.eventType==='GUARDRAIL_APPROVAL_REQUESTED');if(!c)continue;const a=ev.find((x:any)=>x.eventType==='GUARDRAIL_APPROVED'),r=ev.find((x:any)=>x.eventType==='GUARDRAIL_REJECTED');out.push({approvalId:id,...this.p(c),status:a?'APPROVED':r?'REJECTED':'PENDING',createdAt:c.createdAt});}return out;}
 async approvals(u:ScopeUser){this.internal(u);const allowed=new Set((await this.db.booking.findMany({where:bookingScope(u),select:{id:true}})).map((x:any)=>String(x.id)));return this.buildApprovals(await this.events('GuardrailApproval')).filter((x:any)=>allowed.has(String(x.bookingId))).sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());}
 async requestApproval(b:any,u:ScopeUser){this.internal(u);const bookingId=String(b?.bookingId||'');if(!bookingId)throw new BadRequestException('Booking is required');await this.scope.assertBookingAccess(u,bookingId);const existing=this.buildApprovals(await this.events('GuardrailApproval')).find((x:any)=>x.bookingId===bookingId&&x.status==='PENDING');if(existing)return existing;const check=await this.checkBooking(bookingId,u),approvalId=`CGA-${Date.now()}`,payload={approvalId,bookingId,bookingNo:check.bookingNo,reasons:check.blockers,marginPct:check.marginPct,gp:check.gp,creditRisk:check.creditRisk,note:b?.note?String(b.note):null,requestedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'GUARDRAIL_APPROVAL_REQUESTED',externalId:approvalId,objectType:'GuardrailApproval',objectId:approvalId,status:'PENDING',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'COMMERCIAL_GUARDRAIL_APPROVAL_REQUEST',objectType:'GuardrailApproval',objectId:approvalId,bookingId,detail:{reasons:check.blockers}});return payload;}
 async decideApproval(id:string,decision:string,b:any,u:ScopeUser){this.finance(u);const row=this.buildApprovals(await this.events('GuardrailApproval')).find((x:any)=>x.approvalId===id);if(!row)throw new NotFoundException('Commercial approval not found');if(row.status!=='PENDING')return row;const d=String(decision).toUpperCase();if(!['APPROVE','REJECT'].includes(d))throw new BadRequestException('Decision must be APPROVE or REJECT');await this.scope.assertBookingAccess(u,row.bookingId);const eventType=d==='APPROVE'?'GUARDRAIL_APPROVED':'GUARDRAIL_REJECTED';await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType,externalId:id,objectType:'GuardrailApproval',objectId:id,status:'COMPLETED',payload:{bookingId:row.bookingId,note:b?.note?String(b.note):null,decidedBy:u.sub},completedAt:new Date()}});return {ok:true,status:d==='APPROVE'?'APPROVED':'REJECTED'};}
 private async policyFor(b:any){const all=(await this.policies({...(b.__user||{}),role:'GLOBAL_ADMIN'} as any)).filter((x:any)=>x.active!==false),lane=`${b.origin||''}->${b.destination||''}`;return {...(all.find((x:any)=>x.scopeType==='GLOBAL')||{}),...(all.find((x:any)=>x.scopeType==='CUSTOMER'&&String(x.scopeKey)===String(b.customerId))||{}),...(all.find((x:any)=>x.scopeType==='LANE'&&x.scopeKey===lane)||{})};}
 private async credit(customerId:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:'ANCLINE_CREDIT_CONTROL',objectType:'CreditProfile',objectId:customerId},orderBy:{createdAt:'desc'},take:1});return rows[0]?this.p(rows[0]):null;}
 async checkBooking(id:string,u:ScopeUser){this.internal(u);await this.scope.assertBookingAccess(u,id);const b:any=await this.db.booking.findUnique({where:{id},include:{rateQuote:true}});if(!b)throw new NotFoundException('Booking not found');b.__user=u;const policy:any=await this.policyFor(b),q=b.rateQuote,blockers:string[]=[],warnings:string[]=[];let marginPct=0,gp=0;if(q){const sell=Number(q.sellRate||0),buy=Number(q.buyRate||0);gp=this.r(sell-buy);marginPct=sell?this.r(gp/sell*100):0;const days=Math.ceil((new Date(q.validTo).getTime()-Date.now())/86400000);if(days<0)blockers.push(`Rate quote ${q.quoteNo} expired`);else if(days<=Number(policy.expiryWarningDays??7))warnings.push(`Rate quote expires in ${days} day(s)`);if(marginPct<Number(policy.minMarginPct||0))blockers.push(`Margin ${marginPct}% is below minimum ${Number(policy.minMarginPct||0)}%`);if(gp<Number(policy.minGp||0))blockers.push(`Gross profit ${gp} is below minimum ${Number(policy.minGp||0)}`);}else if(policy.requireQuote!==false)blockers.push('An active rate quote is required');const credit=await this.credit(String(b.customerId)),creditRisk=String(credit?.riskRating||'UNRATED').toUpperCase();if(policy.requireCreditApprovalForHighRisk!==false&&(creditRisk==='HIGH'||creditRisk==='RESTRICTED'||credit?.creditHold===true))blockers.push(`Customer credit risk requires commercial approval (${creditRisk}${credit?.creditHold?' / HOLD':''})`);const approved=this.buildApprovals(await this.events('GuardrailApproval')).some((x:any)=>x.bookingId===id&&x.status==='APPROVED');return {bookingId:id,bookingNo:b.bookingNo,customerId:b.customerId,lane:`${b.origin||''}->${b.destination||''}`,quoteNo:q?.quoteNo||null,quoteValidTo:q?.validTo||null,marginPct,gp,creditRisk,creditHold:Boolean(credit?.creditHold),policy,blockers,warnings,approved,clear:blockers.length===0||approved};}
 private buildCommitments(rows:any[]){const out:any[]=[];for(const e of rows.filter((x:any)=>x.eventType==='COMMITMENT_CREATED'))out.push({commitmentId:e.objectId,...this.p(e),createdAt:e.createdAt});return out;}
 async commitments(u:ScopeUser){this.internal(u);const cs=this.buildCommitments(await this.events('VolumeCommitment')),bookings:any[]=await this.db.booking.findMany({where:bookingScope(u),select:{customerId:true,origin:true,destination:true,quantity:true,bookingDate:true,createdAt:true,status:true}});return cs.map((c:any)=>{const util=bookings.filter((b:any)=>b.customerId===c.customerId&&b.status!=='CANCELLED'&&new Date(b.bookingDate||b.createdAt)>=new Date(c.validFrom)&&new Date(b.bookingDate||b.createdAt)<=new Date(c.validTo)&&(!c.lane||c.lane===`${b.origin||''}->${b.destination||''}`)).reduce((s:number,b:any)=>s+Number(b.quantity||1),0),target=Number(c.targetQuantity||0);return {...c,utilizedQuantity:util,attainmentPct:target?this.r(util/target*100):0,remainingQuantity:Math.max(0,target-util),projectedRebateEligible:target>0&&util>=target};});}
 async createCommitment(b:any,u:ScopeUser){this.finance(u);const customerId=String(b?.customerId||''),target=Number(b?.targetQuantity);if(!customerId||!Number.isFinite(target)||target<=0)throw new BadRequestException('Customer and positive target quantity are required');const from=new Date(b.validFrom),to=new Date(b.validTo);if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||to<from)throw new BadRequestException('Invalid dates');const id=`VC-${Date.now()}`,payload={customerId,name:String(b?.name||'Volume commitment'),lane:b?.lane?String(b.lane):null,targetQuantity:this.r(target),quantityUnit:String(b?.quantityUnit||'TEU'),rebatePct:this.r(b?.rebatePct||0),currency:String(b?.currency||'USD').toUpperCase(),validFrom:from.toISOString(),validTo:to.toISOString(),notes:b?.notes?String(b.notes):null};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'COMMITMENT_CREATED',externalId:id,objectType:'VolumeCommitment',objectId:id,status:'ACTIVE',payload,completedAt:new Date()}});return {commitmentId:id,...payload};}
 async contractUtilization(u:ScopeUser){this.internal(u);const contracts:any[]=await this.db.serviceContract.findMany({where:{status:'ACTIVE'},include:{rates:true},orderBy:{validTo:'asc'}}),bookings:any[]=await this.db.booking.findMany({where:bookingScope(u),select:{customerId:true,origin:true,destination:true,quantity:true,bookingDate:true,createdAt:true,status:true}});return contracts.filter((c:any)=>String(c.partyType).toUpperCase()==='CUSTOMER').map((c:any)=>{const util=bookings.filter((b:any)=>b.customerId===c.partyId&&b.status!=='CANCELLED'&&new Date(b.bookingDate||b.createdAt)>=new Date(c.validFrom)&&new Date(b.bookingDate||b.createdAt)<=new Date(c.validTo)&&(!c.trade||c.trade===`${b.origin||''}->${b.destination||''}`)).reduce((s:number,b:any)=>s+Number(b.quantity||1),0),min=Number(c.minimumQuantity||0);return {contractId:c.id,contractNo:c.contractNo,customerId:c.partyId,trade:c.trade,validFrom:c.validFrom,validTo:c.validTo,minimumQuantity:min,quantityUnit:c.quantityUnit,utilizedQuantity:util,attainmentPct:min?this.r(util/min*100):null,remainingQuantity:min?Math.max(0,min-util):null,rateLines:c.rates.length,status:new Date(c.validTo).getTime()<Date.now()?'EXPIRED':min&&util<min?'UNDER_COMMITMENT':'ON_TRACK'};});}
 async dashboard(u:ScopeUser){this.internal(u);const [policies,commitments,approvals,contracts]=await Promise.all([this.policies(u),this.commitments(u),this.approvals(u),this.contractUtilization(u)]),rows:any[]=await this.db.booking.findMany({where:bookingScope(u),select:{id:true,status:true}}),checks:any[]=[];for(const b of rows.filter((x:any)=>['CARRIER_CONFIRMATION','FINAL_APPROVAL','CONFIRMED'].includes(String(x.status))).slice(0,100)){try{checks.push(await this.checkBooking(b.id,u));}catch{}}return {policies,commitments,approvals,contracts,bookingChecks:checks,summary:{activePolicies:policies.filter((x:any)=>x.active!==false).length,pendingApprovals:approvals.filter((x:any)=>x.status==='PENDING').length,blockedBookings:checks.filter((x:any)=>!x.clear).length,expiringRates:checks.filter((x:any)=>x.warnings?.length).length,underCommitmentContracts:contracts.filter((x:any)=>x.status==='UNDER_COMMITMENT').length,rebateEligible:commitments.filter((x:any)=>x.projectedRebateEligible).length}};}
}
