import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser, bookingScope } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SOURCE='ANCLINE_COMMERCIAL_PROFITABILITY';

@Injectable()
export class CommercialProfitabilityService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private get db():any{return this.prisma as any;}
  private r(v:any){return Math.round((Number(v||0)+Number.EPSILON)*100)/100;}
  private p(e:any){return (e?.payload||{}) as any;}
  private internal(u:ScopeUser){this.scope.assertInternal(u);}
  private finance(u:ScopeUser){this.scope.assertFinanceAccess(u);}
  private exposure(c:any){
    const daysAfter=(free:any,end:any)=>{if(!free)return 0;const a=new Date(free).getTime(),b=new Date(end||new Date()).getTime();if(Number.isNaN(a)||Number.isNaN(b)||b<=a)return 0;return Math.ceil((b-a)/86400000);};
    const demDays=daysAfter(c.demurrageFreeUntil,c.deliveryAt),detDays=daysAfter(c.detentionFreeUntil,c.emptyReturnedAt);
    return {demurrageDays:demDays,detentionDays:detDays,demurrage:this.r(demDays*Number(c.demurrageRatePerDay||0)),detention:this.r(detDays*Number(c.detentionRatePerDay||0)),currency:String(c.freeTimeCurrency||'USD').toUpperCase()};
  }
  private async scopedBookings(u:ScopeUser,period?:string):Promise<any[]>{
    const where:any={...bookingScope(u)};if(period&&/^\d{4}-\d{2}$/.test(period)){const start=new Date(`${period}-01T00:00:00Z`),end=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,1));where.createdAt={gte:start,lt:end};}
    return this.db.booking.findMany({where,select:{id:true,bookingNo:true,shipmentNo:true,customerId:true,origin:true,destination:true,status:true,currency:true,createdAt:true,containers:{select:{id:true,containerNo:true,demurrageFreeUntil:true,deliveryAt:true,demurrageRatePerDay:true,detentionFreeUntil:true,emptyReturnedAt:true,detentionRatePerDay:true,freeTimeCurrency:true}}},orderBy:{createdAt:'desc'},take:1000});
  }
  private async organizations(ids:string[]):Promise<Map<string,string>>{if(!ids.length)return new Map<string,string>();const rows:any[]=await this.db.organization.findMany({where:{id:{in:ids}},select:{id:true,name:true}}),m=new Map<string,string>();for(const x of rows)m.set(String(x.id),String(x.name));return m;}
  private async financeLines(ids:string[]):Promise<any[]>{if(!ids.length)return [];return this.db.financeLine.findMany({where:{bookingId:{in:ids},status:{not:'CANCELLED'}},orderBy:{createdAt:'asc'}});}
  private jobRow(b:any,lines:any[],customerName:string){
    const byCur:string[]=[...new Set<string>(lines.map((x:any)=>String(x.currency||b.currency||'USD').toUpperCase()))],rows:any[]=[];
    for(const currency of byCur){const cur=lines.filter((x:any)=>String(x.currency).toUpperCase()===currency),quoteRev=cur.filter((x:any)=>x.type==='REVENUE'&&x.source==='RATE_QUOTE').reduce((s:number,x:any)=>s+Number(x.finalAmount??x.amount),0),quoteCost=cur.filter((x:any)=>x.type==='COST'&&x.source==='RATE_QUOTE').reduce((s:number,x:any)=>s+Number(x.finalAmount??x.amount),0),actualRev=cur.filter((x:any)=>x.type==='REVENUE'&&x.source!=='RATE_QUOTE').reduce((s:number,x:any)=>s+Number(x.finalAmount??x.amount),0);
      const quoteCostByCharge=new Map<string,number>();for(const x of cur.filter((x:any)=>x.type==='COST'&&x.source==='RATE_QUOTE'))quoteCostByCharge.set(String(x.chargeCode),this.r((quoteCostByCharge.get(String(x.chargeCode))||0)+Number(x.finalAmount??x.amount)));
      const actualCostByCharge=new Map<string,number>();for(const x of cur.filter((x:any)=>x.type==='COST'&&x.source!=='RATE_QUOTE'))actualCostByCharge.set(String(x.chargeCode),this.r((actualCostByCharge.get(String(x.chargeCode))||0)+Number(x.finalAmount??x.amount)));
      const keys=new Set<string>([...quoteCostByCharge.keys(),...actualCostByCharge.keys()]);let forecastCost=0;for(const k of keys)forecastCost+=actualCostByCharge.has(k)?Number(actualCostByCharge.get(k)):Number(quoteCostByCharge.get(k)||0);
      const revenue=actualRev>0?actualRev:quoteRev,gp=this.r(revenue-forecastCost),quotedGp=this.r(quoteRev-quoteCost),leakage=this.r(forecastCost-quoteCost),marginPct=revenue?this.r(gp/revenue*100):0;
      rows.push({bookingId:b.id,bookingNo:b.bookingNo,shipmentNo:b.shipmentNo,customerId:b.customerId,customerName,origin:b.origin,destination:b.destination,lane:`${b.origin||'?'} → ${b.destination||'?'}`,status:b.status,currency,quotedRevenue:this.r(quoteRev),quotedCost:this.r(quoteCost),quotedGp,forecastRevenue:this.r(revenue),forecastCost:this.r(forecastCost),forecastGp:gp,marginPct,leakage,leakagePct:quoteCost?this.r(leakage/quoteCost*100):0,marginStatus:gp<0?'LOSS':leakage>0.005?'LEAKAGE':leakage<-0.005?'SAVING':'ON_PLAN'});
    }return rows;
  }
  async profitability(period:string|undefined,u:ScopeUser){
    this.internal(u);const bookings:any[]=await this.scopedBookings(u,period),ids=bookings.map((x:any)=>String(x.id)),lines:any[]=await this.financeLines(ids),cust=await this.organizations([...new Set<string>(bookings.map((x:any)=>String(x.customerId||'')).filter(Boolean))]);const byBooking=new Map<string,any[]>();for(const l of lines){if(!byBooking.has(String(l.bookingId)))byBooking.set(String(l.bookingId),[]);byBooking.get(String(l.bookingId))!.push(l);}const jobs:any[]=[];for(const b of bookings)jobs.push(...this.jobRow(b,byBooking.get(String(b.id))||[],cust.get(String(b.customerId))||'Unassigned customer'));
    const group=(field:string)=>{const m=new Map<string,any>();for(const j of jobs){const k=`${j.currency}:${j[field]||'Unassigned'}`;if(!m.has(k))m.set(k,{name:j[field]||'Unassigned',currency:j.currency,revenue:0,cost:0,gp:0,jobs:0,leakage:0});const x=m.get(k)!;x.revenue=this.r(x.revenue+j.forecastRevenue);x.cost=this.r(x.cost+j.forecastCost);x.gp=this.r(x.gp+j.forecastGp);x.leakage=this.r(x.leakage+j.leakage);x.jobs++;x.marginPct=x.revenue?this.r(x.gp/x.revenue*100):0;}return Array.from(m.values()).sort((a:any,b:any)=>b.gp-a.gp);};
    return {period:period||null,jobs,byCustomer:group('customerName'),byLane:group('lane'),summary:{jobs:jobs.length,lossJobs:jobs.filter((x:any)=>x.marginStatus==='LOSS').length,leakageJobs:jobs.filter((x:any)=>x.marginStatus==='LEAKAGE').length,totalByCurrency:[...new Set<string>(jobs.map((x:any)=>String(x.currency)))].map((currency:string)=>({currency,revenue:this.r(jobs.filter((x:any)=>x.currency===currency).reduce((s:number,x:any)=>s+x.forecastRevenue,0)),cost:this.r(jobs.filter((x:any)=>x.currency===currency).reduce((s:number,x:any)=>s+x.forecastCost,0)),gp:this.r(jobs.filter((x:any)=>x.currency===currency).reduce((s:number,x:any)=>s+x.forecastGp,0)),leakage:this.r(jobs.filter((x:any)=>x.currency===currency).reduce((s:number,x:any)=>s+x.leakage,0))}))}};
  }
  private async recoveryEvents():Promise<any[]>{return this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:'RecoveryCase'},orderBy:{createdAt:'asc'}});}
  private buildCases(events:any[]){const g=new Map<string,any[]>();for(const e of events){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const c=ev.find((x:any)=>x.eventType==='RECOVERY_PROPOSED');if(!c)continue;const approved=ev.find((x:any)=>x.eventType==='RECOVERY_APPROVED'),rejected=ev.find((x:any)=>x.eventType==='RECOVERY_REJECTED');out.push({caseId:id,...this.p(c),status:approved?'APPROVED':rejected?'REJECTED':'PENDING',approvedAt:approved?.createdAt||null,rejectedAt:rejected?.createdAt||null,financeLineId:approved?this.p(approved).financeLineId||null:null,createdAt:c.createdAt});}return out;}
  async recoveries(u:ScopeUser){this.internal(u);const bookings:any[]=await this.scopedBookings(u),allowed=new Set<string>(bookings.map((x:any)=>String(x.id))),ids=bookings.map((x:any)=>String(x.id)),lines:any[]=await this.financeLines(ids),cases=this.buildCases(await this.recoveryEvents()),existingRefs=new Set<string>(lines.filter((x:any)=>x.source==='COMMERCIAL_RECOVERY').map((x:any)=>String(x.reference||''))),opportunities:any[]=[];
    for(const b of bookings){for(const c of b.containers||[]){const x=this.exposure(c);for(const kind of ['DEMURRAGE','DETENTION']){const amount=kind==='DEMURRAGE'?x.demurrage:x.detention;if(amount<=0)continue;const ref=`RECOVERY:${kind}:${c.id}`,already=existingRefs.has(ref)||cases.some((z:any)=>z.opportunityRef===ref&&z.status!=='REJECTED');opportunities.push({opportunityRef:ref,bookingId:b.id,bookingNo:b.bookingNo,containerId:c.id,containerNo:c.containerNo,type:kind,chargeCode:kind,amount,currency:x.currency,status:already?'IN_PROCESS':'OPEN'});}}
      const bl:any[]=lines.filter((x:any)=>String(x.bookingId)===String(b.id)),chargeCodes:string[]=[...new Set<string>(bl.filter((x:any)=>x.type==='COST'&&x.source!=='RATE_QUOTE'&&/(SURCHARGE|BAF|CAF|PSS|THC|DOC|HANDLING)/i.test(String(x.chargeCode))).map((x:any)=>String(x.chargeCode)))];for(const chargeCode of chargeCodes){const currencies:string[]=[...new Set<string>(bl.filter((x:any)=>String(x.chargeCode)===chargeCode).map((x:any)=>String(x.currency)))];for(const currency of currencies){const cost=bl.filter((x:any)=>x.type==='COST'&&x.source!=='RATE_QUOTE'&&x.chargeCode===chargeCode&&x.currency===currency).reduce((s:number,x:any)=>s+Number(x.finalAmount??x.amount),0),rev=bl.filter((x:any)=>x.type==='REVENUE'&&x.source!=='RATE_QUOTE'&&x.chargeCode===chargeCode&&x.currency===currency).reduce((s:number,x:any)=>s+Number(x.finalAmount??x.amount),0),gap=this.r(cost-rev);if(gap<=0.005)continue;const ref=`RECOVERY:SURCHARGE:${b.id}:${currency}:${chargeCode}`,already=existingRefs.has(ref)||cases.some((z:any)=>z.opportunityRef===ref&&z.status!=='REJECTED');opportunities.push({opportunityRef:ref,bookingId:b.id,bookingNo:b.bookingNo,type:'SURCHARGE',chargeCode,amount:gap,currency,status:already?'IN_PROCESS':'OPEN'});}}
    }
    return {opportunities,cases:cases.filter((x:any)=>allowed.has(String(x.bookingId))).sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())};
  }
  async proposeRecovery(b:any,u:ScopeUser){this.internal(u);const bookingId=String(b?.bookingId||'');if(!bookingId)throw new BadRequestException('Booking is required');await this.scope.assertBookingAccess(u,bookingId);const amount=Number(b?.amount);if(!Number.isFinite(amount)||amount<=0)throw new BadRequestException('Recovery amount must be greater than zero');const currency=String(b?.currency||'USD').toUpperCase(),opportunityRef=String(b?.opportunityRef||'').trim(),chargeCode=String(b?.chargeCode||b?.type||'RECOVERY').toUpperCase();if(!opportunityRef)throw new BadRequestException('Opportunity reference is required');const existing=this.buildCases(await this.recoveryEvents()).find((x:any)=>x.opportunityRef===opportunityRef&&x.status!=='REJECTED');if(existing)return existing;const caseId=`RC-${Date.now()}`;const payload={caseId,opportunityRef,bookingId,bookingNo:b?.bookingNo||null,type:String(b?.type||'RECOVERY').toUpperCase(),chargeCode,amount:this.r(amount),currency,reason:b?.reason?String(b.reason):null,proposedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'RECOVERY_PROPOSED',externalId:caseId,objectType:'RecoveryCase',objectId:caseId,status:'PENDING',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'COMMERCIAL_RECOVERY_PROPOSE',objectType:'RecoveryCase',objectId:caseId,bookingId,detail:{opportunityRef,amount:this.r(amount),currency,chargeCode}});return payload;}
  async decideRecovery(caseId:string,decision:string,b:any,u:ScopeUser){this.finance(u);const cases=this.buildCases(await this.recoveryEvents()),row=cases.find((x:any)=>x.caseId===caseId);if(!row)throw new NotFoundException('Recovery case not found');if(row.status!=='PENDING')return row;await this.scope.assertBookingAccess(u,row.bookingId);const d=String(decision).toUpperCase();if(!['APPROVE','REJECT'].includes(d))throw new BadRequestException('Decision must be APPROVE or REJECT');if(d==='REJECT'){await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'RECOVERY_REJECTED',externalId:caseId,objectType:'RecoveryCase',objectId:caseId,status:'COMPLETED',payload:{caseId,reason:b?.reason?String(b.reason):null,rejectedBy:u.sub},completedAt:new Date()}});return {ok:true,status:'REJECTED'};}
    const booking=await this.db.booking.findUnique({where:{id:row.bookingId},select:{customerId:true}});let fl=await this.db.financeLine.findFirst({where:{bookingId:row.bookingId,source:'COMMERCIAL_RECOVERY',reference:row.opportunityRef}});if(!fl)fl=await this.db.financeLine.create({data:{bookingId:row.bookingId,type:'REVENUE',chargeCode:row.chargeCode,description:`Commercial recovery ${row.type}`,partyId:booking?.customerId||null,billingPartyId:booking?.customerId||null,amount:row.amount,currency:row.currency,status:'WIP',source:'COMMERCIAL_RECOVERY',reference:row.opportunityRef,invoiceReady:true}});await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'RECOVERY_APPROVED',externalId:caseId,objectType:'RecoveryCase',objectId:caseId,status:'COMPLETED',payload:{caseId,financeLineId:fl.id,approvedBy:u.sub},completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'COMMERCIAL_RECOVERY_APPROVE',objectType:'RecoveryCase',objectId:caseId,bookingId:row.bookingId,detail:{financeLineId:fl.id,amount:row.amount,currency:row.currency}});return {ok:true,status:'APPROVED',financeLineId:fl.id};}
  private async marginEvents():Promise<any[]>{return this.db.integrationEvent.findMany({where:{sourceSystem:SOURCE,objectType:'MarginException'},orderBy:{createdAt:'asc'}});}
  private buildExceptions(events:any[]){const g=new Map<string,any[]>();for(const e of events){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const c=ev.find((x:any)=>x.eventType==='MARGIN_EXCEPTION_SUBMITTED');if(!c)continue;const a=ev.find((x:any)=>x.eventType==='MARGIN_EXCEPTION_APPROVED'),r=ev.find((x:any)=>x.eventType==='MARGIN_EXCEPTION_REJECTED');out.push({exceptionId:id,...this.p(c),status:a?'APPROVED':r?'REJECTED':'PENDING',createdAt:c.createdAt});}return out;}
  async marginExceptions(u:ScopeUser){this.internal(u);const bookings:any[]=await this.scopedBookings(u),allowed=new Set<string>(bookings.map((x:any)=>String(x.id)));return this.buildExceptions(await this.marginEvents()).filter((x:any)=>allowed.has(String(x.bookingId))).sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());}
  async submitMarginException(b:any,u:ScopeUser){this.internal(u);const bookingId=String(b?.bookingId||'');if(!bookingId)throw new BadRequestException('Booking is required');await this.scope.assertBookingAccess(u,bookingId);const currency=String(b?.currency||'USD').toUpperCase(),reason=String(b?.reason||'').trim();if(!reason)throw new BadRequestException('Reason is required');const exceptionId=`ME-${Date.now()}`,payload={exceptionId,bookingId,bookingNo:b?.bookingNo||null,currency,forecastGp:this.r(b?.forecastGp),marginPct:this.r(b?.marginPct),leakage:this.r(b?.leakage),reason,requestedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:'MARGIN_EXCEPTION_SUBMITTED',externalId:exceptionId,objectType:'MarginException',objectId:exceptionId,status:'PENDING',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'MARGIN_EXCEPTION_SUBMIT',objectType:'MarginException',objectId:exceptionId,bookingId,detail:{currency,forecastGp:payload.forecastGp,marginPct:payload.marginPct,leakage:payload.leakage}});return payload;}
  async decideMarginException(id:string,decision:string,b:any,u:ScopeUser){this.finance(u);const rows=this.buildExceptions(await this.marginEvents()),row=rows.find((x:any)=>x.exceptionId===id);if(!row)throw new NotFoundException('Margin exception not found');if(row.status!=='PENDING')return row;await this.scope.assertBookingAccess(u,row.bookingId);const d=String(decision).toUpperCase();if(!['APPROVE','REJECT'].includes(d))throw new BadRequestException('Decision must be APPROVE or REJECT');await this.db.integrationEvent.create({data:{sourceSystem:SOURCE,eventType:d==='APPROVE'?'MARGIN_EXCEPTION_APPROVED':'MARGIN_EXCEPTION_REJECTED',externalId:id,objectType:'MarginException',objectId:id,status:'COMPLETED',payload:{exceptionId:id,reason:b?.reason?String(b.reason):null,decidedBy:u.sub},completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:`MARGIN_EXCEPTION_${d}`,objectType:'MarginException',objectId:id,bookingId:row.bookingId});return {ok:true,status:d==='APPROVE'?'APPROVED':'REJECTED'};}
  async dashboard(u:ScopeUser){this.internal(u);const [p,r,e]=await Promise.all([this.profitability(undefined,u),this.recoveries(u),this.marginExceptions(u)]);return {jobs:p.summary.jobs,lossJobs:p.summary.lossJobs,leakageJobs:p.summary.leakageJobs,openRecoveries:r.opportunities.filter((x:any)=>x.status==='OPEN').length,pendingRecoveryApprovals:r.cases.filter((x:any)=>x.status==='PENDING').length,pendingMarginExceptions:e.filter((x:any)=>x.status==='PENDING').length,recoverableByCurrency:[...new Set<string>(r.opportunities.filter((x:any)=>x.status==='OPEN').map((x:any)=>String(x.currency)))].map((currency:string)=>({currency,amount:this.r(r.opportunities.filter((x:any)=>x.status==='OPEN'&&x.currency===currency).reduce((s:number,x:any)=>s+x.amount,0))}))};}
}
