'use client';

import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtMoney,requireToken} from '../../lib/api';

const nowPeriod=()=>new Date().toISOString().slice(0,7);
export default function FinanceCloseExecutionPage(){
  const [token,setToken]=useState('');const [period,setPeriod]=useState(nowPeriod());const [data,setData]=useState<any>({});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [policy,setPolicy]=useState<any>({arAgingHoldDays:90,requireBankFullyMatched:true,requireTaxFiled:true,requireIntercompanySettled:true,requireEntityCertification:true});
  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t,nowPeriod());},[]);
  async function load(t=token,p=period){if(!t)return;setBusy(true);setMessage('');try{const d=await api(`/finance-close-execution/dashboard/${encodeURIComponent(p)}`,t);setData(d||{});if(d?.policy)setPolicy(d.policy);}catch(e:any){setMessage(e.message||'Unable to load finance close execution.');}finally{setBusy(false);}}
  async function post(path:string,body:any,success:string){setBusy(true);setMessage('');try{await api(path,token,{method:'POST',body:JSON.stringify(body||{})});setMessage(success);await load();}catch(e:any){setMessage(e.message||'Action failed.');}finally{setBusy(false);}}
  const tax=data?.tax||{},entities=data?.entities||[],blockers=data?.blockers||[];
  return <WorkspaceShell title="Finance Close Execution" subtitle="Execute the period close with bank, AR aging, tax, intercompany and entity maker-checker controls" active="/finance-close-execution" actions={<button className="btn" disabled={busy} onClick={()=>void load()}>{busy?'Working…':'Refresh'}</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="card" style={{marginBottom:12,display:'flex',gap:10,alignItems:'end',flexWrap:'wrap'}}><label style={{minWidth:200}}><span style={labelStyle}>Period</span><input type="month" style={fieldStyle} value={period} onChange={e=>{setPeriod(e.target.value);void load(token,e.target.value);}}/></label><button className="btn" disabled={busy||data?.periodStatus==='CLOSED'} onClick={()=>void post(`/finance-close-execution/period/${period}/close`,{},`Period ${period} closed.`)}>Execute Global Close</button></div>
    <div className="grid" style={{marginBottom:12}}><div className="card"><div className="sub">EXECUTION</div><div className="kpi">{data?.ready?'READY':'BLOCKED'}</div></div><div className="card"><div className="sub">BLOCKERS</div><div className="kpi">{data?.blockerCount||0}</div></div><div className="card"><div className="sub">GL PERIOD</div><div className="kpi">{data?.periodStatus||'OPEN'}</div></div><div className="card"><div className="sub">TAX STATUS</div><div className="kpi">{tax?.filing?.status||'NOT PREPARED'}</div></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Close Policy</h3><div style={formGrid}><label><span style={labelStyle}>AR Aging Hold Days</span><input type="number" min={0} max={3650} style={fieldStyle} value={policy.arAgingHoldDays??90} onChange={e=>setPolicy({...policy,arAgingHoldDays:Number(e.target.value)})}/></label>{[['requireBankFullyMatched','Require bank fully matched'],['requireTaxFiled','Require tax filed'],['requireIntercompanySettled','Require intercompany settled'],['requireEntityCertification','Require entity certification']].map(([k,l])=><label key={k}><span style={labelStyle}>{l}</span><select style={fieldStyle} value={policy[k]?'YES':'NO'} onChange={e=>setPolicy({...policy,[k]:e.target.value==='YES'})}><option>YES</option><option>NO</option></select></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void post('/finance-close-execution/policy',policy,'Close policy saved.')}>Save Policy</button></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Tax / VAT Filing</h3><div className="grid" style={{marginBottom:10}}>{(tax.rows||[]).map((x:any)=><div className="card" key={`${x.currency}-${x.taxCode}`}><div className="sub">{x.taxCode} · {x.currency}</div><b>{fmtMoney(x.taxAmount,x.currency)}</b><div className="sub">Base {fmtMoney(x.taxableBase,x.currency)}</div></div>)}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{!tax?.filing&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-execution/tax/${period}/prepare`,{},'Tax filing prepared.')}>Prepare Tax Filing</button>}{tax?.filing?.status==='PREPARED'&&<button className="btn" disabled={busy} onClick={()=>{const ref=window.prompt('Tax filing reference','');if(ref)void post(`/finance-close-execution/tax/${period}/file`,{filingReference:ref},'Tax filing marked filed.');}}>Mark Filed</button>}</div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Legal Entity Certification</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Entity</th><th>Status</th><th>Requester</th><th>Approver</th><th>Actions</th></tr></thead><tbody>{entities.map((x:any)=><tr key={x.entityId}><td>{x.entityCode} · {x.entityName}</td><td><span className="status">{x.status||'OPEN'}</span></td><td>{x.request?.requestedBy||'-'}</td><td>{x.approval?.approvedBy||'-'}</td><td style={{display:'flex',gap:6,flexWrap:'wrap'}}>{data?.periodStatus==='CLOSED'&&x.status!=='CERTIFIED'&&!x.request&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-execution/entity-approvals/${encodeURIComponent(x.entityId)}/${period}/request`,{},`Certification requested for ${x.entityCode}.`)}>Request Approval</button>}{x.request&&x.status!=='CERTIFIED'&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-execution/entity-approvals/${encodeURIComponent(x.entityId)}/${period}/approve`,{},`${x.entityCode} certified.`)}>Approve / Certify</button>}</td></tr>)}{!entities.length&&<tr><td colSpan={5}>No legal entities configured.</td></tr>}</tbody></table></div></div>

    <div className="card"><h3 style={sectionTitle}>Execution Blockers</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Area</th><th>Type</th><th>Object</th><th>Message</th></tr></thead><tbody>{blockers.map((x:any,i:number)=><tr key={`${x.area}-${x.type}-${x.objectId||i}`}><td>{x.area}</td><td><span className="status">{x.type}</span></td><td>{x.objectId||'-'}</td><td>{x.message}</td></tr>)}{!blockers.length&&<tr><td colSpan={4}>No close-execution blockers.</td></tr>}</tbody></table></div></div>
  </WorkspaceShell>;
}
