'use client';

import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,fmtMoney,requireToken} from '../../lib/api';

const nowPeriod=()=>new Date().toISOString().slice(0,7);
export default function FinanceClosePackPage(){
  const [token,setToken]=useState('');const [period,setPeriod]=useState(nowPeriod());const [data,setData]=useState<any>({});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t,nowPeriod());},[]);
  async function load(t=token,p=period){if(!t)return;setBusy(true);setMessage('');try{setData(await api(`/finance-close-pack/dashboard/${encodeURIComponent(p)}`,t));}catch(e:any){setMessage(e.message||'Unable to load finance close pack.');}finally{setBusy(false);}}
  async function post(path:string,body:any,success:string){setBusy(true);setMessage('');try{await api(path,token,{method:'POST',body:JSON.stringify(body||{})});setMessage(success);await load();}catch(e:any){setMessage(e.message||'Action failed.');}finally{setBusy(false);}}
  const k=data?.kpis||{},recs=data?.reconciliations||[],suspense=data?.suspense||[],aged=data?.agedAp||[],signoffs=data?.signoffs||[],group=data?.group||{};
  async function reconcile(r:any){const ref=window.prompt('Supporting evidence / reconciliation reference',r.supportReference||'');if(ref===null)return;await post(`/finance-close-pack/reconciliations/${encodeURIComponent(r.entityId)}/${period}`,{account:r.account,currency:r.currency,status:'RECONCILED',variance:0,supportReference:ref},`${r.account} reconciled.`);}
  async function resolveSuspense(x:any){const resolution=window.prompt('Resolution','Allocated / corrected');if(!resolution)return;const reference=window.prompt('Resolution reference',x.reference||'');if(!reference)return;await post(`/finance-close-pack/suspense/${period}/${encodeURIComponent(x.itemId)}/resolve`,{resolution,reference},'Suspense item resolved.');}
  return <WorkspaceShell title="Legal Entity / Group Close Pack" subtitle="Balance-sheet reconciliations, suspense, aged AP, entity sign-off evidence and consolidated group certification" active="/finance-close-pack" actions={<button className="btn" disabled={busy} onClick={()=>void load()}>{busy?'Working…':'Refresh'}</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="card" style={{marginBottom:12,display:'flex',gap:10,alignItems:'end',flexWrap:'wrap'}}><label style={{minWidth:200}}><span className="sub">PERIOD</span><input type="month" style={fieldStyle} value={period} onChange={e=>{setPeriod(e.target.value);void load(token,e.target.value);}}/></label>{group.status==='OPEN'&&data?.ready&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/group-certification/${period}/request`,{},'Group close certification requested.')}>Request Group Certification</button>}{group.status==='REVIEW'&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/group-certification/${period}/approve`,{},'Group close certified.')}>Approve Group Certification</button>}</div>
    <div className="grid" style={{marginBottom:12}}><div className="card"><div className="sub">PACK STATUS</div><div className="kpi">{data?.ready?'READY':'BLOCKED'}</div></div><div className="card"><div className="sub">OPEN RECONCILIATIONS</div><div className="kpi">{k.openReconciliations||0}</div></div><div className="card"><div className="sub">SUSPENSE</div><div className="kpi">{k.suspenseItems||0}</div></div><div className="card"><div className="sub">AGED AP</div><div className="kpi">{k.agedApExceptions||0}</div></div><div className="card"><div className="sub">ENTITY SIGN-OFF</div><div className="kpi">{k.entityApproved||0}/{k.entityTotal||0}</div></div><div className="card"><div className="sub">GROUP</div><div className="kpi">{k.groupStatus||'OPEN'}</div></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Balance Sheet Reconciliations</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Entity</th><th>Account</th><th>Currency</th><th>Balance</th><th>Status</th><th>Evidence</th><th></th></tr></thead><tbody>{recs.map((r:any)=><tr key={r.reconciliationId}><td>{r.entityCode}</td><td>{r.account}</td><td>{r.currency}</td><td>{fmtMoney(r.balance,r.currency)}</td><td><span className="status">{r.status}</span></td><td>{r.supportReference||'-'}</td><td>{r.status!=='RECONCILED'&&<button className="btn" disabled={busy} onClick={()=>void reconcile(r)}>Reconcile</button>}</td></tr>)}{!recs.length&&<tr><td colSpan={7}>No balance-sheet accounts found for {period}.</td></tr>}</tbody></table></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Suspense / Unallocated Cash</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Type</th><th>Reference</th><th>Amount</th><th>Message</th><th></th></tr></thead><tbody>{suspense.map((x:any)=><tr key={x.itemId}><td>{x.type}</td><td>{x.reference}</td><td>{fmtMoney(x.amount,x.currency)}</td><td>{x.message}</td><td><button className="btn" disabled={busy} onClick={()=>void resolveSuspense(x)}>Resolve</button></td></tr>)}{!suspense.length&&<tr><td colSpan={5}>No open suspense or unallocated-cash items.</td></tr>}</tbody></table></div></div>

    <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Aged AP Exceptions</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Invoice</th><th>Supplier</th><th>Balance</th><th>Days Overdue</th></tr></thead><tbody>{aged.map((x:any)=><tr key={x.invoiceNo}><td>{x.invoiceNo}</td><td>{x.partyName||'-'}</td><td>{fmtMoney(x.balance,x.currency)}</td><td>{x.daysOverdue}</td></tr>)}{!aged.length&&<tr><td colSpan={4}>No aged AP close exceptions.</td></tr>}</tbody></table></div></div>

    <div className="card"><h3 style={sectionTitle}>Legal Entity Sign-off Evidence</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Entity</th><th>Status</th><th>Open Recs</th><th>Suspense</th><th>Aged AP</th><th>Requester</th><th>Approver</th><th>Actions</th></tr></thead><tbody>{signoffs.map((x:any)=><tr key={x.entityId}><td>{x.entityCode} · {x.entityName}</td><td><span className="status">{x.status}</span></td><td>{x.openReconciliations}</td><td>{x.openSuspense}</td><td>{x.agedApExceptions}</td><td>{x.request?.requestedBy||'-'}</td><td>{x.approval?.approvedBy||'-'}</td><td style={{display:'flex',gap:6,flexWrap:'wrap'}}>{x.status==='OPEN'&&x.ready&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/signoffs/${encodeURIComponent(x.entityId)}/${period}/request`,{},`Sign-off requested for ${x.entityCode}.`)}>Request</button>}{x.status==='REVIEW'&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/signoffs/${encodeURIComponent(x.entityId)}/${period}/approve`,{},`${x.entityCode} close pack approved.`)}>Approve</button>}</td></tr>)}{!signoffs.length&&<tr><td colSpan={8}>No legal entities configured.</td></tr>}</tbody></table></div></div>
  </WorkspaceShell>;
}
