'use client';

import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

const nowPeriod=()=>new Date().toISOString().slice(0,7);
export default function FinanceClosePackPage(){
  const [token,setToken]=useState('');const [period,setPeriod]=useState(nowPeriod());const [data,setData]=useState<any>({});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t,nowPeriod());},[]);
  async function load(t=token,p=period){if(!t)return;setBusy(true);setMessage('');try{setData(await api(`/finance-close-pack/dashboard/${encodeURIComponent(p)}`,t));}catch(e:any){setMessage(e.message||'Unable to load finance close pack.');}finally{setBusy(false);}}
  async function post(path:string,body:any,success:string){setBusy(true);setMessage('');try{await api(path,token,{method:'POST',body:JSON.stringify(body||{})});setMessage(success);await load();}catch(e:any){setMessage(e.message||'Action failed.');}finally{setBusy(false);}}
  const entities=data?.entities||[];
  return <WorkspaceShell title="Legal Entity / Group Close Pack" subtitle="Balance-sheet reconciliation, suspense, aged AP, sign-off evidence and group certification" active="/finance-close-pack" actions={<button className="btn" disabled={busy} onClick={()=>void load()}>{busy?'Working…':'Refresh'}</button>}>
    {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
    <div className="card" style={{marginBottom:12,display:'flex',gap:10,alignItems:'end',flexWrap:'wrap'}}><label style={{minWidth:200}}><span style={labelStyle}>Period</span><input type="month" style={fieldStyle} value={period} onChange={e=>{setPeriod(e.target.value);void load(token,e.target.value);}}/></label>{data?.approvedEntityPacks===data?.entityCount&&data?.entityCount>0&&!data?.group?.request&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/group/${period}/request-certification`,{},'Group certification requested.')}>Request Group Certification</button>}{data?.group?.request&&data?.group?.status!=='CERTIFIED'&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/group/${period}/approve-certification`,{},'Group close certified.')}>Approve Group Certification</button>}</div>
    <div className="grid" style={{marginBottom:12}}><div className="card"><div className="sub">LEGAL ENTITIES</div><div className="kpi">{data?.entityCount||0}</div></div><div className="card"><div className="sub">READY PACKS</div><div className="kpi">{data?.readyEntities||0}</div></div><div className="card"><div className="sub">APPROVED PACKS</div><div className="kpi">{data?.approvedEntityPacks||0}</div></div><div className="card"><div className="sub">BLOCKERS</div><div className="kpi">{data?.totalBlockers||0}</div></div><div className="card"><div className="sub">GROUP STATUS</div><div className="kpi">{data?.group?.status||'OPEN'}</div></div></div>
    <div className="card"><h3 style={sectionTitle}>Entity Close Pack Status</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Entity</th><th>Ready</th><th>Blockers</th><th>Unreconciled</th><th>Suspense</th><th>AP 90+</th><th>Sign-off</th><th>Actions</th></tr></thead><tbody>{entities.map((x:any)=><tr key={x.entityId}><td>{x.entityCode} · {x.entityName}</td><td><span className="status">{x.ready?'READY':'BLOCKED'}</span></td><td>{x.blockers}</td><td>{x.unreconciled}</td><td>{x.openSuspense}</td><td>{x.agedAP90}</td><td><span className="status">{x.signoffStatus}</span></td><td style={{display:'flex',gap:6,flexWrap:'wrap'}}><a className="btn" href={`/finance-close-pack/${encodeURIComponent(x.entityId)}?period=${period}`}>Open Pack</a>{x.ready&&x.signoffStatus==='OPEN'&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/entity/${encodeURIComponent(x.entityId)}/${period}/request-signoff`,{},`Sign-off requested for ${x.entityCode}.`)}>Request Sign-off</button>}{x.signoffStatus==='REVIEW'&&<button className="btn" disabled={busy} onClick={()=>void post(`/finance-close-pack/entity/${encodeURIComponent(x.entityId)}/${period}/approve-signoff`,{},`${x.entityCode} close pack approved.`)}>Approve</button>}</td></tr>)}{!entities.length&&<tr><td colSpan={8}>No legal entities configured.</td></tr>}</tbody></table></div></div>
  </WorkspaceShell>;
}
