'use client';
import {useEffect,useState} from 'react';
import WorkspaceShell,{fieldStyle,formGrid,labelStyle,sectionTitle} from '../../components/WorkspaceShell';
import {api,requireToken} from '../../lib/api';

export default function SalesCrmPage(){
 const [token,setToken]=useState(''),[data,setData]=useState<any>({summary:{},leads:[],opportunities:[],tenders:[],pipelineByCurrency:[],lossReasons:[]}),[customers,setCustomers]=useState<any[]>([]),[organizations,setOrganizations]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null),[quotes,setQuotes]=useState<any[]>([]);
 const [lead,setLead]=useState<any>({organizationId:'',organizationName:'',inquiryType:'EMAIL',inquiryTypeLabel:'Email Inquiry',contactName:'',phone:'',emailAddress:'',assignedSalesRep:'',leadInterest:'WARM',leadSourceCode:'DIRECT',leadSourceName:'Direct',sourceDetails:'',notes:''});
 const [opp,setOpp]=useState<any>({customerId:'',name:'',owner:'',stage:'QUALIFY',probability:'20',value:'0',currency:'USD',origin:'',destination:'',equipment:'40HC',expectedClose:'',source:'DIRECT',notes:''});
 const [tender,setTender]=useState<any>({customerId:'',name:'',opportunityId:'',trade:'',equipment:'40HC',estimatedVolume:'0',volumeUnit:'TEU',deadline:'',status:'OPEN',owner:'',notes:''});
 const [quote,setQuote]=useState<any>({buyRate:'0',sellRate:'0',currency:'USD',trade:'',equipment:'40HC',validFrom:new Date().toISOString().slice(0,10),validTo:new Date(Date.now()+30*86400000).toISOString().slice(0,10),notes:''});
 useEffect(()=>{const t=requireToken();if(!t)return;setToken(t);void load(t);},[]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('opportunity');if(!id||!data?.opportunities?.length)return;const x=data.opportunities.find((r:any)=>r.opportunityId===id);if(x&&!selected)void selectOpp(x);},[data?.opportunities]);
 async function load(t=token){try{const [d,c,o]=await Promise.all([api('/sales-crm/dashboard',t),api('/sales-crm/customers',t),api('/sales-crm/organizations',t)]);setData(d);setCustomers(c);setOrganizations(o);}catch(e:any){setMessage(e.message||'Unable to load Sales CRM');}}
 async function createLead(){setBusy(true);try{const org=organizations.find((x:any)=>x.id===lead.organizationId);const created=await api('/sales-crm/leads',token,{method:'POST',body:JSON.stringify({...lead,organizationName:lead.organizationName||org?.name||''})});location.href=`/sales-crm/leads/${created.leadId}`;}catch(e:any){setMessage(e.message||'Inquiry / lead could not be created');}finally{setBusy(false);}}
 async function createOpp(){setBusy(true);try{await api('/sales-crm/opportunities',token,{method:'POST',body:JSON.stringify({...opp,probability:Number(opp.probability),value:Number(opp.value)})});setMessage('Opportunity created.');setOpp({...opp,name:'',value:'0'});await load();}catch(e:any){setMessage(e.message||'Opportunity could not be created');}finally{setBusy(false);}}
 async function createTender(){setBusy(true);try{await api('/sales-crm/tenders',token,{method:'POST',body:JSON.stringify({...tender,estimatedVolume:Number(tender.estimatedVolume)})});setMessage('Tender / RFQ created.');await load();}catch(e:any){setMessage(e.message||'Tender could not be created');}finally{setBusy(false);}}
 async function selectOpp(x:any){setSelected(x);try{setQuotes(await api(`/sales-crm/opportunities/${x.opportunityId}/quotes`,token));}catch(e:any){setMessage(e.message||'Unable to load quote versions');}}
 async function createQuote(){if(!selected)return;setBusy(true);try{await api(`/sales-crm/opportunities/${selected.opportunityId}/quotes`,token,{method:'POST',body:JSON.stringify({...quote,buyRate:Number(quote.buyRate),sellRate:Number(quote.sellRate)})});setQuotes(await api(`/sales-crm/opportunities/${selected.opportunityId}/quotes`,token));setMessage('Quote version created.');}catch(e:any){setMessage(e.message||'Quote version could not be created');}finally{setBusy(false);}}
 async function quoteAction(id:string,action:string){setBusy(true);try{await api(`/sales-crm/quotes/${id}/${action}`,token,{method:'POST',body:JSON.stringify({})});if(selected)setQuotes(await api(`/sales-crm/opportunities/${selected.opportunityId}/quotes`,token));setMessage(action==='publish'?'Quote published into Commercial / Quotes.':'Quote version approved.');await load();}catch(e:any){setMessage(e.message||'Quote action failed');}finally{setBusy(false);}}
 async function closeOpp(id:string,result:string){const lossReason=result==='LOST'?prompt('Loss reason?')||'Unspecified':null;setBusy(true);try{await api(`/sales-crm/opportunities/${id}/close/${result}`,token,{method:'POST',body:JSON.stringify({lossReason})});await load();setMessage(`Opportunity marked ${result}.`);}catch(e:any){setMessage(e.message||'Opportunity update failed');}finally{setBusy(false);}}
 const s=data.summary||{};
 return <WorkspaceShell title="Sales CRM / Pipeline" subtitle="Opportunities, tenders/RFQs, quote versions, pipeline forecast and win/loss control" active="/sales-crm" actions={<button className="btn" onClick={()=>void load()}>Refresh</button>}>
  {message&&<div className="card" style={{marginBottom:12}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:12}}>{[['Open Inquiries',s.openLeads],['Open Opportunities',s.openOpportunities],['Won',s.won],['Lost',s.lost],['Win Rate',`${Number(s.winRate||0).toFixed(1)}%`],['Open Tenders',s.openTenders]].map(([a,b])=><div className="card" key={String(a)}><div className="sub">{a}</div><div style={{fontSize:24,fontWeight:800}}>{b??0}</div></div>)}</div>
  <div className="card" style={{marginBottom:12,display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h3 style={{...sectionTitle,marginBottom:4}}>Inquiry / Sales Lead</h3><div className="sub">Open the classic Inquiry workspace to create and qualify a lead before converting it to an Opportunity.</div></div><a className="btn" href="/sales-crm/leads/new" style={{textDecoration:'none'}}>+ New Inquiry</a></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Inquiry / Lead Register</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Inquiry</th><th>Type</th><th>Organization</th><th>Contact</th><th>Sales Rep</th><th>Interest</th><th>Source</th><th>Status</th><th></th></tr></thead><tbody>{(data.leads||[]).map((x:any)=><tr key={x.leadId}><td><b>{x.inquiryNo}</b></td><td>{x.inquiryTypeLabel||x.inquiryType}</td><td>{x.organizationName}</td><td>{x.contactName}<div className="sub">{x.emailAddress||x.phone||''}</div></td><td>{x.assignedSalesRep||'—'}</td><td><span className="status">{x.leadInterest||'—'}</span></td><td>{[x.leadSourceCode,x.leadSourceName].filter(Boolean).join(' - ')}</td><td><span className="status">{x.status}</span></td><td><a className="btn" href={`/sales-crm/leads/${x.leadId}`} style={{textDecoration:'none'}}>Open</a></td></tr>)}{!(data.leads||[]).length&&<tr><td colSpan={9}>No inquiries / leads yet.</td></tr>}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Pipeline Forecast</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Currency</th><th>Gross Pipeline</th><th>Weighted Forecast</th></tr></thead><tbody>{(data.pipelineByCurrency||[]).map((x:any)=><tr key={x.currency}><td>{x.currency}</td><td>{Number(x.grossPipeline||0).toFixed(2)}</td><td>{Number(x.weightedPipeline||0).toFixed(2)}</td></tr>)}</tbody></table></div></div>
  <div className="card" style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8}}><h3 style={sectionTitle}>New Opportunity</h3><a className="btn" href="/sales-crm/opportunities/new" style={{textDecoration:'none'}}>Open Classic Opportunity</a></div><div style={formGrid}>
   <label><span style={labelStyle}>Customer</span><select style={fieldStyle} value={opp.customerId} onChange={e=>setOpp({...opp,customerId:e.target.value})}><option value="">Select customer</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   {['name','owner','value','currency','origin','destination','equipment','expectedClose','source'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type={k==='value'?'number':k==='expectedClose'?'date':'text'} style={fieldStyle} value={opp[k]} onChange={e=>setOpp({...opp,[k]:e.target.value})}/></label>)}
   <label><span style={labelStyle}>Stage</span><select style={fieldStyle} value={opp.stage} onChange={e=>setOpp({...opp,stage:e.target.value})}>{['QUALIFY','DISCOVERY','SOLUTION','PRICING','NEGOTIATION'].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span style={labelStyle}>Probability %</span><input type="number" style={fieldStyle} value={opp.probability} onChange={e=>setOpp({...opp,probability:e.target.value})}/></label>
  </div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void createOpp()}>Create Opportunity</button></div>
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Opportunity Pipeline</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Opportunity</th><th>Customer</th><th>Stage</th><th>Probability</th><th>Value</th><th>Lane</th><th>Status</th><th>Actions</th></tr></thead><tbody>{(data.opportunities||[]).map((x:any)=><tr key={x.opportunityId}><td><a className="btn" href={`/sales-crm/opportunities/${x.opportunityId}`} style={{textDecoration:'none'}}>{x.name}</a></td><td>{customers.find(c=>c.id===x.customerId)?.name||x.customerId}</td><td>{x.stage}</td><td>{x.probability}%</td><td>{x.currency} {Number(x.value||0).toFixed(2)}</td><td>{x.origin||'—'} → {x.destination||'—'}</td><td>{x.status}</td><td>{!['WON','LOST'].includes(x.status)&&<><button className="btn" onClick={()=>void closeOpp(x.opportunityId,'WON')}>Won</button> <button className="btn" onClick={()=>void closeOpp(x.opportunityId,'LOST')}>Lost</button></>}</td></tr>)}</tbody></table></div></div>
  {selected&&<div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Quote Versioning — {selected.name}</h3><div style={formGrid}>{['buyRate','sellRate','currency','trade','equipment','validFrom','validTo'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type={k==='buyRate'||k==='sellRate'?'number':k==='validFrom'||k==='validTo'?'date':'text'} style={fieldStyle} value={quote[k]} onChange={e=>setQuote({...quote,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void createQuote()}>Create Version</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Version</th><th>Buy</th><th>Sell</th><th>Margin</th><th>Validity</th><th>Status</th><th>Commercial Quote</th><th>Action</th></tr></thead><tbody>{quotes.map((q:any)=><tr key={q.quoteVersionId}><td>v{q.version}</td><td>{q.currency} {q.buyRate}</td><td>{q.currency} {q.sellRate}</td><td>{Number(q.marginPct||0).toFixed(1)}%</td><td>{String(q.validTo||'').slice(0,10)}</td><td>{q.status}</td><td>{q.rateQuoteId||'—'}</td><td>{q.status==='DRAFT'?<button className="btn" onClick={()=>void quoteAction(q.quoteVersionId,'approve')}>Approve</button>:!q.rateQuoteId?<button className="btn" onClick={()=>void quoteAction(q.quoteVersionId,'publish')}>Publish</button>:'Published'}</td></tr>)}</tbody></table></div></div>}
  <div className="card" style={{marginBottom:12}}><h3 style={sectionTitle}>Tender / RFQ Register</h3><div style={formGrid}><label><span style={labelStyle}>Customer</span><select style={fieldStyle} value={tender.customerId} onChange={e=>setTender({...tender,customerId:e.target.value})}><option value="">Select customer</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{['name','opportunityId','trade','equipment','estimatedVolume','volumeUnit','deadline','owner'].map(k=><label key={k}><span style={labelStyle}>{k}</span><input type={k==='estimatedVolume'?'number':k==='deadline'?'date':'text'} style={fieldStyle} value={tender[k]} onChange={e=>setTender({...tender,[k]:e.target.value})}/></label>)}</div><button className="btn" style={{marginTop:10}} disabled={busy} onClick={()=>void createTender()}>Create Tender / RFQ</button><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Tender</th><th>Customer</th><th>Trade</th><th>Volume</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{(data.tenders||[]).map((x:any)=><tr key={x.tenderId}><td>{x.name}</td><td>{customers.find(c=>c.id===x.customerId)?.name||x.customerId}</td><td>{x.trade||'—'}</td><td>{x.estimatedVolume} {x.volumeUnit}</td><td>{String(x.deadline||'').slice(0,10)||'—'}</td><td>{x.status}</td></tr>)}</tbody></table></div></div>
  <div className="card"><h3 style={sectionTitle}>Win / Loss Analysis</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Loss Reason</th><th>Count</th></tr></thead><tbody>{(data.lossReasons||[]).map((x:any)=><tr key={x.reason}><td>{x.reason}</td><td>{String(x.count)}</td></tr>)}</tbody></table></div></div>
 </WorkspaceShell>;
}
