import { BadRequestException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser, bookingScope } from '../auth/scope';

const SOURCE='ANCLINE_ENTERPRISE_RISK';
const now=()=>new Date();
const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;

@Injectable()
export class EnterpriseRiskService {
 constructor(private prisma:PrismaService,private scope:ScopeService){}
 private async events(){return this.prisma.integrationEvent.findMany({where:{sourceSystem:SOURCE},orderBy:{createdAt:'asc'}});}
 private latest(rows:any[],objectType:string,eventTypes?:string[]){const m=new Map<string,any>();for(const e of rows)if(e.objectType===objectType&&(!eventTypes||eventTypes.includes(e.eventType)))m.set(e.objectId,e);return [...m.values()];}
 private p(e:any){return (e?.payload||{}) as any;}
 private write(eventType:string,objectType:string,objectId:string,payload:any){return this.prisma.integrationEvent.create({data:{sourceSystem:SOURCE,eventType,objectType,objectId,status:'COMPLETED',payload,completedAt:now()}});}
 async customers(user:ScopeUser){this.scope.assertInternal(user);return this.prisma.organization.findMany({where:{roles:{has:'CUSTOMER'}},select:{id:true,name:true,code:true},orderBy:{name:'asc'}});}
 async bookings(user:ScopeUser){this.scope.assertInternal(user);return this.prisma.booking.findMany({where:bookingScope(user),select:{id:true,bookingNo:true,customerId:true,origin:true,destination:true,status:true,specialCargo:true,dgUnNo:true,dgImoClass:true,dgPackingGroup:true,dgProperShippingName:true},orderBy:{createdAt:'desc'},take:250});}
 async dashboard(user:ScopeUser){this.scope.assertInternal(user);const rows=await this.events(),screenings=this.latest(rows,'CounterpartyScreening',['SCREENING_SET']).map(e=>this.p(e)),policies=this.latest(rows,'InsurancePolicy',['INSURANCE_POLICY_SET']).map(e=>this.p(e)),certs=this.latest(rows,'InsuranceCertificate',['INSURANCE_CERT_SET']).map(e=>this.p(e)),dg=this.latest(rows,'DGReview',['DG_REVIEW_SET']).map(e=>this.p(e)),docs=this.latest(rows,'ComplianceDocument',['COMPLIANCE_DOCUMENT_SET']).map(e=>this.p(e)),holds=this.activeHolds(rows),recoveries=this.latest(rows,'InsuranceRecovery',['INSURANCE_RECOVERY_SET','INSURANCE_RECOVERY_UPDATED']).map(e=>this.p(e)),today=Date.now(),soon=today+30*86400000,expiry=[...policies.map((x:any)=>({type:'Insurance Policy',reference:x.policyNo,owner:x.insurer,expiresAt:x.validTo})),...screenings.map((x:any)=>({type:'KYC / Screening',reference:x.counterpartyName||x.organizationId,owner:x.organizationId,expiresAt:x.expiresAt})),...docs.map((x:any)=>({type:x.documentType||'Compliance Document',reference:x.reference||x.organizationId,owner:x.organizationId,expiresAt:x.expiresAt}))].filter((x:any)=>x.expiresAt&&new Date(x.expiresAt).getTime()<=soon).sort((a:any,b:any)=>new Date(a.expiresAt).getTime()-new Date(b.expiresAt).getTime());return {summary:{activePolicies:policies.filter((x:any)=>x.active!==false&&(!x.validTo||new Date(x.validTo).getTime()>=today)).length,activeHolds:holds.length,sanctionsMatches:screenings.filter((x:any)=>['MATCH','BLOCKED'].includes(String(x.sanctionsStatus||'').toUpperCase())).length,pendingDG:dg.filter((x:any)=>String(x.status).toUpperCase()==='PENDING').length,expiring30d:expiry.length,openInsuranceRecoveries:recoveries.filter((x:any)=>!['RECOVERED','CLOSED','REJECTED'].includes(String(x.status||'').toUpperCase())).length},screenings,policies,certificates:certs,dgReviews:dg,documents:docs,holds,recoveries,expiry};}
 private activeHolds(rows:any[]){const m=new Map<string,any>();for(const e of rows.filter(e=>e.objectType==='BookingRiskHold')){if(e.eventType==='HOLD_PLACED')m.set(e.objectId,this.p(e));if(e.eventType==='HOLD_RELEASED')m.delete(e.objectId);}return [...m.values()];}
 async setRiskPolicy(body:any,user:ScopeUser){this.scope.assertFinanceAccess(user);const payload={requireKyc:body?.requireKyc===true,requireInsurance:body?.requireInsurance===true,requireInsuranceForDG:body?.requireInsuranceForDG===true,screeningValidityDays:Number(body?.screeningValidityDays||365),documentWarningDays:Number(body?.documentWarningDays||30),updatedBy:user.sub,updatedAt:now().toISOString()};await this.write('RISK_POLICY_SET','RiskPolicy','GLOBAL',payload);return payload;}
 async screening(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.organizationId)throw new BadRequestException('Organization is required');const org=await this.prisma.organization.findUnique({where:{id:String(body.organizationId)},select:{id:true,name:true}});if(!org)throw new BadRequestException('Organization not found');const payload={organizationId:org.id,counterpartyName:org.name,kycStatus:String(body.kycStatus||'PENDING').toUpperCase(),sanctionsStatus:String(body.sanctionsStatus||'CLEAR').toUpperCase(),pepStatus:String(body.pepStatus||'CLEAR').toUpperCase(),screenedAt:body.screenedAt||now().toISOString(),expiresAt:body.expiresAt||null,provider:body.provider||'MANUAL',reference:body.reference||null,notes:body.notes||null,updatedBy:user.sub};await this.write('SCREENING_SET','CounterpartyScreening',org.id,payload);return payload;}
 async setInsurancePolicy(body:any,user:ScopeUser){this.scope.assertFinanceAccess(user);if(!body?.policyNo||!body?.insurer)throw new BadRequestException('Policy number and insurer are required');const policyId=String(body.policyId||id('POL'));const payload={policyId,policyNo:String(body.policyNo),insurer:String(body.insurer),currency:String(body.currency||'USD').toUpperCase(),limit:Number(body.limit||0),deductible:Number(body.deductible||0),validFrom:body.validFrom||null,validTo:body.validTo||null,coveredModes:Array.isArray(body.coveredModes)?body.coveredModes:[],active:body.active!==false,notes:body.notes||null,updatedBy:user.sub};await this.write('INSURANCE_POLICY_SET','InsurancePolicy',policyId,payload);return payload;}
 async certificate(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.bookingId||!body?.policyId)throw new BadRequestException('Booking and policy are required');await this.scope.assertBookingAccess(user,String(body.bookingId));const rows=await this.events(),policy=this.latest(rows,'InsurancePolicy',['INSURANCE_POLICY_SET']).map(e=>this.p(e)).find((x:any)=>x.policyId===body.policyId&&x.active!==false);if(!policy)throw new BadRequestException('Active insurance policy not found');const certificateId=String(body.certificateId||id('CERT')),payload={certificateId,bookingId:String(body.bookingId),policyId:String(body.policyId),certificateNo:String(body.certificateNo||certificateId),insuredValue:Number(body.insuredValue||0),currency:String(body.currency||policy.currency||'USD').toUpperCase(),issuedAt:body.issuedAt||now().toISOString(),status:String(body.status||'ISSUED').toUpperCase(),notes:body.notes||null,updatedBy:user.sub};await this.write('INSURANCE_CERT_SET','InsuranceCertificate',certificateId,payload);return payload;}
 async dgReview(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.bookingId)throw new BadRequestException('Booking is required');await this.scope.assertBookingAccess(user,String(body.bookingId));const b=await this.prisma.booking.findUnique({where:{id:String(body.bookingId)},select:{id:true,bookingNo:true,dgUnNo:true,dgImoClass:true,dgPackingGroup:true,dgProperShippingName:true}});if(!b)throw new BadRequestException('Booking not found');const payload={bookingId:b.id,bookingNo:b.bookingNo,unNo:body.unNo||b.dgUnNo||null,imoClass:body.imoClass||b.dgImoClass||null,packingGroup:body.packingGroup||b.dgPackingGroup||null,properShippingName:body.properShippingName||b.dgProperShippingName||null,declarationReceived:body.declarationReceived===true,sdsReceived:body.sdsReceived===true,carrierAccepted:body.carrierAccepted===true,status:String(body.status||'PENDING').toUpperCase(),reviewer:user.sub,reviewedAt:now().toISOString(),notes:body.notes||null};if(payload.status==='APPROVED'&&(!payload.declarationReceived||!payload.sdsReceived||!payload.carrierAccepted))throw new BadRequestException('DG approval requires declaration, SDS and carrier acceptance');await this.write('DG_REVIEW_SET','DGReview',b.id,payload);return payload;}
 async document(body:any,user:ScopeUser){this.scope.assertInternal(user);if(!body?.organizationId||!body?.documentType)throw new BadRequestException('Organization and document type are required');const docId=String(body.documentId||id('DOC')),payload={documentId:docId,organizationId:String(body.organizationId),documentType:String(body.documentType),reference:body.reference||null,issuedAt:body.issuedAt||null,expiresAt:body.expiresAt||null,status:String(body.status||'VALID').toUpperCase(),notes:body.notes||null,updatedBy:user.sub};await this.write('COMPLIANCE_DOCUMENT_SET','ComplianceDocument',docId,payload);return payload;}
 async hold(bookingId:string,body:any,user:ScopeUser){this.scope.assertInternal(user);await this.scope.assertBookingAccess(user,bookingId);const rows=await this.events(),active=this.activeHolds(rows).find((x:any)=>x.bookingId===bookingId);if(active)throw new BadRequestException('Booking already has an active risk hold');const holdId=id('HOLD'),payload={holdId,bookingId,type:String(body?.type||'COMPLIANCE').toUpperCase(),reason:String(body?.reason||'Risk review required'),placedBy:user.sub,placedAt:now().toISOString()};await this.write('HOLD_PLACED','BookingRiskHold',holdId,payload);return payload;}
 async releaseHold(holdId:string,body:any,user:ScopeUser){this.scope.assertFinanceAccess(user);const rows=await this.events(),active=this.activeHolds(rows).find((x:any)=>x.holdId===holdId);if(!active)throw new BadRequestException('Active hold not found');const payload={...active,releasedBy:user.sub,releasedAt:now().toISOString(),releaseReason:body?.reason||null};await this.write('HOLD_RELEASED','BookingRiskHold',holdId,payload);return payload;}
 async recovery(body:any,user:ScopeUser){this.scope.assertFinanceAccess(user);if(!body?.claimId&&!body?.bookingId)throw new BadRequestException('Claim or booking reference is required');const recoveryId=String(body.recoveryId||id('IR')),payload={recoveryId,claimId:body.claimId||null,bookingId:body.bookingId||null,insurer:body.insurer||null,policyId:body.policyId||null,amount:Number(body.amount||0),currency:String(body.currency||'USD').toUpperCase(),status:String(body.status||'OPEN').toUpperCase(),subrogationParty:body.subrogationParty||null,reference:body.reference||null,notes:body.notes||null,updatedBy:user.sub,updatedAt:now().toISOString()};await this.write('INSURANCE_RECOVERY_SET','InsuranceRecovery',recoveryId,payload);return payload;}
 async updateRecovery(id:string,body:any,user:ScopeUser){this.scope.assertFinanceAccess(user);const rows=await this.events(),current=this.latest(rows,'InsuranceRecovery',['INSURANCE_RECOVERY_SET','INSURANCE_RECOVERY_UPDATED']).map(e=>this.p(e)).find((x:any)=>x.recoveryId===id);if(!current)throw new BadRequestException('Insurance recovery not found');const payload={...current,...body,recoveryId:id,amount:body.amount!=null?Number(body.amount):current.amount,status:String(body.status||current.status).toUpperCase(),updatedBy:user.sub,updatedAt:now().toISOString()};await this.write('INSURANCE_RECOVERY_UPDATED','InsuranceRecovery',id,payload);return payload;}
 async bookingGate(booking:any){const rows=await this.events(),policy=this.latest(rows,'RiskPolicy',['RISK_POLICY_SET']).map(e=>this.p(e)).find((x:any)=>true)||{},blockers:string[]=[],holds=this.activeHolds(rows).filter((x:any)=>x.bookingId===booking.id);if(holds.length)blockers.push(`active risk hold: ${holds[0].reason}`);const screening=this.latest(rows,'CounterpartyScreening',['SCREENING_SET']).map(e=>this.p(e)).find((x:any)=>x.organizationId===booking.customerId);if(screening){const sanctions=String(screening.sanctionsStatus||'').toUpperCase(),kyc=String(screening.kycStatus||'').toUpperCase();if(['MATCH','BLOCKED','REJECTED'].includes(sanctions))blockers.push(`customer sanctions screening is ${sanctions}`);if(policy.requireKyc===true&&!['APPROVED','CLEAR','VERIFIED'].includes(kyc))blockers.push(`customer KYC is ${kyc||'not approved'}`);if(policy.requireKyc===true&&screening.expiresAt&&new Date(screening.expiresAt).getTime()<Date.now())blockers.push('customer KYC / screening is expired');}else if(policy.requireKyc===true)blockers.push('customer KYC / screening is required');const isDG=Boolean(booking.dgUnNo||booking.dgImoClass||String(booking.specialCargo||'').toUpperCase().includes('DG'));if(isDG){const dg=this.latest(rows,'DGReview',['DG_REVIEW_SET']).map(e=>this.p(e)).find((x:any)=>x.bookingId===booking.id);if(!dg||String(dg.status).toUpperCase()!=='APPROVED')blockers.push('dangerous-goods review must be approved');}if(policy.requireInsurance===true||(policy.requireInsuranceForDG===true&&isDG)){const cert=this.latest(rows,'InsuranceCertificate',['INSURANCE_CERT_SET']).map(e=>this.p(e)).find((x:any)=>x.bookingId===booking.id&&['ISSUED','ACTIVE'].includes(String(x.status||'').toUpperCase()));if(!cert)blockers.push('cargo insurance certificate is required');}if(blockers.length)throw new BadRequestException(`Enterprise risk blocked confirmation: ${blockers.join('; ')}`);return {ok:true};}
}
