import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser, bookingScope } from '../auth/scope';
import { AuditService } from '../audit/audit.service';
import { ProcurementData, PROCUREMENT_SOURCE } from './procurement.data';

@Injectable()
export class ProcurementService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService,private data:ProcurementData){}
  private get db():any{return this.prisma as any;}
  private internal(u:ScopeUser){this.scope.assertInternal(u);}
  private finance(u:ScopeUser){this.scope.assertFinanceAccess(u);}
  private r(v:any){return this.data.r(v);}
  private req(v:any,n:string){const s=String(v??'').trim();if(!s)throw new BadRequestException(`${n} is required`);return s;}
  private cur(v:any){const s=String(v||'USD').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(s))throw new BadRequestException('Currency must be a 3-letter code');return s;}
  private dt(v:any,n='Date'){const d=new Date(v);if(Number.isNaN(d.getTime()))throw new BadRequestException(`${n} is invalid`);return d;}
  private generatedNo(){const d=new Date();return `PO-${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}-${Date.now().toString().slice(-7)}`;}

  async vendors(u:ScopeUser){this.internal(u);return this.db.organization.findMany({where:{active:true,roles:{has:'VENDOR'}},select:{id:true,code:true,name:true,countryCode:true},orderBy:{name:'asc'}});}
  async bookings(u:ScopeUser){this.internal(u);return this.db.booking.findMany({where:{...bookingScope(u),status:{not:'CANCELLED'}},select:{id:true,bookingNo:true,shipmentNo:true,origin:true,destination:true,currency:true,owningBranchId:true,status:true},orderBy:{createdAt:'desc'},take:250});}
  async purchaseOrders(status:string|undefined,u:ScopeUser){this.internal(u);const rows=await this.data.accessiblePOs(u);return rows.filter((x:any)=>!status||x.status===String(status).toUpperCase()).sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());}
  async purchaseOrder(poNo:string,u:ScopeUser){this.internal(u);const row=(await this.data.accessiblePOs(u)).find((x:any)=>x.poNo===poNo);if(!row)throw new NotFoundException('Purchase order not found');return row;}

  private lines(lines:any[]){if(!Array.isArray(lines)||!lines.length)throw new BadRequestException('At least one PO line is required');const seen=new Set<string>();return lines.map((x:any,i:number)=>{const quantity=Number(x?.quantity),unitRate=Number(x?.unitRate),taxRate=Number(x?.taxRate||0);if(!Number.isFinite(quantity)||quantity<=0)throw new BadRequestException(`Line ${i+1} quantity must be greater than zero`);if(!Number.isFinite(unitRate)||unitRate<0)throw new BadRequestException(`Line ${i+1} unit rate is invalid`);if(!Number.isFinite(taxRate)||taxRate<0)throw new BadRequestException(`Line ${i+1} tax rate is invalid`);const lineId=String(x?.lineId||`L${i+1}`).toUpperCase();if(seen.has(lineId))throw new BadRequestException(`Duplicate line ${lineId}`);seen.add(lineId);const amount=this.r(quantity*unitRate);return {lineId,chargeCode:this.req(x?.chargeCode||'COST','Charge code').toUpperCase(),description:x?.description?String(x.description):null,expenseAccount:String(x?.expenseAccount||'5000-DIRECT-COST').toUpperCase(),quantity:this.r(quantity),unitRate:this.r(unitRate),amount,taxRate:this.r(taxRate),taxAmount:this.r(amount*taxRate/100)};});}
  private totals(lines:any[]){const subtotal=this.r(lines.reduce((s:number,l:any)=>s+Number(l.amount||0),0)),taxAmount=this.r(lines.reduce((s:number,l:any)=>s+Number(l.taxAmount||0),0));return {subtotal,taxAmount,totalAmount:this.r(subtotal+taxAmount)};}
  private async vendor(id:string){const vendor=await this.db.organization.findUnique({where:{id}});if(!vendor||!vendor.active||!Array.isArray(vendor.roles)||!vendor.roles.includes('VENDOR'))throw new BadRequestException('Vendor must be an active VENDOR organization');return vendor;}

  async createPO(b:any,u:ScopeUser){this.internal(u);const bookingId=this.req(b?.bookingId,'Booking');await this.scope.assertBookingAccess(u,bookingId);const booking=await this.db.booking.findUnique({where:{id:bookingId},select:{id:true,bookingNo:true,currency:true,owningBranchId:true}});if(!booking)throw new BadRequestException('Booking not found');const vendorId=this.req(b?.vendorId,'Vendor'),vendor=await this.vendor(vendorId),currency=this.cur(b?.currency||booking.currency||'USD'),lines=this.lines(b?.lines),totals=this.totals(lines),poNo=String(b?.poNo||this.generatedNo()).toUpperCase();if(await this.db.integrationEvent.findFirst({where:{sourceSystem:PROCUREMENT_SOURCE,objectType:'PurchaseOrder',objectId:poNo}}))throw new BadRequestException(`Purchase order ${poNo} already exists`);const tolerancePct=Number(b?.tolerancePct??2);if(!Number.isFinite(tolerancePct)||tolerancePct<0||tolerancePct>25)throw new BadRequestException('Tolerance % must be between 0 and 25');const budgetPolicy=String(b?.budgetPolicy||'WARN').toUpperCase();if(!['WARN','BLOCK'].includes(budgetPolicy))throw new BadRequestException('Budget policy must be WARN or BLOCK');const payload={poNo,bookingId,bookingNo:booking.bookingNo,owningBranchId:booking.owningBranchId,vendorId,vendorName:vendor.name,currency,orderDate:(b?.orderDate?this.dt(b.orderDate,'Order date'):new Date()).toISOString(),expectedDate:b?.expectedDate?this.dt(b.expectedDate,'Expected date').toISOString():null,tolerancePct:this.r(tolerancePct),budgetPolicy,reference:b?.reference?String(b.reference):null,notes:b?.notes?String(b.notes):null,lines,...totals,createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'PO_CREATED',externalId:poNo,objectType:'PurchaseOrder',objectId:poNo,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'PROCUREMENT_PO_CREATE',objectType:'PurchaseOrder',objectId:poNo,bookingId,detail:{vendorId,currency,totalAmount:totals.totalAmount,lineCount:lines.length}});return this.purchaseOrder(poNo,u);}

  async updatePO(poNo:string,b:any,u:ScopeUser){this.internal(u);const po:any=await this.purchaseOrder(poNo,u);if(po.status!=='DRAFT')throw new BadRequestException('Only draft purchase orders can be edited');const vendorId=String(b?.vendorId||po.vendorId),vendor=await this.vendor(vendorId),lines=this.lines(b?.lines||po.lines),totals=this.totals(lines),tolerancePct=Number(b?.tolerancePct??po.tolerancePct??2),budgetPolicy=String(b?.budgetPolicy||po.budgetPolicy||'WARN').toUpperCase();if(!Number.isFinite(tolerancePct)||tolerancePct<0||tolerancePct>25)throw new BadRequestException('Tolerance % must be between 0 and 25');if(!['WARN','BLOCK'].includes(budgetPolicy))throw new BadRequestException('Budget policy must be WARN or BLOCK');const payload={poNo,bookingId:po.bookingId,bookingNo:po.bookingNo,owningBranchId:po.owningBranchId,vendorId,vendorName:vendor.name,currency:this.cur(b?.currency||po.currency),orderDate:(b?.orderDate?this.dt(b.orderDate):new Date(po.orderDate)).toISOString(),expectedDate:b?.expectedDate?this.dt(b.expectedDate).toISOString():po.expectedDate,tolerancePct:this.r(tolerancePct),budgetPolicy,reference:b?.reference??po.reference,notes:b?.notes??po.notes,lines,...totals,updatedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'PO_UPDATED',externalId:poNo,objectType:'PurchaseOrder',objectId:poNo,status:'COMPLETED',payload,completedAt:new Date()}});return this.purchaseOrder(poNo,u);}

  async submitPO(poNo:string,u:ScopeUser){this.internal(u);const po:any=await this.purchaseOrder(poNo,u);if(po.status!=='DRAFT')throw new BadRequestException(`PO cannot be submitted from ${po.status}`);await this.db.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'PO_SUBMITTED',externalId:poNo,objectType:'PurchaseOrder',objectId:poNo,status:'COMPLETED',payload:{poNo,submittedBy:u.sub},completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'PROCUREMENT_PO_SUBMIT',objectType:'PurchaseOrder',objectId:poNo,bookingId:po.bookingId,detail:{totalAmount:po.totalAmount,currency:po.currency}});return this.purchaseOrder(poNo,u);}
  async budgetCheck(poNo:string,u:ScopeUser){this.internal(u);const po:any=await this.purchaseOrder(poNo,u);return this.data.budgetCheck(po);}

  async approvePO(poNo:string,u:ScopeUser){this.finance(u);const po:any=(await this.data.allPOs()).find((x:any)=>x.poNo===poNo);if(!po)throw new NotFoundException('Purchase order not found');if(po.status!=='SUBMITTED')throw new BadRequestException(`PO cannot be approved from ${po.status}`);const budget=await this.data.budgetCheck(po);if(po.budgetPolicy==='BLOCK'&&budget.lines.some((x:any)=>x.status!=='WITHIN_BUDGET'))throw new BadRequestException('PO is blocked by budget control');const financeLineIds:any={};await this.db.$transaction(async(tx:any)=>{for(const line of po.lines){const reference=`PO:${poNo}:${line.lineId}`;let fl=await tx.financeLine.findFirst({where:{reference}});if(!fl)fl=await tx.financeLine.create({data:{bookingId:po.bookingId,type:'COST',chargeCode:line.chargeCode,description:line.description||`PO ${poNo}`,partyId:po.vendorId,serviceProviderId:po.vendorId,quantity:line.quantity,unitRate:line.unitRate,amount:line.amount,currency:po.currency,status:'WIP',source:'PROCUREMENT',reference,taxRate:line.taxRate}});financeLineIds[line.lineId]=fl.id;}await tx.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'PO_APPROVED',externalId:poNo,objectType:'PurchaseOrder',objectId:poNo,status:'COMPLETED',payload:{poNo,financeLineIds,budgetStatus:budget.status,approvedBy:u.sub},completedAt:new Date()}});});await this.audit.log({actorId:u.sub,action:'PROCUREMENT_PO_APPROVE',objectType:'PurchaseOrder',objectId:poNo,bookingId:po.bookingId,detail:{budgetStatus:budget.status,totalAmount:po.totalAmount,financeLineIds}});return this.purchaseOrder(poNo,u);}

  async receivePO(poNo:string,b:any,u:ScopeUser){this.internal(u);const po:any=await this.purchaseOrder(poNo,u);if(!['APPROVED','PART_RECEIVED'].includes(po.status))throw new BadRequestException(`PO cannot be received from ${po.status}`);const input=Array.isArray(b?.items)?b.items:[];if(!input.length)throw new BadRequestException('At least one receipt item is required');const items:any[]=[];for(const x of input){const line=po.lines.find((l:any)=>l.lineId===String(x?.lineId));if(!line)throw new BadRequestException(`Unknown PO line ${x?.lineId}`);const q=this.r(x?.quantity);if(q<=0)throw new BadRequestException('Receipt quantity must be greater than zero');if(q-line.remainingQuantity>0.0005)throw new BadRequestException(`Receipt exceeds remaining quantity for ${line.lineId}`);items.push({lineId:line.lineId,quantity:q,receivedBy:u.sub});}const now=b?.receivedAt?this.dt(b.receivedAt,'Receipt date'):new Date();await this.db.$transaction(async(tx:any)=>{await tx.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'PO_RECEIPT_RECORDED',externalId:poNo,objectType:'PurchaseOrder',objectId:poNo,status:'COMPLETED',payload:{poNo,items,receiptReference:b?.receiptReference?String(b.receiptReference):null,notes:b?.notes?String(b.notes):null,receivedAt:now.toISOString(),receivedBy:u.sub},completedAt:new Date()}});for(const item of items){const line=po.lines.find((l:any)=>l.lineId===item.lineId);if(line.financeLineId&&this.r(Number(line.receivedQuantity||0)+item.quantity)>=Number(line.quantity)-0.0005)await tx.financeLine.update({where:{id:line.financeLineId},data:{status:'ACCRUED',accruedAt:now}});}});await this.audit.log({actorId:u.sub,action:'PROCUREMENT_PO_RECEIPT',objectType:'PurchaseOrder',objectId:poNo,bookingId:po.bookingId,detail:{items,receiptReference:b?.receiptReference||null}});return this.purchaseOrder(poNo,u);}

  private async scopedMatches(u:ScopeUser){const all=await this.data.apMatches();if(['GLOBAL_ADMIN','CONTROL_TOWER','FINANCE'].includes(u.role))return all;const pos=await this.data.accessiblePOs(u),ids=new Set<string>();for(const po of pos)for(const line of po.lines||[])if(line.financeLineId)ids.add(String(line.financeLineId));return all.filter((m:any)=>(m.lines||[]).some((l:any)=>ids.has(String(l.financeLineId))));}
  async apMatches(u:ScopeUser){this.internal(u);return this.scopedMatches(u);}
  async overrideMatch(invoiceNo:string,b:any,u:ScopeUser){this.finance(u);const match=(await this.data.apMatches()).find((x:any)=>x.invoiceNo===invoiceNo);if(!match)throw new NotFoundException('AP invoice match not found');if(match.status==='MATCHED')return match;const reason=this.req(b?.reason,'Override reason');await this.db.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'AP_MATCH_OVERRIDE',externalId:invoiceNo,objectType:'APMatch',objectId:invoiceNo,status:'COMPLETED',payload:{invoiceNo,reason,approvedBy:u.sub},completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'PROCUREMENT_AP_MATCH_OVERRIDE',objectType:'FinanceInvoice',objectId:invoiceNo,detail:{reason}});return (await this.data.apMatches()).find((x:any)=>x.invoiceNo===invoiceNo);}

  async closePO(poNo:string,u:ScopeUser){this.internal(u);const po:any=await this.purchaseOrder(poNo,u);if(po.status!=='RECEIVED')throw new BadRequestException('PO must be fully received before close');const matches=await this.data.apMatches();for(const line of po.lines){if(!line.financeLineId)throw new BadRequestException('PO line is missing finance commitment');const fl=await this.db.financeLine.findUnique({where:{id:line.financeLineId}});if(!fl?.invoiceNo)throw new BadRequestException(`PO line ${line.lineId} is not invoiced`);const m=matches.find((x:any)=>x.invoiceNo===fl.invoiceNo);if(!m||!['MATCHED','OVERRIDDEN'].includes(m.status))throw new BadRequestException(`AP invoice ${fl.invoiceNo} is not matched`);}await this.db.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'PO_CLOSED',externalId:poNo,objectType:'PurchaseOrder',objectId:poNo,status:'COMPLETED',payload:{poNo,closedBy:u.sub},completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'PROCUREMENT_PO_CLOSE',objectType:'PurchaseOrder',objectId:poNo,bookingId:po.bookingId});return this.purchaseOrder(poNo,u);}
  async cancelPO(poNo:string,b:any,u:ScopeUser){this.internal(u);const po:any=await this.purchaseOrder(poNo,u);if(!['DRAFT','SUBMITTED','APPROVED'].includes(po.status))throw new BadRequestException(`PO cannot be cancelled from ${po.status}`);if((po.receipts||[]).length)throw new BadRequestException('Received PO cannot be cancelled');const reason=this.req(b?.reason,'Cancellation reason');await this.db.$transaction(async(tx:any)=>{await tx.integrationEvent.create({data:{sourceSystem:PROCUREMENT_SOURCE,eventType:'PO_CANCELLED',externalId:poNo,objectType:'PurchaseOrder',objectId:poNo,status:'COMPLETED',payload:{poNo,reason,cancelledBy:u.sub},completedAt:new Date()}});for(const line of po.lines||[])if(line.financeLineId)await tx.financeLine.update({where:{id:line.financeLineId},data:{status:'CANCELLED'}});});await this.audit.log({actorId:u.sub,action:'PROCUREMENT_PO_CANCEL',objectType:'PurchaseOrder',objectId:poNo,bookingId:po.bookingId,detail:{reason}});return this.purchaseOrder(poNo,u);}

  async spendAnalysis(periodInput:string|undefined,u:ScopeUser){this.internal(u);const period=periodInput&&/^\d{4}-\d{2}$/.test(periodInput)?periodInput:new Date().toISOString().slice(0,7),pos=(await this.data.accessiblePOs(u)).filter((p:any)=>this.data.periodOf(p.orderDate)===period&&!['DRAFT','SUBMITTED','CANCELLED'].includes(p.status));const vendors=new Map<string,any>(),charges=new Map<string,any>();for(const po of pos){const vk=`${po.currency}:${po.vendorId}`;if(!vendors.has(vk))vendors.set(vk,{vendorId:po.vendorId,vendorName:po.vendorName,currency:po.currency,committed:0,poCount:0});const v=vendors.get(vk)!;v.committed=this.r(v.committed+Number(po.subtotal||0));v.poCount+=1;for(const l of po.lines||[]){const k=`${po.currency}:${l.chargeCode}`;if(!charges.has(k))charges.set(k,{chargeCode:l.chargeCode,currency:po.currency,committed:0,lineCount:0});const c=charges.get(k)!;c.committed=this.r(c.committed+Number(l.amount||0));c.lineCount+=1;}}return {period,poCount:pos.length,totalByCurrency:Array.from(new Set(pos.map((p:any)=>String(p.currency)))).map((currency:string)=>({currency,amount:this.r(pos.filter((p:any)=>p.currency===currency).reduce((s:number,p:any)=>s+Number(p.subtotal||0),0))})),byVendor:Array.from(vendors.values()).sort((a:any,b:any)=>b.committed-a.committed),byCharge:Array.from(charges.values()).sort((a:any,b:any)=>b.committed-a.committed)};}
  async dashboard(u:ScopeUser){this.internal(u);const [pos,matches]=await Promise.all([this.data.accessiblePOs(u),this.scopedMatches(u)]);return {poCount:pos.length,draftCount:pos.filter((p:any)=>p.status==='DRAFT').length,awaitingApproval:pos.filter((p:any)=>p.status==='SUBMITTED').length,openCommitments:pos.filter((p:any)=>['APPROVED','PART_RECEIVED'].includes(p.status)).length,receivedAwaitingClose:pos.filter((p:any)=>p.status==='RECEIVED').length,apMatchExceptions:matches.filter((m:any)=>m.status==='EXCEPTION').length,matchedInvoices:matches.filter((m:any)=>['MATCHED','OVERRIDDEN'].includes(m.status)).length};}
}
