import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { ScopeService } from '../auth/scope.service';
import { ScopeUser } from '../auth/scope';
import { AuditService } from '../audit/audit.service';

const SRC='ANCLINE_MONTH_END',GL='ANCLINE_GL',STAT='ANCLINE_STATUTORY_FINANCE',ACC='ANCLINE_ACCOUNTING',TREAS='ANCLINE_TREASURY',CREDIT='ANCLINE_CREDIT_CONTROL',GROUP='ANCLINE_GROUP_FINANCE';

@Injectable()
export class MonthEndService {
  constructor(private prisma:PrismaService,private scope:ScopeService,private audit:AuditService){}
  private get db():any{return this.prisma as any;}
  private access(u:ScopeUser){this.scope.assertFinanceAccess(u);}
  private p(e:any){return (e?.payload||{}) as any;}
  private r(v:any){return Math.round((Number(v||0)+Number.EPSILON)*100)/100;}
  private req(v:any,n:string){const s=String(v??'').trim();if(!s)throw new BadRequestException(`${n} is required`);return s;}
  private per(v:any){const s=String(v||'');if(!/^\d{4}-\d{2}$/.test(s))throw new BadRequestException('Period must be YYYY-MM');return s;}
  private cur(v:any){const s=String(v||'USD').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(s))throw new BadRequestException('Currency must be a 3-letter code');return s;}
  private dt(v:any,n='Date'){const d=new Date(v);if(Number.isNaN(d.getTime()))throw new BadRequestException(`${n} is invalid`);return d;}
  private periodOf(v:any){const d=this.dt(v);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
  private addMonths(period:string,n:number){const [y,m]=this.per(period).split('-').map(Number);const d=new Date(Date.UTC(y,m-1+n,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
  private monthDiff(a:string,b:string){const [ay,am]=this.per(a).split('-').map(Number),[by,bm]=this.per(b).split('-').map(Number);return (by-ay)*12+(bm-am);}
  private periodEnd(period:string){const [y,m]=this.per(period).split('-').map(Number);return new Date(Date.UTC(y,m,0,12,0,0)).toISOString();}
  private firstDay(period:string){return `${this.per(period)}-01T12:00:00.000Z`;}

  private async periodStatus(period:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GL,objectType:'FiscalPeriod',objectId:period},orderBy:{createdAt:'asc'}});return rows.length?String(this.p(rows[rows.length-1]).status||'OPEN'):'OPEN';}
  private async setPeriod(period:string,status:string,note:string,u:ScopeUser){await this.db.integrationEvent.create({data:{sourceSystem:GL,eventType:'PERIOD_STATUS_SET',externalId:period,objectType:'FiscalPeriod',objectId:period,status:'COMPLETED',payload:{period,status,note,actorId:u.sub},completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'MONTH_END_PERIOD_SET',objectType:'FiscalPeriod',objectId:period,detail:{status,note}});return {period,status};}

  private async entityMap(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:STAT,objectType:'LegalEntity',eventType:'LEGAL_ENTITY_SET'},orderBy:{createdAt:'asc'}});const m=new Map<string,any>();for(const e of rows)m.set(e.objectId,{entityId:e.objectId,...this.p(e)});return m;}
  async legalEntities(u:ScopeUser){this.access(u);return Array.from((await this.entityMap()).values()).filter((x:any)=>x.active!==false).sort((a:any,b:any)=>String(a.entityCode).localeCompare(String(b.entityCode)));}
  private async entity(id:string){const e=(await this.entityMap()).get(id);if(!e||e.active===false)throw new BadRequestException('Legal entity is not configured or inactive');return e;}

  private buildJournal(rows:any[]){const c=rows.find((e:any)=>e.eventType==='JOURNAL_CREATED');if(!c)return null;const posted=rows.find((e:any)=>e.eventType==='JOURNAL_POSTED'),rev=rows.find((e:any)=>e.eventType==='JOURNAL_REVERSED');return {...this.p(c),journalNo:c.objectId,status:rev?'REVERSED':posted?'POSTED':'DRAFT',createdAt:c.createdAt};}
  private async journalsRaw(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GL,objectType:'JournalEntry'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}return Array.from(g.values()).map((x:any[])=>this.buildJournal(x)).filter(Boolean) as any[];}
  private async postJournal(input:any,u:ScopeUser){const period=this.periodOf(input.journalDate);if(await this.periodStatus(period)==='CLOSED')throw new BadRequestException(`Period ${period} is closed`);const journals=await this.journalsRaw();const existing=journals.find((j:any)=>j.reference===input.reference);if(existing)return existing;const lines=(input.lines||[]).map((l:any)=>({...l,debit:this.r(l.debit),credit:this.r(l.credit),entityId:l.entityId||input.legalEntityId||null}));const debit=this.r(lines.reduce((s:number,l:any)=>s+Number(l.debit||0),0)),credit=this.r(lines.reduce((s:number,l:any)=>s+Number(l.credit||0),0));if(Math.abs(debit-credit)>0.005)throw new BadRequestException('Generated journal is not balanced');const no=String(input.journalNo||`${input.prefix||'ME'}-${period.replace('-','')}-${Date.now().toString().slice(-7)}`).toUpperCase();const payload={journalNo:no,journalDate:new Date(input.journalDate).toISOString(),period,currency:this.cur(input.currency),description:input.description||null,reference:input.reference,source:input.source||'MONTH_END',entityId:input.legalEntityId||null,legalEntityId:input.legalEntityId||null,lines,totalDebit:debit,totalCredit:credit};const now=new Date();await this.db.$transaction([this.db.integrationEvent.create({data:{sourceSystem:GL,eventType:'JOURNAL_CREATED',externalId:no,objectType:'JournalEntry',objectId:no,status:'COMPLETED',payload,completedAt:now}}),this.db.integrationEvent.create({data:{sourceSystem:GL,eventType:'JOURNAL_POSTED',externalId:no,objectType:'JournalEntry',objectId:no,status:'COMPLETED',payload:{journalNo:no,postedBy:u.sub,automated:true,sourceReference:input.reference},completedAt:now}})]);await this.audit.log({actorId:u.sub,action:'MONTH_END_GL_POST',objectType:'JournalEntry',objectId:no,detail:{reference:input.reference,period,currency:payload.currency,debit,credit}});return {...payload,status:'POSTED'};}

  private async accrualMap(period?:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'Accrual'},orderBy:{createdAt:'asc'}}),m=new Map<string,any>(),posts=new Map<string,any>();for(const e of rows){const p=this.p(e);if(e.eventType==='ACCRUAL_SET'&&(!period||p.period===period))m.set(e.objectId,{accrualId:e.objectId,...p,updatedAt:e.createdAt});if(e.eventType==='ACCRUAL_POSTED')posts.set(e.objectId,{...p,postedAt:e.createdAt});}for(const [id,a] of m){const x=posts.get(id);a.posting=x&&String(x.version)===String(a.version)?x:null;a.status=a.posting?'POSTED':'PENDING';}return m;}
  async accruals(period:string|undefined,u:ScopeUser){this.access(u);return Array.from((await this.accrualMap(period)).values());}
  async createAccrual(b:any,u:ScopeUser){this.access(u);const period=this.per(b?.period),legalEntityId=this.req(b?.legalEntityId,'Legal entity'),e=await this.entity(legalEntityId);if(await this.periodStatus(period)==='CLOSED')throw new BadRequestException(`Period ${period} is closed`);const amount=this.r(b?.amount);if(amount<=0)throw new BadRequestException('Accrual amount must be greater than zero');const currency=this.cur(b?.currency||e.localCurrency);if(currency!==String(e.localCurrency).toUpperCase())throw new BadRequestException('Accrual currency must match entity local currency');const id=String(b?.accrualId||`ACR-${period.replace('-','')}-${Date.now().toString().slice(-7)}`).toUpperCase(),version=String(Date.now());const payload={accrualId:id,version,period,legalEntityId,entityCode:e.entityCode,currency,amount,expenseAccount:String(b?.expenseAccount||'6000-OPERATING-EXPENSE').toUpperCase(),accrualAccount:String(b?.accrualAccount||'2200-ACCRUALS').toUpperCase(),description:this.req(b?.description||'Month-end accrual','Description'),reference:b?.reference?String(b.reference):null,autoReverse:b?.autoReverse!==false,createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'ACCRUAL_SET',externalId:id,objectType:'Accrual',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});await this.audit.log({actorId:u.sub,action:'MONTH_END_ACCRUAL_SET',objectType:'Accrual',objectId:id,detail:payload});return {...payload,status:'PENDING'};}
  async postAccrual(id:string,u:ScopeUser){this.access(u);const a=(await this.accrualMap()).get(id);if(!a)throw new NotFoundException('Accrual not found');if(a.posting)return a;if(a.autoReverse&&await this.periodStatus(this.addMonths(a.period,1))==='CLOSED')throw new BadRequestException(`Reversal period ${this.addMonths(a.period,1)} is closed`);const ref=`ME:ACCRUAL:${id}:${a.version}`;const j=await this.postJournal({journalDate:this.periodEnd(a.period),currency:a.currency,legalEntityId:a.legalEntityId,reference:ref,source:'MONTH_END_ACCRUAL',prefix:'AC',description:a.description,lines:[{account:a.expenseAccount,description:a.description,debit:a.amount,credit:0},{account:a.accrualAccount,description:a.description,debit:0,credit:a.amount}]},u);let reversalJournalNo:null|string=null;if(a.autoReverse){const next=this.addMonths(a.period,1),rj=await this.postJournal({journalDate:this.firstDay(next),currency:a.currency,legalEntityId:a.legalEntityId,reference:`ME:ACCRUAL-REV:${id}:${a.version}`,source:'MONTH_END_ACCRUAL_REVERSAL',prefix:'AR',description:`Reversal · ${a.description}`,lines:[{account:a.accrualAccount,description:`Reversal · ${a.description}`,debit:a.amount,credit:0},{account:a.expenseAccount,description:`Reversal · ${a.description}`,debit:0,credit:a.amount}]},u);reversalJournalNo=rj.journalNo;}const payload={accrualId:id,version:a.version,journalNo:j.journalNo,reversalJournalNo,postedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'ACCRUAL_POSTED',externalId:id,objectType:'Accrual',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {...a,posting:payload,status:'POSTED'};}

  private async prepaymentMap(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'Prepayment'},orderBy:{createdAt:'asc'}}),m=new Map<string,any>();for(const e of rows){const p=this.p(e);if(e.eventType==='PREPAYMENT_SET')m.set(e.objectId,{prepaymentId:e.objectId,...p,createdAt:e.createdAt,recognitions:[]});else if(e.eventType==='PREPAYMENT_RECOGNIZED'){const x=m.get(e.objectId);if(x)x.recognitions.push({...p,postedAt:e.createdAt});}}for(const x of m.values()){x.recognizedAmount=this.r((x.recognitions||[]).reduce((s:number,v:any)=>s+Number(v.amount||0),0));x.remainingAmount=this.r(Math.max(0,Number(x.totalAmount)-x.recognizedAmount));}return m;}
  async prepayments(u:ScopeUser){this.access(u);return Array.from((await this.prepaymentMap()).values());}
  async createPrepayment(b:any,u:ScopeUser){this.access(u);const legalEntityId=this.req(b?.legalEntityId,'Legal entity'),e=await this.entity(legalEntityId),totalAmount=this.r(b?.totalAmount),periods=Math.floor(Number(b?.periods));if(totalAmount<=0)throw new BadRequestException('Prepayment amount must be greater than zero');if(!Number.isInteger(periods)||periods<1||periods>120)throw new BadRequestException('Prepayment periods must be 1-120');const startPeriod=this.per(b?.startPeriod),currency=this.cur(b?.currency||e.localCurrency);if(currency!==String(e.localCurrency).toUpperCase())throw new BadRequestException('Prepayment currency must match entity local currency');const id=String(b?.prepaymentId||`PP-${startPeriod.replace('-','')}-${Date.now().toString().slice(-7)}`).toUpperCase();const payload={prepaymentId:id,legalEntityId,entityCode:e.entityCode,currency,totalAmount,startPeriod,periods,prepaidAccount:String(b?.prepaidAccount||'1300-PREPAYMENTS').toUpperCase(),expenseAccount:String(b?.expenseAccount||'6000-OPERATING-EXPENSE').toUpperCase(),description:this.req(b?.description||'Prepayment amortization','Description'),createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'PREPAYMENT_SET',externalId:id,objectType:'Prepayment',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {...payload,recognitions:[],recognizedAmount:0,remainingAmount:totalAmount};}
  async recognizePrepayment(id:string,periodInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput),x=(await this.prepaymentMap()).get(id);if(!x)throw new NotFoundException('Prepayment not found');const index=this.monthDiff(x.startPeriod,period);if(index<0||index>=Number(x.periods))throw new BadRequestException('Period is outside the prepayment schedule');if((x.recognitions||[]).some((v:any)=>v.period===period))return x;const base=this.r(Number(x.totalAmount)/Number(x.periods)),amount=index===Number(x.periods)-1?this.r(Number(x.totalAmount)-base*(Number(x.periods)-1)):base;const j=await this.postJournal({journalDate:this.periodEnd(period),currency:x.currency,legalEntityId:x.legalEntityId,reference:`ME:PREPAY:${id}:${period}`,source:'MONTH_END_PREPAYMENT',prefix:'PP',description:x.description,lines:[{account:x.expenseAccount,description:x.description,debit:amount,credit:0},{account:x.prepaidAccount,description:x.description,debit:0,credit:amount}]},u);const payload={prepaymentId:id,period,amount,journalNo:j.journalNo,postedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'PREPAYMENT_RECOGNIZED',externalId:`${id}:${period}`,objectType:'Prepayment',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return payload;}

  private async assetMap(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'FixedAsset'},orderBy:{createdAt:'asc'}}),m=new Map<string,any>();for(const e of rows){const p=this.p(e);if(e.eventType==='ASSET_SET')m.set(e.objectId,{assetId:e.objectId,...p,createdAt:e.createdAt,depreciation:[]});else if(e.eventType==='ASSET_DEPRECIATION_POSTED'){const x=m.get(e.objectId);if(x)x.depreciation.push({...p,postedAt:e.createdAt});}}for(const x of m.values()){x.accumulatedDepreciation=this.r((x.depreciation||[]).reduce((s:number,v:any)=>s+Number(v.amount||0),0));x.netBookValue=this.r(Math.max(Number(x.salvageValue||0),Number(x.acquisitionCost)-x.accumulatedDepreciation));}return m;}
  async fixedAssets(u:ScopeUser){this.access(u);return Array.from((await this.assetMap()).values());}
  async createFixedAsset(b:any,u:ScopeUser){this.access(u);const legalEntityId=this.req(b?.legalEntityId,'Legal entity'),e=await this.entity(legalEntityId),cost=this.r(b?.acquisitionCost),salvage=this.r(b?.salvageValue),life=Math.floor(Number(b?.usefulLifeMonths));if(cost<=0)throw new BadRequestException('Acquisition cost must be greater than zero');if(salvage<0||salvage>=cost)throw new BadRequestException('Salvage value must be zero or less than acquisition cost');if(!Number.isInteger(life)||life<1||life>600)throw new BadRequestException('Useful life must be 1-600 months');const inServiceDate=this.dt(b?.inServiceDate,'In-service date').toISOString(),currency=this.cur(b?.currency||e.localCurrency);if(currency!==String(e.localCurrency).toUpperCase())throw new BadRequestException('Asset currency must match entity local currency');const id=String(b?.assetId||`FA-${Date.now().toString().slice(-9)}`).toUpperCase();const payload={assetId:id,assetCode:String(b?.assetCode||id).toUpperCase(),assetName:this.req(b?.assetName,'Asset name'),legalEntityId,entityCode:e.entityCode,currency,inServiceDate,acquisitionCost:cost,salvageValue:salvage,usefulLifeMonths:life,method:'STRAIGHT_LINE',assetAccount:String(b?.assetAccount||'1500-FIXED-ASSETS').toUpperCase(),accumulatedDepreciationAccount:String(b?.accumulatedDepreciationAccount||'1590-ACCUM-DEPRECIATION').toUpperCase(),depreciationExpenseAccount:String(b?.depreciationExpenseAccount||'6100-DEPRECIATION-EXPENSE').toUpperCase(),createdBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'ASSET_SET',externalId:id,objectType:'FixedAsset',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {...payload,depreciation:[],accumulatedDepreciation:0,netBookValue:cost};}
  private depreciationDue(a:any,period:string){const start=this.periodOf(a.inServiceDate),index=this.monthDiff(start,period);return index>=0&&index<Number(a.usefulLifeMonths);}
  async depreciateAsset(id:string,periodInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput),a=(await this.assetMap()).get(id);if(!a)throw new NotFoundException('Fixed asset not found');if(!this.depreciationDue(a,period))throw new BadRequestException('Depreciation is not due for this period');if((a.depreciation||[]).some((x:any)=>x.period===period))return a;const index=this.monthDiff(this.periodOf(a.inServiceDate),period),depreciable=this.r(Number(a.acquisitionCost)-Number(a.salvageValue)),base=this.r(depreciable/Number(a.usefulLifeMonths)),amount=index===Number(a.usefulLifeMonths)-1?this.r(depreciable-base*(Number(a.usefulLifeMonths)-1)):base;const j=await this.postJournal({journalDate:this.periodEnd(period),currency:a.currency,legalEntityId:a.legalEntityId,reference:`ME:DEPR:${id}:${period}`,source:'MONTH_END_DEPRECIATION',prefix:'DP',description:`Depreciation · ${a.assetName}`,lines:[{account:a.depreciationExpenseAccount,description:a.assetName,debit:amount,credit:0},{account:a.accumulatedDepreciationAccount,description:a.assetName,debit:0,credit:amount}]},u);const payload={assetId:id,period,amount,journalNo:j.journalNo,postedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'ASSET_DEPRECIATION_POSTED',externalId:`${id}:${period}`,objectType:'FixedAsset',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return payload;}

  private async budgetMap(){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:SRC,objectType:'BudgetLine',eventType:'BUDGET_LINE_SET'},orderBy:{createdAt:'asc'}}),m=new Map<string,any>();for(const e of rows)m.set(e.objectId,{budgetLineId:e.objectId,...this.p(e),updatedAt:e.createdAt});return m;}
  async setBudgetLine(b:any,u:ScopeUser){this.access(u);const period=this.per(b?.period),scenario=String(b?.scenario||'BUDGET').toUpperCase();if(!['BUDGET','FORECAST'].includes(scenario))throw new BadRequestException('Scenario must be BUDGET or FORECAST');const scopeId=String(b?.scopeId||'GROUP').toUpperCase();if(scopeId!=='GROUP')await this.entity(scopeId);const currency=this.cur(b?.currency),account=this.req(b?.account,'Account').toUpperCase(),amount=this.r(b?.amount);if(amount<0)throw new BadRequestException('Budget amount cannot be negative');const id=`${scenario}:${period}:${scopeId}:${currency}:${account}`,payload={scenario,period,scopeId,currency,account,amount,description:b?.description?String(b.description):null,updatedBy:u.sub};await this.db.integrationEvent.create({data:{sourceSystem:SRC,eventType:'BUDGET_LINE_SET',externalId:id,objectType:'BudgetLine',objectId:id,status:'COMPLETED',payload,completedAt:new Date()}});return {budgetLineId:id,...payload};}
  async budgetVariance(periodInput:string,scenarioInput:string,scopeInput:string,currencyInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput),scenario=String(scenarioInput||'BUDGET').toUpperCase(),scopeId=String(scopeInput||'GROUP').toUpperCase(),currency=this.cur(currencyInput||'USD');const budgets=Array.from((await this.budgetMap()).values()).filter((x:any)=>x.period===period&&x.scenario===scenario&&x.scopeId===scopeId&&x.currency===currency),journals=(await this.journalsRaw()).filter((j:any)=>j.status==='POSTED'&&j.period===period&&String(j.currency).toUpperCase()===currency);const actual=new Map<string,number>();for(const j of journals){const jEntity=String(j.legalEntityId||j.entityId||'');if(scopeId!=='GROUP'&&jEntity!==scopeId)continue;for(const l of j.lines||[]){if(scopeId!=='GROUP'&&jEntity!==scopeId&&String(l.entityId||'')!==scopeId)continue;const account=String(l.account||'').toUpperCase();if(!account)continue;const raw=account.startsWith('4')?Number(l.credit||0)-Number(l.debit||0):Number(l.debit||0)-Number(l.credit||0);actual.set(account,this.r((actual.get(account)||0)+raw));}}const bmap=new Map(budgets.map((x:any)=>[x.account,Number(x.amount||0)])),accounts=Array.from(new Set([...bmap.keys(),...actual.keys()])).sort();return accounts.map(account=>{const budget=this.r(bmap.get(account)||0),act=this.r(actual.get(account)||0),variance=this.r(act-budget);return {period,scenario,scopeId,currency,account,budget,actual:act,variance,variancePct:budget?this.r(variance/Math.abs(budget)*100):null,status:budget===0&&act!==0?'UNBUDGETED':Math.abs(variance)<0.005?'ON_PLAN':variance>0?'ABOVE':'BELOW'};});}

  private async subledgerBlockers(period:string,refs:Set<string>){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:ACC,objectType:'FinanceInvoice'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [invoiceNo,ev] of g){const issued=ev.find((e:any)=>e.eventType==='INVOICE_ISSUED'),voided=[...ev].reverse().find((e:any)=>e.eventType==='INVOICE_VOIDED');if(issued&&this.periodOf(issued.createdAt)===period&&!voided&&!refs.has(`INVOICE:${invoiceNo}:ISSUE`))out.push({type:'UNPOSTED_INVOICE',objectId:invoiceNo,message:`Invoice ${invoiceNo} is issued but not posted to GL`});for(const pay of ev.filter((e:any)=>e.eventType==='PAYMENT_RECORDED'&&Number(this.p(e).amount||0)>0)){if(this.periodOf(this.p(pay).paidAt||pay.createdAt)===period&&!refs.has(`PAYMENT:${pay.id}`))out.push({type:'UNPOSTED_PAYMENT',objectId:pay.id,message:`Payment for ${invoiceNo} is not posted to GL`});}if(voided&&this.periodOf(voided.createdAt)===period&&refs.has(`INVOICE:${invoiceNo}:ISSUE`)&&!refs.has(`VOID:${invoiceNo}:${voided.id}`))out.push({type:'UNPOSTED_VOID',objectId:voided.id,message:`Void for ${invoiceNo} is not posted to GL`});}return out;}
  private async fxBlockers(period:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:STAT,objectType:'FXExposure'},orderBy:{createdAt:'asc'}}),sets=new Map<string,any>(),posts=new Map<string,any>();for(const e of rows){const p=this.p(e);if(e.eventType==='FX_EXPOSURE_SET'&&p.period===period)sets.set(e.objectId,{event:e,...p});if(e.eventType==='FX_REVALUATION_POSTED')posts.set(e.objectId,e);}const out:any[]=[];for(const [id,x] of sets){const p=posts.get(id);if(!p||new Date(p.createdAt).getTime()<new Date(x.event.createdAt).getTime())out.push({type:'FX_REVALUATION_PENDING',objectId:id,message:`FX exposure ${id} has not been revalued`});}return out;}
  private async intercompanyBlockers(period:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:GROUP,objectType:'IntercompanyTransaction'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const c=ev.find((e:any)=>e.eventType==='INTERCOMPANY_CREATED'),posted=ev.find((e:any)=>e.eventType==='INTERCOMPANY_POSTED');if(c&&this.p(c).period===period&&!posted)out.push({type:'INTERCOMPANY_UNPOSTED',objectId:id,message:`Intercompany transaction ${id} is still draft`});}return out;}
  private async treasuryBlockers(period:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:TREAS,objectType:'PaymentRun'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const c=ev.find((e:any)=>e.eventType==='PAYMENT_RUN_CREATED');if(!c||this.periodOf(this.p(c).paymentDate)!==period)continue;const cancelled=ev.find((e:any)=>e.eventType==='PAYMENT_RUN_CANCELLED'),posted=ev.find((e:any)=>e.eventType==='PAYMENT_RUN_POSTED'),approved=ev.find((e:any)=>e.eventType==='PAYMENT_RUN_APPROVED');if(!cancelled&&!posted)out.push({type:approved?'PAYMENT_RUN_APPROVED':'PAYMENT_RUN_DRAFT',objectId:id,message:`Treasury payment run ${id} is ${approved?'approved but not posted':'still draft'}`});}return out;}
  private async bankBlockers(period:string){const rows:any[]=await this.db.integrationEvent.findMany({where:{sourceSystem:CREDIT,objectType:'BankTransaction'},orderBy:{createdAt:'asc'}}),g=new Map<string,any[]>();for(const e of rows){if(!g.has(e.objectId))g.set(e.objectId,[]);g.get(e.objectId)!.push(e);}const out:any[]=[];for(const [id,ev] of g){const imp=ev.find((e:any)=>e.eventType==='BANK_TRANSACTION_IMPORTED');if(!imp||this.periodOf(this.p(imp).bookedAt||imp.createdAt)!==period)continue;const reversals=new Set(ev.filter((e:any)=>e.eventType==='BANK_MATCH_REVERSED').map((e:any)=>String(this.p(e).matchEventId||''))),matches=ev.filter((e:any)=>e.eventType==='BANK_TRANSACTION_MATCHED'&&!reversals.has(e.id)),amount=this.r(this.p(imp).amount),matched=this.r(matches.reduce((s:number,e:any)=>s+Number(this.p(e).amount||0),0));if(amount-matched>0.005)out.push({type:'BANK_UNRECONCILED',objectId:id,message:`Bank transaction ${id} has ${this.r(amount-matched)} ${this.cur(this.p(imp).currency)} unreconciled`});}return out;}

  async closeReadiness(periodInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput),[journals,accrualMap,prepaymentMap,assetMap]=await Promise.all([this.journalsRaw(),this.accrualMap(period),this.prepaymentMap(),this.assetMap()]),refs=new Set(journals.map((j:any)=>String(j.reference||'')).filter(Boolean)),blockers:any[]=[];for(const j of journals.filter((j:any)=>j.period===period&&j.status==='DRAFT'))blockers.push({type:'DRAFT_JOURNAL',objectId:j.journalNo,message:`Journal ${j.journalNo} is still draft`});for(const a of accrualMap.values())if(a.status!=='POSTED')blockers.push({type:'ACCRUAL_PENDING',objectId:a.accrualId,message:`Accrual ${a.accrualId} is not posted`});for(const x of prepaymentMap.values()){const i=this.monthDiff(x.startPeriod,period);if(i>=0&&i<Number(x.periods)&&!(x.recognitions||[]).some((v:any)=>v.period===period))blockers.push({type:'PREPAYMENT_DUE',objectId:x.prepaymentId,message:`Prepayment ${x.prepaymentId} is due for recognition`});}for(const a of assetMap.values())if(this.depreciationDue(a,period)&&!(a.depreciation||[]).some((v:any)=>v.period===period))blockers.push({type:'DEPRECIATION_DUE',objectId:a.assetId,message:`Depreciation is due for ${a.assetCode}`});const extra=await Promise.all([this.subledgerBlockers(period,refs),this.fxBlockers(period),this.intercompanyBlockers(period),this.treasuryBlockers(period),this.bankBlockers(period)]);for(const list of extra)blockers.push(...list);const status=await this.periodStatus(period);return {period,status,ready:blockers.length===0,blockerCount:blockers.length,blockers};}
  async runDue(periodInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput);if(await this.periodStatus(period)==='CLOSED')throw new BadRequestException(`Period ${period} is closed`);const results:any[]=[];for(const a of (await this.accruals(period,u)).filter((x:any)=>x.status!=='POSTED'))try{const x=await this.postAccrual(a.accrualId,u);results.push({type:'ACCRUAL',objectId:a.accrualId,status:'POSTED',journalNo:x.posting?.journalNo||null});}catch(e:any){results.push({type:'ACCRUAL',objectId:a.accrualId,status:'ERROR',message:e.message});}for(const x of await this.prepayments(u)){const i=this.monthDiff(x.startPeriod,period);if(i>=0&&i<Number(x.periods)&&!(x.recognitions||[]).some((v:any)=>v.period===period))try{const r=await this.recognizePrepayment(x.prepaymentId,period,u);results.push({type:'PREPAYMENT',objectId:x.prepaymentId,status:'POSTED',journalNo:r.journalNo});}catch(e:any){results.push({type:'PREPAYMENT',objectId:x.prepaymentId,status:'ERROR',message:e.message});}}for(const a of await this.fixedAssets(u))if(this.depreciationDue(a,period)&&!(a.depreciation||[]).some((v:any)=>v.period===period))try{const r=await this.depreciateAsset(a.assetId,period,u);results.push({type:'DEPRECIATION',objectId:a.assetId,status:'POSTED',journalNo:r.journalNo});}catch(e:any){results.push({type:'DEPRECIATION',objectId:a.assetId,status:'ERROR',message:e.message});}return {period,results,errors:results.filter((x:any)=>x.status==='ERROR').length,posted:results.filter((x:any)=>x.status==='POSTED').length};}
  async softClose(periodInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput);if(await this.periodStatus(period)==='CLOSED')throw new BadRequestException('Closed period must be reopened first');return this.setPeriod(period,'SOFT_CLOSED','Month-end soft close',u);}
  async closePeriod(periodInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput),readiness=await this.closeReadiness(period,u);if(!readiness.ready)throw new BadRequestException(`Month-end has ${readiness.blockerCount} blocker(s)`);return this.setPeriod(period,'CLOSED','Month-end close completed',u);}
  async reopen(periodInput:string,u:ScopeUser){this.access(u);return this.setPeriod(this.per(periodInput),'OPEN','Month-end period reopened',u);}

  async dashboard(periodInput:string,scenarioInput:string,scopeInput:string,currencyInput:string,u:ScopeUser){this.access(u);const period=this.per(periodInput),scenario=String(scenarioInput||'BUDGET').toUpperCase(),scopeId=String(scopeInput||'GROUP').toUpperCase(),currency=this.cur(currencyInput||'USD');const [entities,accruals,prepayments,assets,variance,readiness]=await Promise.all([this.legalEntities(u),this.accruals(period,u),this.prepayments(u),this.fixedAssets(u),this.budgetVariance(period,scenario,scopeId,currency,u),this.closeReadiness(period,u)]);const duePrepayments=prepayments.filter((x:any)=>{const i=this.monthDiff(x.startPeriod,period);return i>=0&&i<Number(x.periods)&&!(x.recognitions||[]).some((v:any)=>v.period===period);}),dueAssets=assets.filter((x:any)=>this.depreciationDue(x,period)&&!(x.depreciation||[]).some((v:any)=>v.period===period));return {period,scenario,scopeId,currency,entities,accruals,prepayments,assets,variance,readiness,kpis:{pendingAccruals:accruals.filter((x:any)=>x.status!=='POSTED').length,duePrepayments:duePrepayments.length,dueDepreciation:dueAssets.length,closeBlockers:readiness.blockerCount,budgetLines:variance.filter((x:any)=>x.budget!==0).length,unbudgetedActuals:variance.filter((x:any)=>x.status==='UNBUDGETED').length}};}
}
